
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AdminSidebar: typeof import("../../app/components/admin/AdminSidebar.vue")['default']
  AuthGoogleButton: typeof import("../../app/components/auth/AuthGoogleButton.vue")['default']
  UserDashboardCreatorSection: typeof import("../../app/components/dashboard/UserDashboardCreatorSection.vue")['default']
  UserDashboardHistorySection: typeof import("../../app/components/dashboard/UserDashboardHistorySection.vue")['default']
  UserDashboardLayout: typeof import("../../app/components/dashboard/UserDashboardLayout.vue")['default']
  UserDashboardSidebarCompletion: typeof import("../../app/components/dashboard/UserDashboardSidebarCompletion.vue")['default']
  UserDashboardSidebarNav: typeof import("../../app/components/dashboard/UserDashboardSidebarNav.vue")['default']
  UserDashboardSidebarProfileCard: typeof import("../../app/components/dashboard/UserDashboardSidebarProfileCard.vue")['default']
  UserDashboardSubscriptionsSection: typeof import("../../app/components/dashboard/UserDashboardSubscriptionsSection.vue")['default']
  UserDashboardUsageCard: typeof import("../../app/components/dashboard/UserDashboardUsageCard.vue")['default']
  HomeArticles: typeof import("../../app/components/home/HomeArticles.vue")['default']
  HomeCTA: typeof import("../../app/components/home/HomeCTA.vue")['default']
  HomeHero: typeof import("../../app/components/home/HomeHero.vue")['default']
  HomeHighlights: typeof import("../../app/components/home/HomeHighlights.vue")['default']
  HomePageFrame: typeof import("../../app/components/home/HomePageFrame.vue")['default']
  HomePolls: typeof import("../../app/components/home/HomePolls.vue")['default']
  HomeStatsData: typeof import("../../app/components/home/HomeStatsData.vue")['default']
  HomeStatsStrip: typeof import("../../app/components/home/HomeStatsStrip.vue")['default']
  IconCommunity: typeof import("../../app/components/icons/IconCommunity.vue")['default']
  IconDocumentation: typeof import("../../app/components/icons/IconDocumentation.vue")['default']
  IconEcosystem: typeof import("../../app/components/icons/IconEcosystem.vue")['default']
  IconSupport: typeof import("../../app/components/icons/IconSupport.vue")['default']
  IconTooling: typeof import("../../app/components/icons/IconTooling.vue")['default']
  AppAccessibilityPanel: typeof import("../../app/components/layout/AppAccessibilityPanel.vue")['default']
  AppBootstrapError: typeof import("../../app/components/layout/AppBootstrapError.vue")['default']
  AppCreateFab: typeof import("../../app/components/layout/AppCreateFab.vue")['default']
  AppDropdownMenu: typeof import("../../app/components/layout/AppDropdownMenu.vue")['default']
  AppDropdownMenuItem: typeof import("../../app/components/layout/AppDropdownMenuItem.vue")['default']
  AppFooter: typeof import("../../app/components/layout/AppFooter.vue")['default']
  AppHeader: typeof import("../../app/components/layout/AppHeader.vue")['default']
  AppNavIcon: typeof import("../../app/components/layout/AppNavIcon.vue")['default']
  AppNotificationStack: typeof import("../../app/components/layout/AppNotificationStack.vue")['default']
  AppPromoBanner: typeof import("../../app/components/layout/AppPromoBanner.vue")['default']
  AuthLayout: typeof import("../../app/components/login/AuthLayout.vue")['default']
  ForgotPasswordFormCard: typeof import("../../app/components/login/ForgotPasswordFormCard.vue")['default']
  LoginFormCard: typeof import("../../app/components/login/LoginFormCard.vue")['default']
  LoginHeader: typeof import("../../app/components/login/LoginHeader.vue")['default']
  LoginIntroPanel: typeof import("../../app/components/login/LoginIntroPanel.vue")['default']
  RegisterFormCard: typeof import("../../app/components/login/RegisterFormCard.vue")['default']
  GlobalStatusBar: typeof import("../../app/components/notifications/GlobalStatusBar.vue")['default']
  PollCard: typeof import("../../app/components/polls/PollCard.vue")['default']
  PollQuestionBlock: typeof import("../../app/components/polls/PollQuestionBlock.vue")['default']
  StudioHeader: typeof import("../../app/components/studio/StudioHeader.vue")['default']
  StudioSidebarLeft: typeof import("../../app/components/studio/StudioSidebarLeft.vue")['default']
  StudioSidebarRight: typeof import("../../app/components/studio/StudioSidebarRight.vue")['default']
  BarChartBlock: typeof import("../../app/components/studio/blocks/BarChartBlock.vue")['default']
  BlockRenderer: typeof import("../../app/components/studio/blocks/BlockRenderer.vue")['default']
  KpiBlock: typeof import("../../app/components/studio/blocks/KpiBlock.vue")['default']
  LineChartBlock: typeof import("../../app/components/studio/blocks/LineChartBlock.vue")['default']
  SearchBlock: typeof import("../../app/components/studio/blocks/SearchBlock.vue")['default']
  TableBlock: typeof import("../../app/components/studio/blocks/TableBlock.vue")['default']
  TextBlock: typeof import("../../app/components/studio/blocks/TextBlock.vue")['default']
  BlockWrapper: typeof import("../../app/components/studio/canvas/BlockWrapper.vue")['default']
  CanvasGrid: typeof import("../../app/components/studio/canvas/CanvasGrid.vue")['default']
  CanvasPageTabs: typeof import("../../app/components/studio/canvas/CanvasPageTabs.vue")['default']
  CanvasSection: typeof import("../../app/components/studio/canvas/CanvasSection.vue")['default']
  CanvasZone: typeof import("../../app/components/studio/canvas/CanvasZone.vue")['default']
  AddSourceModal: typeof import("../../app/components/studio/sidebar/AddSourceModal.vue")['default']
  BlockConfigPanel: typeof import("../../app/components/studio/sidebar/BlockConfigPanel.vue")['default']
  DynamicParamsPanel: typeof import("../../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']
  SidebarBlocks: typeof import("../../app/components/studio/sidebar/SidebarBlocks.vue")['default']
  SidebarDataSources: typeof import("../../app/components/studio/sidebar/SidebarDataSources.vue")['default']
  SidebarLayouts: typeof import("../../app/components/studio/sidebar/SidebarLayouts.vue")['default']
  SidebarVariables: typeof import("../../app/components/studio/sidebar/SidebarVariables.vue")['default']
  TvAudiencesEvolutionChart: typeof import("../../app/components/tv/TvAudiencesEvolutionChart.vue")['default']
  TvAudiencesRankingTable: typeof import("../../app/components/tv/TvAudiencesRankingTable.vue")['default']
  TvAudiencesTop50Table: typeof import("../../app/components/tv/TvAudiencesTop50Table.vue")['default']
  TvProgrammeCardIcon: typeof import("../../app/components/tv/TvProgrammeCardIcon.vue")['default']
  TvReviewModal: typeof import("../../app/components/tv/TvReviewModal.vue")['default']
  TvScheduleChannelRow: typeof import("../../app/components/tv/TvScheduleChannelRow.vue")['default']
  TvScheduleGrid: typeof import("../../app/components/tv/TvScheduleGrid.vue")['default']
  TvScheduleNowNext: typeof import("../../app/components/tv/TvScheduleNowNext.vue")['default']
  TvScheduleProgrammeBlock: typeof import("../../app/components/tv/TvScheduleProgrammeBlock.vue")['default']
  TvScheduleTimeline: typeof import("../../app/components/tv/TvScheduleTimeline.vue")['default']
  AppAvatar: typeof import("../../app/components/ui/AppAvatar.vue")['default']
  AppButton: typeof import("../../app/components/ui/AppButton.vue")['default']
  AppCheckbox: typeof import("../../app/components/ui/AppCheckbox.vue")['default']
  AppColorPickerModal: typeof import("../../app/components/ui/AppColorPickerModal.vue")['default']
  AppModal: typeof import("../../app/components/ui/AppModal.vue")['default']
  AppSelect: typeof import("../../app/components/ui/AppSelect.vue")['default']
  AppStepModal: typeof import("../../app/components/ui/AppStepModal.vue")['default']
  AppWordmark: typeof import("../../app/components/ui/AppWordmark.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAdminSidebar: LazyComponent<typeof import("../../app/components/admin/AdminSidebar.vue")['default']>
  LazyAuthGoogleButton: LazyComponent<typeof import("../../app/components/auth/AuthGoogleButton.vue")['default']>
  LazyUserDashboardCreatorSection: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardCreatorSection.vue")['default']>
  LazyUserDashboardHistorySection: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardHistorySection.vue")['default']>
  LazyUserDashboardLayout: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardLayout.vue")['default']>
  LazyUserDashboardSidebarCompletion: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSidebarCompletion.vue")['default']>
  LazyUserDashboardSidebarNav: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSidebarNav.vue")['default']>
  LazyUserDashboardSidebarProfileCard: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSidebarProfileCard.vue")['default']>
  LazyUserDashboardSubscriptionsSection: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSubscriptionsSection.vue")['default']>
  LazyUserDashboardUsageCard: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardUsageCard.vue")['default']>
  LazyHomeArticles: LazyComponent<typeof import("../../app/components/home/HomeArticles.vue")['default']>
  LazyHomeCTA: LazyComponent<typeof import("../../app/components/home/HomeCTA.vue")['default']>
  LazyHomeHero: LazyComponent<typeof import("../../app/components/home/HomeHero.vue")['default']>
  LazyHomeHighlights: LazyComponent<typeof import("../../app/components/home/HomeHighlights.vue")['default']>
  LazyHomePageFrame: LazyComponent<typeof import("../../app/components/home/HomePageFrame.vue")['default']>
  LazyHomePolls: LazyComponent<typeof import("../../app/components/home/HomePolls.vue")['default']>
  LazyHomeStatsData: LazyComponent<typeof import("../../app/components/home/HomeStatsData.vue")['default']>
  LazyHomeStatsStrip: LazyComponent<typeof import("../../app/components/home/HomeStatsStrip.vue")['default']>
  LazyIconCommunity: LazyComponent<typeof import("../../app/components/icons/IconCommunity.vue")['default']>
  LazyIconDocumentation: LazyComponent<typeof import("../../app/components/icons/IconDocumentation.vue")['default']>
  LazyIconEcosystem: LazyComponent<typeof import("../../app/components/icons/IconEcosystem.vue")['default']>
  LazyIconSupport: LazyComponent<typeof import("../../app/components/icons/IconSupport.vue")['default']>
  LazyIconTooling: LazyComponent<typeof import("../../app/components/icons/IconTooling.vue")['default']>
  LazyAppAccessibilityPanel: LazyComponent<typeof import("../../app/components/layout/AppAccessibilityPanel.vue")['default']>
  LazyAppBootstrapError: LazyComponent<typeof import("../../app/components/layout/AppBootstrapError.vue")['default']>
  LazyAppCreateFab: LazyComponent<typeof import("../../app/components/layout/AppCreateFab.vue")['default']>
  LazyAppDropdownMenu: LazyComponent<typeof import("../../app/components/layout/AppDropdownMenu.vue")['default']>
  LazyAppDropdownMenuItem: LazyComponent<typeof import("../../app/components/layout/AppDropdownMenuItem.vue")['default']>
  LazyAppFooter: LazyComponent<typeof import("../../app/components/layout/AppFooter.vue")['default']>
  LazyAppHeader: LazyComponent<typeof import("../../app/components/layout/AppHeader.vue")['default']>
  LazyAppNavIcon: LazyComponent<typeof import("../../app/components/layout/AppNavIcon.vue")['default']>
  LazyAppNotificationStack: LazyComponent<typeof import("../../app/components/layout/AppNotificationStack.vue")['default']>
  LazyAppPromoBanner: LazyComponent<typeof import("../../app/components/layout/AppPromoBanner.vue")['default']>
  LazyAuthLayout: LazyComponent<typeof import("../../app/components/login/AuthLayout.vue")['default']>
  LazyForgotPasswordFormCard: LazyComponent<typeof import("../../app/components/login/ForgotPasswordFormCard.vue")['default']>
  LazyLoginFormCard: LazyComponent<typeof import("../../app/components/login/LoginFormCard.vue")['default']>
  LazyLoginHeader: LazyComponent<typeof import("../../app/components/login/LoginHeader.vue")['default']>
  LazyLoginIntroPanel: LazyComponent<typeof import("../../app/components/login/LoginIntroPanel.vue")['default']>
  LazyRegisterFormCard: LazyComponent<typeof import("../../app/components/login/RegisterFormCard.vue")['default']>
  LazyGlobalStatusBar: LazyComponent<typeof import("../../app/components/notifications/GlobalStatusBar.vue")['default']>
  LazyPollCard: LazyComponent<typeof import("../../app/components/polls/PollCard.vue")['default']>
  LazyPollQuestionBlock: LazyComponent<typeof import("../../app/components/polls/PollQuestionBlock.vue")['default']>
  LazyStudioHeader: LazyComponent<typeof import("../../app/components/studio/StudioHeader.vue")['default']>
  LazyStudioSidebarLeft: LazyComponent<typeof import("../../app/components/studio/StudioSidebarLeft.vue")['default']>
  LazyStudioSidebarRight: LazyComponent<typeof import("../../app/components/studio/StudioSidebarRight.vue")['default']>
  LazyBarChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/BarChartBlock.vue")['default']>
  LazyBlockRenderer: LazyComponent<typeof import("../../app/components/studio/blocks/BlockRenderer.vue")['default']>
  LazyKpiBlock: LazyComponent<typeof import("../../app/components/studio/blocks/KpiBlock.vue")['default']>
  LazyLineChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LineChartBlock.vue")['default']>
  LazySearchBlock: LazyComponent<typeof import("../../app/components/studio/blocks/SearchBlock.vue")['default']>
  LazyTableBlock: LazyComponent<typeof import("../../app/components/studio/blocks/TableBlock.vue")['default']>
  LazyTextBlock: LazyComponent<typeof import("../../app/components/studio/blocks/TextBlock.vue")['default']>
  LazyBlockWrapper: LazyComponent<typeof import("../../app/components/studio/canvas/BlockWrapper.vue")['default']>
  LazyCanvasGrid: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasGrid.vue")['default']>
  LazyCanvasPageTabs: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasPageTabs.vue")['default']>
  LazyCanvasSection: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasSection.vue")['default']>
  LazyCanvasZone: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasZone.vue")['default']>
  LazyAddSourceModal: LazyComponent<typeof import("../../app/components/studio/sidebar/AddSourceModal.vue")['default']>
  LazyBlockConfigPanel: LazyComponent<typeof import("../../app/components/studio/sidebar/BlockConfigPanel.vue")['default']>
  LazyDynamicParamsPanel: LazyComponent<typeof import("../../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']>
  LazySidebarBlocks: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarBlocks.vue")['default']>
  LazySidebarDataSources: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarDataSources.vue")['default']>
  LazySidebarLayouts: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarLayouts.vue")['default']>
  LazySidebarVariables: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarVariables.vue")['default']>
  LazyTvAudiencesEvolutionChart: LazyComponent<typeof import("../../app/components/tv/TvAudiencesEvolutionChart.vue")['default']>
  LazyTvAudiencesRankingTable: LazyComponent<typeof import("../../app/components/tv/TvAudiencesRankingTable.vue")['default']>
  LazyTvAudiencesTop50Table: LazyComponent<typeof import("../../app/components/tv/TvAudiencesTop50Table.vue")['default']>
  LazyTvProgrammeCardIcon: LazyComponent<typeof import("../../app/components/tv/TvProgrammeCardIcon.vue")['default']>
  LazyTvReviewModal: LazyComponent<typeof import("../../app/components/tv/TvReviewModal.vue")['default']>
  LazyTvScheduleChannelRow: LazyComponent<typeof import("../../app/components/tv/TvScheduleChannelRow.vue")['default']>
  LazyTvScheduleGrid: LazyComponent<typeof import("../../app/components/tv/TvScheduleGrid.vue")['default']>
  LazyTvScheduleNowNext: LazyComponent<typeof import("../../app/components/tv/TvScheduleNowNext.vue")['default']>
  LazyTvScheduleProgrammeBlock: LazyComponent<typeof import("../../app/components/tv/TvScheduleProgrammeBlock.vue")['default']>
  LazyTvScheduleTimeline: LazyComponent<typeof import("../../app/components/tv/TvScheduleTimeline.vue")['default']>
  LazyAppAvatar: LazyComponent<typeof import("../../app/components/ui/AppAvatar.vue")['default']>
  LazyAppButton: LazyComponent<typeof import("../../app/components/ui/AppButton.vue")['default']>
  LazyAppCheckbox: LazyComponent<typeof import("../../app/components/ui/AppCheckbox.vue")['default']>
  LazyAppColorPickerModal: LazyComponent<typeof import("../../app/components/ui/AppColorPickerModal.vue")['default']>
  LazyAppModal: LazyComponent<typeof import("../../app/components/ui/AppModal.vue")['default']>
  LazyAppSelect: LazyComponent<typeof import("../../app/components/ui/AppSelect.vue")['default']>
  LazyAppStepModal: LazyComponent<typeof import("../../app/components/ui/AppStepModal.vue")['default']>
  LazyAppWordmark: LazyComponent<typeof import("../../app/components/ui/AppWordmark.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
