import type { Component } from 'vue'
import {
  AcademicCapIcon,
  BanknotesIcon,
  BeakerIcon,
  BoltIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingStorefrontIcon,
  CakeIcon,
  CalendarDaysIcon,
  CameraIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleLeftRightIcon,
  CloudIcon,
  CpuChipIcon,
  CurrencyEuroIcon,
  FilmIcon,
  FireIcon,
  FlagIcon,
  GlobeAltIcon,
  HandRaisedIcon,
  HeartIcon,
  HomeModernIcon,
  LightBulbIcon,
  MapIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  PaintBrushIcon,
  RocketLaunchIcon,
  ScaleIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SunIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UsersIcon,
  WrenchScrewdriverIcon,
} from '@heroicons/vue/24/outline'

/**
 * Icônes proposées pour une catégorie (contenu, chaîne, TV). Les clés sont des
 * noms Heroicons stockés en base et pilotés en back-office Filament — cette liste
 * doit rester alignée sur `App\Support\CategoryIcons::OPTIONS` côté statsio-api.
 */
export const CATEGORY_ICON_COMPONENTS: Record<string, Component> = {
  'academic-cap': AcademicCapIcon,
  banknotes: BanknotesIcon,
  beaker: BeakerIcon,
  bolt: BoltIcon,
  'book-open': BookOpenIcon,
  briefcase: BriefcaseIcon,
  'building-library': BuildingLibraryIcon,
  'building-office-2': BuildingOffice2Icon,
  'building-storefront': BuildingStorefrontIcon,
  cake: CakeIcon,
  'calendar-days': CalendarDaysIcon,
  camera: CameraIcon,
  'chart-bar': ChartBarIcon,
  'chart-pie': ChartPieIcon,
  'chat-bubble-left-right': ChatBubbleLeftRightIcon,
  cloud: CloudIcon,
  'cpu-chip': CpuChipIcon,
  'currency-euro': CurrencyEuroIcon,
  film: FilmIcon,
  fire: FireIcon,
  flag: FlagIcon,
  'globe-alt': GlobeAltIcon,
  'hand-raised': HandRaisedIcon,
  heart: HeartIcon,
  'home-modern': HomeModernIcon,
  'light-bulb': LightBulbIcon,
  map: MapIcon,
  megaphone: MegaphoneIcon,
  microphone: MicrophoneIcon,
  'musical-note': MusicalNoteIcon,
  newspaper: NewspaperIcon,
  'paint-brush': PaintBrushIcon,
  'rocket-launch': RocketLaunchIcon,
  scale: ScaleIcon,
  'shield-check': ShieldCheckIcon,
  sparkles: SparklesIcon,
  sun: SunIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  tv: TvIcon,
  users: UsersIcon,
  'wrench-screwdriver': WrenchScrewdriverIcon,
}

export function resolveCategoryIconComponent(name: string | null | undefined): Component | null {
  if (!name) return null
  return CATEGORY_ICON_COMPONENTS[name] ?? null
}
