
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const CookieBanner: typeof import("../app/components/CookieBanner.vue")['default']
export const ArticleBody: typeof import("../app/components/articles/ArticleBody.vue")['default']
export const ArticleCatalogCard: typeof import("../app/components/articles/ArticleCatalogCard.vue")['default']
export const ArticleCatalogRow: typeof import("../app/components/articles/ArticleCatalogRow.vue")['default']
export const ArticleDetailView: typeof import("../app/components/articles/ArticleDetailView.vue")['default']
export const ArticleFeaturedCard: typeof import("../app/components/articles/ArticleFeaturedCard.vue")['default']
export const ArticleHero: typeof import("../app/components/articles/ArticleHero.vue")['default']
export const ArticleSubHeader: typeof import("../app/components/articles/ArticleSubHeader.vue")['default']
export const ArticleTeaserCard: typeof import("../app/components/articles/ArticleTeaserCard.vue")['default']
export const ArticleToc: typeof import("../app/components/articles/ArticleToc.vue")['default']
export const ArticlesListingView: typeof import("../app/components/articles/ArticlesListingView.vue")['default']
export const AuthBrandPanel: typeof import("../app/components/auth/AuthBrandPanel.vue")['default']
export const AuthCard: typeof import("../app/components/auth/AuthCard.vue")['default']
export const AuthDivider: typeof import("../app/components/auth/AuthDivider.vue")['default']
export const AuthErrorAlert: typeof import("../app/components/auth/AuthErrorAlert.vue")['default']
export const AuthGoogleButton: typeof import("../app/components/auth/AuthGoogleButton.vue")['default']
export const AuthInputField: typeof import("../app/components/auth/AuthInputField.vue")['default']
export const AuthShell: typeof import("../app/components/auth/AuthShell.vue")['default']
export const AuthStatCard: typeof import("../app/components/auth/AuthStatCard.vue")['default']
export const AuthTopBar: typeof import("../app/components/auth/AuthTopBar.vue")['default']
export const ForgotPasswordFormCard: typeof import("../app/components/auth/ForgotPasswordFormCard.vue")['default']
export const LoginFormCard: typeof import("../app/components/auth/LoginFormCard.vue")['default']
export const PasswordStrengthMeter: typeof import("../app/components/auth/PasswordStrengthMeter.vue")['default']
export const RegisterFormCard: typeof import("../app/components/auth/RegisterFormCard.vue")['default']
export const ResetPasswordFormCard: typeof import("../app/components/auth/ResetPasswordFormCard.vue")['default']
export const VerifyEmailFormCard: typeof import("../app/components/auth/VerifyEmailFormCard.vue")['default']
export const ChannelConsentModal: typeof import("../app/components/chaines/ChannelConsentModal.vue")['default']
export const ChannelCreateCard: typeof import("../app/components/chaines/ChannelCreateCard.vue")['default']
export const ChannelBadgeList: typeof import("../app/components/channels/ChannelBadgeList.vue")['default']
export const ChannelCard: typeof import("../app/components/channels/ChannelCard.vue")['default']
export const ChannelCatalogCard: typeof import("../app/components/channels/ChannelCatalogCard.vue")['default']
export const ChannelCatalogRow: typeof import("../app/components/channels/ChannelCatalogRow.vue")['default']
export const ChannelContentTypeFilter: typeof import("../app/components/channels/ChannelContentTypeFilter.vue")['default']
export const ChannelFeaturedCard: typeof import("../app/components/channels/ChannelFeaturedCard.vue")['default']
export const ChannelInviteMembersModal: typeof import("../app/components/channels/ChannelInviteMembersModal.vue")['default']
export const ChannelOrganizationBadge: typeof import("../app/components/channels/ChannelOrganizationBadge.vue")['default']
export const ChannelPopularityCard: typeof import("../app/components/channels/ChannelPopularityCard.vue")['default']
export const ChannelSwitcher: typeof import("../app/components/channels/ChannelSwitcher.vue")['default']
export const ChannelVerifiedBadge: typeof import("../app/components/channels/ChannelVerifiedBadge.vue")['default']
export const ChannelsListingView: typeof import("../app/components/channels/ChannelsListingView.vue")['default']
export const ChannelDashboardHeader: typeof import("../app/components/channels/dashboard/ChannelDashboardHeader.vue")['default']
export const ChannelDashboardSearch: typeof import("../app/components/channels/dashboard/ChannelDashboardSearch.vue")['default']
export const ChannelDataSourceRow: typeof import("../app/components/channels/dashboard/ChannelDataSourceRow.vue")['default']
export const ChannelSidebar: typeof import("../app/components/channels/dashboard/ChannelSidebar.vue")['default']
export const ChannelTopbar: typeof import("../app/components/channels/dashboard/ChannelTopbar.vue")['default']
export const ChannelViewsBreakdownCard: typeof import("../app/components/channels/dashboard/ChannelViewsBreakdownCard.vue")['default']
export const ChannelAboutTab: typeof import("../app/components/channels/detail/ChannelAboutTab.vue")['default']
export const ChannelBanner: typeof import("../app/components/channels/detail/ChannelBanner.vue")['default']
export const ChannelBreadcrumb: typeof import("../app/components/channels/detail/ChannelBreadcrumb.vue")['default']
export const ChannelDatasetList: typeof import("../app/components/channels/detail/ChannelDatasetList.vue")['default']
export const ChannelDetailTabs: typeof import("../app/components/channels/detail/ChannelDetailTabs.vue")['default']
export const ChannelDetailView: typeof import("../app/components/channels/detail/ChannelDetailView.vue")['default']
export const ChannelFeaturedTab: typeof import("../app/components/channels/detail/ChannelFeaturedTab.vue")['default']
export const ChannelFeedList: typeof import("../app/components/channels/detail/ChannelFeedList.vue")['default']
export const ChannelPollGridCard: typeof import("../app/components/channels/detail/ChannelPollGridCard.vue")['default']
export const ChannelPollsTab: typeof import("../app/components/channels/detail/ChannelPollsTab.vue")['default']
export const ChannelProfileHeader: typeof import("../app/components/channels/detail/ChannelProfileHeader.vue")['default']
export const ChannelShareModal: typeof import("../app/components/channels/detail/ChannelShareModal.vue")['default']
export const ChannelSimilarSlider: typeof import("../app/components/channels/detail/ChannelSimilarSlider.vue")['default']
export const ChannelStatsStrip: typeof import("../app/components/channels/detail/ChannelStatsStrip.vue")['default']
export const ChannelOrganizationSettings: typeof import("../app/components/channels/settings/ChannelOrganizationSettings.vue")['default']
export const ChannelPrivacySettings: typeof import("../app/components/channels/settings/ChannelPrivacySettings.vue")['default']
export const ChannelProfileSettings: typeof import("../app/components/channels/settings/ChannelProfileSettings.vue")['default']
export const StepChannelCategories: typeof import("../app/components/channels/steps/StepChannelCategories.vue")['default']
export const StepChannelLegal: typeof import("../app/components/channels/steps/StepChannelLegal.vue")['default']
export const ComingSoonGate: typeof import("../app/components/coming-soon/ComingSoonGate.vue")['default']
export const ComingSoonPage: typeof import("../app/components/coming-soon/ComingSoonPage.vue")['default']
export const ContentComingSoonCard: typeof import("../app/components/contents/dashboard/ContentComingSoonCard.vue")['default']
export const ContentDashboardHeader: typeof import("../app/components/contents/dashboard/ContentDashboardHeader.vue")['default']
export const ContentSidebar: typeof import("../app/components/contents/dashboard/ContentSidebar.vue")['default']
export const ContentTopbar: typeof import("../app/components/contents/dashboard/ContentTopbar.vue")['default']
export const ContentCard: typeof import("../app/components/contenus/ContentCard.vue")['default']
export const ContenusCreateButton: typeof import("../app/components/contenus/ContenusCreateButton.vue")['default']
export const ContenusEmptyState: typeof import("../app/components/contenus/ContenusEmptyState.vue")['default']
export const ContenusFilters: typeof import("../app/components/contenus/ContenusFilters.vue")['default']
export const ContenusLegend: typeof import("../app/components/contenus/ContenusLegend.vue")['default']
export const CreateContentMenu: typeof import("../app/components/create/CreateContentMenu.vue")['default']
export const CreateContentModal: typeof import("../app/components/create/CreateContentModal.vue")['default']
export const StepCategories: typeof import("../app/components/create/steps/StepCategories.vue")['default']
export const StepCoverage: typeof import("../app/components/create/steps/StepCoverage.vue")['default']
export const StepPublication: typeof import("../app/components/create/steps/StepPublication.vue")['default']
export const StepSuccess: typeof import("../app/components/create/steps/StepSuccess.vue")['default']
export const StepSurveyType: typeof import("../app/components/create/steps/StepSurveyType.vue")['default']
export const StepTitle: typeof import("../app/components/create/steps/StepTitle.vue")['default']
export const PageHero: typeof import("../app/components/home/PageHero.vue")['default']
export const MedistatsHero: typeof import("../app/components/home/medistats/MedistatsHero.vue")['default']
export const MedistatsHighlights: typeof import("../app/components/home/medistats/MedistatsHighlights.vue")['default']
export const MedistatsHome: typeof import("../app/components/home/medistats/MedistatsHome.vue")['default']
export const HomeArticlesV2: typeof import("../app/components/home/statsio/HomeArticlesV2.vue")['default']
export const HomeCarousel: typeof import("../app/components/home/statsio/HomeCarousel.vue")['default']
export const HomeChannelsStrip: typeof import("../app/components/home/statsio/HomeChannelsStrip.vue")['default']
export const HomeCreateSteps: typeof import("../app/components/home/statsio/HomeCreateSteps.vue")['default']
export const HomeCtaBanner: typeof import("../app/components/home/statsio/HomeCtaBanner.vue")['default']
export const HomeFaq: typeof import("../app/components/home/statsio/HomeFaq.vue")['default']
export const HomeHeroV2: typeof import("../app/components/home/statsio/HomeHeroV2.vue")['default']
export const HomeSondagesV2: typeof import("../app/components/home/statsio/HomeSondagesV2.vue")['default']
export const HomeStatsDataV2: typeof import("../app/components/home/statsio/HomeStatsDataV2.vue")['default']
export const StatsioHome: typeof import("../app/components/home/statsio/StatsioHome.vue")['default']
export const TvstatsHero: typeof import("../app/components/home/tvstats/TvstatsHero.vue")['default']
export const TvstatsHighlights: typeof import("../app/components/home/tvstats/TvstatsHighlights.vue")['default']
export const TvstatsHome: typeof import("../app/components/home/tvstats/TvstatsHome.vue")['default']
export const IconCommunity: typeof import("../app/components/icons/IconCommunity.vue")['default']
export const IconDocumentation: typeof import("../app/components/icons/IconDocumentation.vue")['default']
export const IconEcosystem: typeof import("../app/components/icons/IconEcosystem.vue")['default']
export const IconSupport: typeof import("../app/components/icons/IconSupport.vue")['default']
export const IconTooling: typeof import("../app/components/icons/IconTooling.vue")['default']
export const AppAccessibilityPanel: typeof import("../app/components/layout/AppAccessibilityPanel.vue")['default']
export const AppBootstrapError: typeof import("../app/components/layout/AppBootstrapError.vue")['default']
export const AppCreateFab: typeof import("../app/components/layout/AppCreateFab.vue")['default']
export const AppDropdownMenu: typeof import("../app/components/layout/AppDropdownMenu.vue")['default']
export const AppDropdownMenuItem: typeof import("../app/components/layout/AppDropdownMenuItem.vue")['default']
export const AppFooter: typeof import("../app/components/layout/AppFooter.vue")['default']
export const AppHeader: typeof import("../app/components/layout/AppHeader.vue")['default']
export const AppHeaderMegaMenu: typeof import("../app/components/layout/AppHeaderMegaMenu.vue")['default']
export const AppHeaderSearch: typeof import("../app/components/layout/AppHeaderSearch.vue")['default']
export const AppLoadingBar: typeof import("../app/components/layout/AppLoadingBar.vue")['default']
export const AppNavIcon: typeof import("../app/components/layout/AppNavIcon.vue")['default']
export const AppNotificationStack: typeof import("../app/components/layout/AppNotificationStack.vue")['default']
export const AppPromoBanner: typeof import("../app/components/layout/AppPromoBanner.vue")['default']
export const DashboardShell: typeof import("../app/components/layout/DashboardShell.vue")['default']
export const CatalogChipRow: typeof import("../app/components/listing/CatalogChipRow.vue")['default']
export const CatalogCta: typeof import("../app/components/listing/CatalogCta.vue")['default']
export const CatalogEmpty: typeof import("../app/components/listing/CatalogEmpty.vue")['default']
export const CatalogFavButton: typeof import("../app/components/listing/CatalogFavButton.vue")['default']
export const CatalogHero: typeof import("../app/components/listing/CatalogHero.vue")['default']
export const CatalogLoadMore: typeof import("../app/components/listing/CatalogLoadMore.vue")['default']
export const CatalogPublisherRow: typeof import("../app/components/listing/CatalogPublisherRow.vue")['default']
export const CatalogResultBar: typeof import("../app/components/listing/CatalogResultBar.vue")['default']
export const CatalogSearchField: typeof import("../app/components/listing/CatalogSearchField.vue")['default']
export const CatalogSortPills: typeof import("../app/components/listing/CatalogSortPills.vue")['default']
export const CatalogSubBrandTag: typeof import("../app/components/listing/CatalogSubBrandTag.vue")['default']
export const CatalogToggleChip: typeof import("../app/components/listing/CatalogToggleChip.vue")['default']
export const CatalogToolbar: typeof import("../app/components/listing/CatalogToolbar.vue")['default']
export const CatalogViewToggle: typeof import("../app/components/listing/CatalogViewToggle.vue")['default']
export const MaladiesCard: typeof import("../app/components/maladies/MaladiesCard.vue")['default']
export const MaladiesDetail: typeof import("../app/components/maladies/MaladiesDetail.vue")['default']
export const MaladiesExplorer: typeof import("../app/components/maladies/MaladiesExplorer.vue")['default']
export const MaladiesRankedList: typeof import("../app/components/maladies/MaladiesRankedList.vue")['default']
export const MedicamentsCard: typeof import("../app/components/medicaments/MedicamentsCard.vue")['default']
export const MedicamentsDetail: typeof import("../app/components/medicaments/MedicamentsDetail.vue")['default']
export const MedicamentsExplorer: typeof import("../app/components/medicaments/MedicamentsExplorer.vue")['default']
export const SourceSyncToast: typeof import("../app/components/notifications/SourceSyncToast.vue")['default']
export const CountryCard: typeof import("../app/components/pays/CountryCard.vue")['default']
export const PaysDetail: typeof import("../app/components/pays/PaysDetail.vue")['default']
export const PaysMap: typeof import("../app/components/pays/PaysMap.vue")['default']
export const PollPulseBanner: typeof import("../app/components/polls/PollPulseBanner.vue")['default']
export const SondageDetailView: typeof import("../app/components/polls/SondageDetailView.vue")['default']
export const SondagesListingView: typeof import("../app/components/polls/SondagesListingView.vue")['default']
export const SurveyCatalogCard: typeof import("../app/components/polls/SurveyCatalogCard.vue")['default']
export const SurveyCatalogRow: typeof import("../app/components/polls/SurveyCatalogRow.vue")['default']
export const SurveyFeaturedCard: typeof import("../app/components/polls/SurveyFeaturedCard.vue")['default']
export const SoinsMap: typeof import("../app/components/soins/SoinsMap.vue")['default']
export const StagingGate: typeof import("../app/components/staging/StagingGate.vue")['default']
export const DatasetCard: typeof import("../app/components/statsdata/DatasetCard.vue")['default']
export const StatsDataCatalogCard: typeof import("../app/components/statsdata/StatsDataCatalogCard.vue")['default']
export const StatsDataCatalogRow: typeof import("../app/components/statsdata/StatsDataCatalogRow.vue")['default']
export const StatsDataFeaturedCard: typeof import("../app/components/statsdata/StatsDataFeaturedCard.vue")['default']
export const StatsDataListingView: typeof import("../app/components/statsdata/StatsDataListingView.vue")['default']
export const StatsDataToolbar: typeof import("../app/components/statsdata/StatsDataToolbar.vue")['default']
export const StatsDataActionButton: typeof import("../app/components/statsdata/detail/StatsDataActionButton.vue")['default']
export const StatsDataBreadcrumb: typeof import("../app/components/statsdata/detail/StatsDataBreadcrumb.vue")['default']
export const StatsDataContent: typeof import("../app/components/statsdata/detail/StatsDataContent.vue")['default']
export const StatsDataCover: typeof import("../app/components/statsdata/detail/StatsDataCover.vue")['default']
export const StatsDataDetailView: typeof import("../app/components/statsdata/detail/StatsDataDetailView.vue")['default']
export const StatsDataEmbedModal: typeof import("../app/components/statsdata/detail/StatsDataEmbedModal.vue")['default']
export const StatsDataFreshnessBadge: typeof import("../app/components/statsdata/detail/StatsDataFreshnessBadge.vue")['default']
export const StatsDataHero: typeof import("../app/components/statsdata/detail/StatsDataHero.vue")['default']
export const StatsDataLinkButton: typeof import("../app/components/statsdata/detail/StatsDataLinkButton.vue")['default']
export const StatsDataLinkCard: typeof import("../app/components/statsdata/detail/StatsDataLinkCard.vue")['default']
export const StatsDataPageTabs: typeof import("../app/components/statsdata/detail/StatsDataPageTabs.vue")['default']
export const StatsDataPublisherCard: typeof import("../app/components/statsdata/detail/StatsDataPublisherCard.vue")['default']
export const StatsDataSection: typeof import("../app/components/statsdata/detail/StatsDataSection.vue")['default']
export const StatsDataShareMenu: typeof import("../app/components/statsdata/detail/StatsDataShareMenu.vue")['default']
export const StatsDataSourceCard: typeof import("../app/components/statsdata/detail/StatsDataSourceCard.vue")['default']
export const StatsDataSubHeader: typeof import("../app/components/statsdata/detail/StatsDataSubHeader.vue")['default']
export const StatsDataToc: typeof import("../app/components/statsdata/detail/StatsDataToc.vue")['default']
export const StatsDataToggleButton: typeof import("../app/components/statsdata/detail/StatsDataToggleButton.vue")['default']
export const StatsDataUsefulBar: typeof import("../app/components/statsdata/detail/StatsDataUsefulBar.vue")['default']
export const StatsDataSettingsBreadcrumb: typeof import("../app/components/statsdata/settings/StatsDataSettingsBreadcrumb.vue")['default']
export const StatsDataSettingsCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsCard.vue")['default']
export const StatsDataSettingsCategoriesCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsCategoriesCard.vue")['default']
export const StatsDataSettingsDangerZoneCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsDangerZoneCard.vue")['default']
export const StatsDataSettingsEmojiCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsEmojiCard.vue")['default']
export const StatsDataSettingsGeneralCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsGeneralCard.vue")['default']
export const StatsDataSettingsHeader: typeof import("../app/components/statsdata/settings/StatsDataSettingsHeader.vue")['default']
export const StatsDataSettingsIdentityCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsIdentityCard.vue")['default']
export const StatsDataSettingsResponseDeadlineCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsResponseDeadlineCard.vue")['default']
export const StatsDataSettingsStudioCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsStudioCard.vue")['default']
export const StatsDataSettingsSurveyKindCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsSurveyKindCard.vue")['default']
export const StatsDataSettingsThumbnailCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsThumbnailCard.vue")['default']
export const StatsDataSettingsVisibilityCard: typeof import("../app/components/statsdata/settings/StatsDataSettingsVisibilityCard.vue")['default']
export const StudioHeader: typeof import("../app/components/studio/StudioHeader.vue")['default']
export const StudioSidebarLeft: typeof import("../app/components/studio/StudioSidebarLeft.vue")['default']
export const StudioSidebarRight: typeof import("../app/components/studio/StudioSidebarRight.vue")['default']
export const TextFormatToolbar: typeof import("../app/components/studio/TextFormatToolbar.vue")['default']
export const VariablePickerModal: typeof import("../app/components/studio/VariablePickerModal.vue")['default']
export const MentionPicker: typeof import("../app/components/studio/assistant/MentionPicker.vue")['default']
export const StudioAssistantPanel: typeof import("../app/components/studio/assistant/StudioAssistantPanel.vue")['default']
export const BarChartBlock: typeof import("../app/components/studio/blocks/BarChartBlock.vue")['default']
export const BlockCard: typeof import("../app/components/studio/blocks/BlockCard.vue")['default']
export const BlockRenderer: typeof import("../app/components/studio/blocks/BlockRenderer.vue")['default']
export const ButtonBlock: typeof import("../app/components/studio/blocks/ButtonBlock.vue")['default']
export const CheckboxesBlock: typeof import("../app/components/studio/blocks/CheckboxesBlock.vue")['default']
export const DropdownBlock: typeof import("../app/components/studio/blocks/DropdownBlock.vue")['default']
export const FieldGridBlock: typeof import("../app/components/studio/blocks/FieldGridBlock.vue")['default']
export const IfBlock: typeof import("../app/components/studio/blocks/IfBlock.vue")['default']
export const ImageBlock: typeof import("../app/components/studio/blocks/ImageBlock.vue")['default']
export const KpiBlock: typeof import("../app/components/studio/blocks/KpiBlock.vue")['default']
export const LineChartBlock: typeof import("../app/components/studio/blocks/LineChartBlock.vue")['default']
export const LinearScaleBlock: typeof import("../app/components/studio/blocks/LinearScaleBlock.vue")['default']
export const LinkCardBlock: typeof import("../app/components/studio/blocks/LinkCardBlock.vue")['default']
export const LoopBlock: typeof import("../app/components/studio/blocks/LoopBlock.vue")['default']
export const MapBlock: typeof import("../app/components/studio/blocks/MapBlock.vue")['default']
export const MultipleChoiceBlock: typeof import("../app/components/studio/blocks/MultipleChoiceBlock.vue")['default']
export const ParamBlock: typeof import("../app/components/studio/blocks/ParamBlock.vue")['default']
export const PieChartBlock: typeof import("../app/components/studio/blocks/PieChartBlock.vue")['default']
export const RatingBlock: typeof import("../app/components/studio/blocks/RatingBlock.vue")['default']
export const RecordBlock: typeof import("../app/components/studio/blocks/RecordBlock.vue")['default']
export const RelatedBlock: typeof import("../app/components/studio/blocks/RelatedBlock.vue")['default']
export const RetenirBlock: typeof import("../app/components/studio/blocks/RetenirBlock.vue")['default']
export const SdEmbedBlock: typeof import("../app/components/studio/blocks/SdEmbedBlock.vue")['default']
export const SearchBlock: typeof import("../app/components/studio/blocks/SearchBlock.vue")['default']
export const TableBlock: typeof import("../app/components/studio/blocks/TableBlock.vue")['default']
export const TextBlock: typeof import("../app/components/studio/blocks/TextBlock.vue")['default']
export const VideoBlock: typeof import("../app/components/studio/blocks/VideoBlock.vue")['default']
export const BlockWrapper: typeof import("../app/components/studio/canvas/BlockWrapper.vue")['default']
export const CanvasGrid: typeof import("../app/components/studio/canvas/CanvasGrid.vue")['default']
export const CanvasSection: typeof import("../app/components/studio/canvas/CanvasSection.vue")['default']
export const CanvasZone: typeof import("../app/components/studio/canvas/CanvasZone.vue")['default']
export const SectionContext: typeof import("../app/components/studio/canvas/section-context")['default']
export const FieldChips: typeof import("../app/components/studio/fields/FieldChips.vue")['default']
export const FieldColorSwatches: typeof import("../app/components/studio/fields/FieldColorSwatches.vue")['default']
export const FieldColumns: typeof import("../app/components/studio/fields/FieldColumns.vue")['default']
export const FieldFilters: typeof import("../app/components/studio/fields/FieldFilters.vue")['default']
export const FieldList: typeof import("../app/components/studio/fields/FieldList.vue")['default']
export const FieldNote: typeof import("../app/components/studio/fields/FieldNote.vue")['default']
export const FieldPicker: typeof import("../app/components/studio/fields/FieldPicker.vue")['default']
export const FieldPreview: typeof import("../app/components/studio/fields/FieldPreview.vue")['default']
export const FieldSegmented: typeof import("../app/components/studio/fields/FieldSegmented.vue")['default']
export const FieldText: typeof import("../app/components/studio/fields/FieldText.vue")['default']
export const FieldTextarea: typeof import("../app/components/studio/fields/FieldTextarea.vue")['default']
export const FieldToggle: typeof import("../app/components/studio/fields/FieldToggle.vue")['default']
export const InspectorSection: typeof import("../app/components/studio/fields/InspectorSection.vue")['default']
export const InspectorTabs: typeof import("../app/components/studio/fields/InspectorTabs.vue")['default']
export const StudioField: typeof import("../app/components/studio/fields/StudioField.vue")['default']
export const VariableButton: typeof import("../app/components/studio/fields/VariableButton.vue")['default']
export const Options: typeof import("../app/components/studio/fields/options")['default']
export const DataBlockInspector: typeof import("../app/components/studio/inspector/DataBlockInspector.vue")['default']
export const FormBlockInspector: typeof import("../app/components/studio/inspector/FormBlockInspector.vue")['default']
export const IfBlockInspector: typeof import("../app/components/studio/inspector/IfBlockInspector.vue")['default']
export const LoopBlockInspector: typeof import("../app/components/studio/inspector/LoopBlockInspector.vue")['default']
export const MediaBlockInspector: typeof import("../app/components/studio/inspector/MediaBlockInspector.vue")['default']
export const ParamBlockInspector: typeof import("../app/components/studio/inspector/ParamBlockInspector.vue")['default']
export const RecordBlockInspector: typeof import("../app/components/studio/inspector/RecordBlockInspector.vue")['default']
export const RichBlockInspector: typeof import("../app/components/studio/inspector/RichBlockInspector.vue")['default']
export const SdEmbedBlockInspector: typeof import("../app/components/studio/inspector/SdEmbedBlockInspector.vue")['default']
export const SearchBlockInspector: typeof import("../app/components/studio/inspector/SearchBlockInspector.vue")['default']
export const SectionInspector: typeof import("../app/components/studio/inspector/SectionInspector.vue")['default']
export const AddSourceModal: typeof import("../app/components/studio/sidebar/AddSourceModal.vue")['default']
export const BlockConfigPanel: typeof import("../app/components/studio/sidebar/BlockConfigPanel.vue")['default']
export const DatasetSchemaPreview: typeof import("../app/components/studio/sidebar/DatasetSchemaPreview.vue")['default']
export const DetectedFiltersTable: typeof import("../app/components/studio/sidebar/DetectedFiltersTable.vue")['default']
export const DynamicParamsPanel: typeof import("../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']
export const EditSourceModal: typeof import("../app/components/studio/sidebar/EditSourceModal.vue")['default']
export const SidebarBlocks: typeof import("../app/components/studio/sidebar/SidebarBlocks.vue")['default']
export const SidebarDataSources: typeof import("../app/components/studio/sidebar/SidebarDataSources.vue")['default']
export const SidebarLayouts: typeof import("../app/components/studio/sidebar/SidebarLayouts.vue")['default']
export const SidebarScript: typeof import("../app/components/studio/sidebar/SidebarScript.vue")['default']
export const SourceCompatibilityCard: typeof import("../app/components/studio/sidebar/SourceCompatibilityCard.vue")['default']
export const ViewSourceDataModal: typeof import("../app/components/studio/sidebar/ViewSourceDataModal.vue")['default']
export const ApiDetectionResults: typeof import("../app/components/studio/sidebar/add-source-steps/ApiDetectionResults.vue")['default']
export const StepApiDetect: typeof import("../app/components/studio/sidebar/add-source-steps/StepApiDetect.vue")['default']
export const StepProvenance: typeof import("../app/components/studio/sidebar/add-source-steps/StepProvenance.vue")['default']
export const StepSourceConfigure: typeof import("../app/components/studio/sidebar/add-source-steps/StepSourceConfigure.vue")['default']
export const StepSourceType: typeof import("../app/components/studio/sidebar/add-source-steps/StepSourceType.vue")['default']
export const StepVisibility: typeof import("../app/components/studio/sidebar/add-source-steps/StepVisibility.vue")['default']
export const AggregationSelect: typeof import("../app/components/studio/ui/AggregationSelect.vue")['default']
export const ColumnButton: typeof import("../app/components/studio/ui/ColumnButton.vue")['default']
export const ColumnInput: typeof import("../app/components/studio/ui/ColumnInput.vue")['default']
export const ColumnPickerModal: typeof import("../app/components/studio/ui/ColumnPickerModal.vue")['default']
export const ColumnsMappingModal: typeof import("../app/components/studio/ui/ColumnsMappingModal.vue")['default']
export const DataSourceModal: typeof import("../app/components/studio/ui/DataSourceModal.vue")['default']
export const DataSourcePickerModal: typeof import("../app/components/studio/ui/DataSourcePickerModal.vue")['default']
export const EditorialContentModal: typeof import("../app/components/studio/ui/EditorialContentModal.vue")['default']
export const FiltersModal: typeof import("../app/components/studio/ui/FiltersModal.vue")['default']
export const SearchResultsDisplayModal: typeof import("../app/components/studio/ui/SearchResultsDisplayModal.vue")['default']
export const StudioModal: typeof import("../app/components/studio/ui/StudioModal.vue")['default']
export const StudioSubModal: typeof import("../app/components/studio/ui/StudioSubModal.vue")['default']
export const StudioWizardModal: typeof import("../app/components/studio/ui/StudioWizardModal.vue")['default']
export const URLParamPickerModal: typeof import("../app/components/studio/ui/URLParamPickerModal.vue")['default']
export const TvAudiencesEvolutionChart: typeof import("../app/components/tv/TvAudiencesEvolutionChart.vue")['default']
export const TvAudiencesRankingTable: typeof import("../app/components/tv/TvAudiencesRankingTable.vue")['default']
export const TvAudiencesTop50Table: typeof import("../app/components/tv/TvAudiencesTop50Table.vue")['default']
export const TvBroadcastActionCard: typeof import("../app/components/tv/TvBroadcastActionCard.vue")['default']
export const TvBroadcastAudienceCard: typeof import("../app/components/tv/TvBroadcastAudienceCard.vue")['default']
export const TvBroadcastDiffusions: typeof import("../app/components/tv/TvBroadcastDiffusions.vue")['default']
export const TvBroadcastHero: typeof import("../app/components/tv/TvBroadcastHero.vue")['default']
export const TvBroadcastInfoCard: typeof import("../app/components/tv/TvBroadcastInfoCard.vue")['default']
export const TvBroadcastReviews: typeof import("../app/components/tv/TvBroadcastReviews.vue")['default']
export const TvBroadcastScores: typeof import("../app/components/tv/TvBroadcastScores.vue")['default']
export const TvChannelBanner: typeof import("../app/components/tv/TvChannelBanner.vue")['default']
export const TvChannelLogo: typeof import("../app/components/tv/TvChannelLogo.vue")['default']
export const TvPopularProgrammeCard: typeof import("../app/components/tv/TvPopularProgrammeCard.vue")['default']
export const TvProgrammeCard: typeof import("../app/components/tv/TvProgrammeCard.vue")['default']
export const TvProgrammeCardIcon: typeof import("../app/components/tv/TvProgrammeCardIcon.vue")['default']
export const TvReviewModal: typeof import("../app/components/tv/TvReviewModal.vue")['default']
export const TvScheduleCardView: typeof import("../app/components/tv/TvScheduleCardView.vue")['default']
export const TvScheduleChannelRow: typeof import("../app/components/tv/TvScheduleChannelRow.vue")['default']
export const TvScheduleEmptyState: typeof import("../app/components/tv/TvScheduleEmptyState.vue")['default']
export const TvScheduleFilters: typeof import("../app/components/tv/TvScheduleFilters.vue")['default']
export const TvScheduleGrid: typeof import("../app/components/tv/TvScheduleGrid.vue")['default']
export const TvScheduleNowNext: typeof import("../app/components/tv/TvScheduleNowNext.vue")['default']
export const TvScheduleProgrammeBlock: typeof import("../app/components/tv/TvScheduleProgrammeBlock.vue")['default']
export const TvScheduleTimeline: typeof import("../app/components/tv/TvScheduleTimeline.vue")['default']
export const AppAvatar: typeof import("../app/components/ui/AppAvatar.vue")['default']
export const AppBadge: typeof import("../app/components/ui/AppBadge.vue")['default']
export const AppButton: typeof import("../app/components/ui/AppButton.vue")['default']
export const AppCheckbox: typeof import("../app/components/ui/AppCheckbox.vue")['default']
export const AppColorPickerModal: typeof import("../app/components/ui/AppColorPickerModal.vue")['default']
export const AppLockedPanel: typeof import("../app/components/ui/AppLockedPanel.vue")['default']
export const AppModal: typeof import("../app/components/ui/AppModal.vue")['default']
export const AppPageSection: typeof import("../app/components/ui/AppPageSection.vue")['default']
export const AppPagination: typeof import("../app/components/ui/AppPagination.vue")['default']
export const AppRankingList: typeof import("../app/components/ui/AppRankingList.vue")['default']
export const AppRelatedSlider: typeof import("../app/components/ui/AppRelatedSlider.vue")['default']
export const AppSectionHeader: typeof import("../app/components/ui/AppSectionHeader.vue")['default']
export const AppSectionTabs: typeof import("../app/components/ui/AppSectionTabs.vue")['default']
export const AppSelect: typeof import("../app/components/ui/AppSelect.vue")['default']
export const AppSidebarNavItem: typeof import("../app/components/ui/AppSidebarNavItem.vue")['default']
export const AppSparkline: typeof import("../app/components/ui/AppSparkline.vue")['default']
export const AppStatCard: typeof import("../app/components/ui/AppStatCard.vue")['default']
export const AppStepModal: typeof import("../app/components/ui/AppStepModal.vue")['default']
export const AppTooltip: typeof import("../app/components/ui/AppTooltip.vue")['default']
export const AppTurnstile: typeof import("../app/components/ui/AppTurnstile.vue")['default']
export const AppWordmark: typeof import("../app/components/ui/AppWordmark.vue")['default']
export const AppWorldScatterMap: typeof import("../app/components/ui/AppWorldScatterMap.vue")['default']
export const AccountAvatarUploader: typeof import("../app/components/user/AccountAvatarUploader.vue")['default']
export const AccountContentThumb: typeof import("../app/components/user/AccountContentThumb.vue")['default']
export const AccountDangerZone: typeof import("../app/components/user/AccountDangerZone.vue")['default']
export const AccountDemographicsCard: typeof import("../app/components/user/AccountDemographicsCard.vue")['default']
export const AccountNotificationsCard: typeof import("../app/components/user/AccountNotificationsCard.vue")['default']
export const AccountPageHeader: typeof import("../app/components/user/AccountPageHeader.vue")['default']
export const AccountProfileCard: typeof import("../app/components/user/AccountProfileCard.vue")['default']
export const AccountSearch: typeof import("../app/components/user/AccountSearch.vue")['default']
export const AccountSidebar: typeof import("../app/components/user/AccountSidebar.vue")['default']
export const AccountToggle: typeof import("../app/components/user/AccountToggle.vue")['default']
export const AccountTopbar: typeof import("../app/components/user/AccountTopbar.vue")['default']
export const FavoriteCard: typeof import("../app/components/user/FavoriteCard.vue")['default']
export const SubscriptionRow: typeof import("../app/components/user/SubscriptionRow.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyCookieBanner: LazyComponent<typeof import("../app/components/CookieBanner.vue")['default']>
export const LazyArticleBody: LazyComponent<typeof import("../app/components/articles/ArticleBody.vue")['default']>
export const LazyArticleCatalogCard: LazyComponent<typeof import("../app/components/articles/ArticleCatalogCard.vue")['default']>
export const LazyArticleCatalogRow: LazyComponent<typeof import("../app/components/articles/ArticleCatalogRow.vue")['default']>
export const LazyArticleDetailView: LazyComponent<typeof import("../app/components/articles/ArticleDetailView.vue")['default']>
export const LazyArticleFeaturedCard: LazyComponent<typeof import("../app/components/articles/ArticleFeaturedCard.vue")['default']>
export const LazyArticleHero: LazyComponent<typeof import("../app/components/articles/ArticleHero.vue")['default']>
export const LazyArticleSubHeader: LazyComponent<typeof import("../app/components/articles/ArticleSubHeader.vue")['default']>
export const LazyArticleTeaserCard: LazyComponent<typeof import("../app/components/articles/ArticleTeaserCard.vue")['default']>
export const LazyArticleToc: LazyComponent<typeof import("../app/components/articles/ArticleToc.vue")['default']>
export const LazyArticlesListingView: LazyComponent<typeof import("../app/components/articles/ArticlesListingView.vue")['default']>
export const LazyAuthBrandPanel: LazyComponent<typeof import("../app/components/auth/AuthBrandPanel.vue")['default']>
export const LazyAuthCard: LazyComponent<typeof import("../app/components/auth/AuthCard.vue")['default']>
export const LazyAuthDivider: LazyComponent<typeof import("../app/components/auth/AuthDivider.vue")['default']>
export const LazyAuthErrorAlert: LazyComponent<typeof import("../app/components/auth/AuthErrorAlert.vue")['default']>
export const LazyAuthGoogleButton: LazyComponent<typeof import("../app/components/auth/AuthGoogleButton.vue")['default']>
export const LazyAuthInputField: LazyComponent<typeof import("../app/components/auth/AuthInputField.vue")['default']>
export const LazyAuthShell: LazyComponent<typeof import("../app/components/auth/AuthShell.vue")['default']>
export const LazyAuthStatCard: LazyComponent<typeof import("../app/components/auth/AuthStatCard.vue")['default']>
export const LazyAuthTopBar: LazyComponent<typeof import("../app/components/auth/AuthTopBar.vue")['default']>
export const LazyForgotPasswordFormCard: LazyComponent<typeof import("../app/components/auth/ForgotPasswordFormCard.vue")['default']>
export const LazyLoginFormCard: LazyComponent<typeof import("../app/components/auth/LoginFormCard.vue")['default']>
export const LazyPasswordStrengthMeter: LazyComponent<typeof import("../app/components/auth/PasswordStrengthMeter.vue")['default']>
export const LazyRegisterFormCard: LazyComponent<typeof import("../app/components/auth/RegisterFormCard.vue")['default']>
export const LazyResetPasswordFormCard: LazyComponent<typeof import("../app/components/auth/ResetPasswordFormCard.vue")['default']>
export const LazyVerifyEmailFormCard: LazyComponent<typeof import("../app/components/auth/VerifyEmailFormCard.vue")['default']>
export const LazyChannelConsentModal: LazyComponent<typeof import("../app/components/chaines/ChannelConsentModal.vue")['default']>
export const LazyChannelCreateCard: LazyComponent<typeof import("../app/components/chaines/ChannelCreateCard.vue")['default']>
export const LazyChannelBadgeList: LazyComponent<typeof import("../app/components/channels/ChannelBadgeList.vue")['default']>
export const LazyChannelCard: LazyComponent<typeof import("../app/components/channels/ChannelCard.vue")['default']>
export const LazyChannelCatalogCard: LazyComponent<typeof import("../app/components/channels/ChannelCatalogCard.vue")['default']>
export const LazyChannelCatalogRow: LazyComponent<typeof import("../app/components/channels/ChannelCatalogRow.vue")['default']>
export const LazyChannelContentTypeFilter: LazyComponent<typeof import("../app/components/channels/ChannelContentTypeFilter.vue")['default']>
export const LazyChannelFeaturedCard: LazyComponent<typeof import("../app/components/channels/ChannelFeaturedCard.vue")['default']>
export const LazyChannelInviteMembersModal: LazyComponent<typeof import("../app/components/channels/ChannelInviteMembersModal.vue")['default']>
export const LazyChannelOrganizationBadge: LazyComponent<typeof import("../app/components/channels/ChannelOrganizationBadge.vue")['default']>
export const LazyChannelPopularityCard: LazyComponent<typeof import("../app/components/channels/ChannelPopularityCard.vue")['default']>
export const LazyChannelSwitcher: LazyComponent<typeof import("../app/components/channels/ChannelSwitcher.vue")['default']>
export const LazyChannelVerifiedBadge: LazyComponent<typeof import("../app/components/channels/ChannelVerifiedBadge.vue")['default']>
export const LazyChannelsListingView: LazyComponent<typeof import("../app/components/channels/ChannelsListingView.vue")['default']>
export const LazyChannelDashboardHeader: LazyComponent<typeof import("../app/components/channels/dashboard/ChannelDashboardHeader.vue")['default']>
export const LazyChannelDashboardSearch: LazyComponent<typeof import("../app/components/channels/dashboard/ChannelDashboardSearch.vue")['default']>
export const LazyChannelDataSourceRow: LazyComponent<typeof import("../app/components/channels/dashboard/ChannelDataSourceRow.vue")['default']>
export const LazyChannelSidebar: LazyComponent<typeof import("../app/components/channels/dashboard/ChannelSidebar.vue")['default']>
export const LazyChannelTopbar: LazyComponent<typeof import("../app/components/channels/dashboard/ChannelTopbar.vue")['default']>
export const LazyChannelViewsBreakdownCard: LazyComponent<typeof import("../app/components/channels/dashboard/ChannelViewsBreakdownCard.vue")['default']>
export const LazyChannelAboutTab: LazyComponent<typeof import("../app/components/channels/detail/ChannelAboutTab.vue")['default']>
export const LazyChannelBanner: LazyComponent<typeof import("../app/components/channels/detail/ChannelBanner.vue")['default']>
export const LazyChannelBreadcrumb: LazyComponent<typeof import("../app/components/channels/detail/ChannelBreadcrumb.vue")['default']>
export const LazyChannelDatasetList: LazyComponent<typeof import("../app/components/channels/detail/ChannelDatasetList.vue")['default']>
export const LazyChannelDetailTabs: LazyComponent<typeof import("../app/components/channels/detail/ChannelDetailTabs.vue")['default']>
export const LazyChannelDetailView: LazyComponent<typeof import("../app/components/channels/detail/ChannelDetailView.vue")['default']>
export const LazyChannelFeaturedTab: LazyComponent<typeof import("../app/components/channels/detail/ChannelFeaturedTab.vue")['default']>
export const LazyChannelFeedList: LazyComponent<typeof import("../app/components/channels/detail/ChannelFeedList.vue")['default']>
export const LazyChannelPollGridCard: LazyComponent<typeof import("../app/components/channels/detail/ChannelPollGridCard.vue")['default']>
export const LazyChannelPollsTab: LazyComponent<typeof import("../app/components/channels/detail/ChannelPollsTab.vue")['default']>
export const LazyChannelProfileHeader: LazyComponent<typeof import("../app/components/channels/detail/ChannelProfileHeader.vue")['default']>
export const LazyChannelShareModal: LazyComponent<typeof import("../app/components/channels/detail/ChannelShareModal.vue")['default']>
export const LazyChannelSimilarSlider: LazyComponent<typeof import("../app/components/channels/detail/ChannelSimilarSlider.vue")['default']>
export const LazyChannelStatsStrip: LazyComponent<typeof import("../app/components/channels/detail/ChannelStatsStrip.vue")['default']>
export const LazyChannelOrganizationSettings: LazyComponent<typeof import("../app/components/channels/settings/ChannelOrganizationSettings.vue")['default']>
export const LazyChannelPrivacySettings: LazyComponent<typeof import("../app/components/channels/settings/ChannelPrivacySettings.vue")['default']>
export const LazyChannelProfileSettings: LazyComponent<typeof import("../app/components/channels/settings/ChannelProfileSettings.vue")['default']>
export const LazyStepChannelCategories: LazyComponent<typeof import("../app/components/channels/steps/StepChannelCategories.vue")['default']>
export const LazyStepChannelLegal: LazyComponent<typeof import("../app/components/channels/steps/StepChannelLegal.vue")['default']>
export const LazyComingSoonGate: LazyComponent<typeof import("../app/components/coming-soon/ComingSoonGate.vue")['default']>
export const LazyComingSoonPage: LazyComponent<typeof import("../app/components/coming-soon/ComingSoonPage.vue")['default']>
export const LazyContentComingSoonCard: LazyComponent<typeof import("../app/components/contents/dashboard/ContentComingSoonCard.vue")['default']>
export const LazyContentDashboardHeader: LazyComponent<typeof import("../app/components/contents/dashboard/ContentDashboardHeader.vue")['default']>
export const LazyContentSidebar: LazyComponent<typeof import("../app/components/contents/dashboard/ContentSidebar.vue")['default']>
export const LazyContentTopbar: LazyComponent<typeof import("../app/components/contents/dashboard/ContentTopbar.vue")['default']>
export const LazyContentCard: LazyComponent<typeof import("../app/components/contenus/ContentCard.vue")['default']>
export const LazyContenusCreateButton: LazyComponent<typeof import("../app/components/contenus/ContenusCreateButton.vue")['default']>
export const LazyContenusEmptyState: LazyComponent<typeof import("../app/components/contenus/ContenusEmptyState.vue")['default']>
export const LazyContenusFilters: LazyComponent<typeof import("../app/components/contenus/ContenusFilters.vue")['default']>
export const LazyContenusLegend: LazyComponent<typeof import("../app/components/contenus/ContenusLegend.vue")['default']>
export const LazyCreateContentMenu: LazyComponent<typeof import("../app/components/create/CreateContentMenu.vue")['default']>
export const LazyCreateContentModal: LazyComponent<typeof import("../app/components/create/CreateContentModal.vue")['default']>
export const LazyStepCategories: LazyComponent<typeof import("../app/components/create/steps/StepCategories.vue")['default']>
export const LazyStepCoverage: LazyComponent<typeof import("../app/components/create/steps/StepCoverage.vue")['default']>
export const LazyStepPublication: LazyComponent<typeof import("../app/components/create/steps/StepPublication.vue")['default']>
export const LazyStepSuccess: LazyComponent<typeof import("../app/components/create/steps/StepSuccess.vue")['default']>
export const LazyStepSurveyType: LazyComponent<typeof import("../app/components/create/steps/StepSurveyType.vue")['default']>
export const LazyStepTitle: LazyComponent<typeof import("../app/components/create/steps/StepTitle.vue")['default']>
export const LazyPageHero: LazyComponent<typeof import("../app/components/home/PageHero.vue")['default']>
export const LazyMedistatsHero: LazyComponent<typeof import("../app/components/home/medistats/MedistatsHero.vue")['default']>
export const LazyMedistatsHighlights: LazyComponent<typeof import("../app/components/home/medistats/MedistatsHighlights.vue")['default']>
export const LazyMedistatsHome: LazyComponent<typeof import("../app/components/home/medistats/MedistatsHome.vue")['default']>
export const LazyHomeArticlesV2: LazyComponent<typeof import("../app/components/home/statsio/HomeArticlesV2.vue")['default']>
export const LazyHomeCarousel: LazyComponent<typeof import("../app/components/home/statsio/HomeCarousel.vue")['default']>
export const LazyHomeChannelsStrip: LazyComponent<typeof import("../app/components/home/statsio/HomeChannelsStrip.vue")['default']>
export const LazyHomeCreateSteps: LazyComponent<typeof import("../app/components/home/statsio/HomeCreateSteps.vue")['default']>
export const LazyHomeCtaBanner: LazyComponent<typeof import("../app/components/home/statsio/HomeCtaBanner.vue")['default']>
export const LazyHomeFaq: LazyComponent<typeof import("../app/components/home/statsio/HomeFaq.vue")['default']>
export const LazyHomeHeroV2: LazyComponent<typeof import("../app/components/home/statsio/HomeHeroV2.vue")['default']>
export const LazyHomeSondagesV2: LazyComponent<typeof import("../app/components/home/statsio/HomeSondagesV2.vue")['default']>
export const LazyHomeStatsDataV2: LazyComponent<typeof import("../app/components/home/statsio/HomeStatsDataV2.vue")['default']>
export const LazyStatsioHome: LazyComponent<typeof import("../app/components/home/statsio/StatsioHome.vue")['default']>
export const LazyTvstatsHero: LazyComponent<typeof import("../app/components/home/tvstats/TvstatsHero.vue")['default']>
export const LazyTvstatsHighlights: LazyComponent<typeof import("../app/components/home/tvstats/TvstatsHighlights.vue")['default']>
export const LazyTvstatsHome: LazyComponent<typeof import("../app/components/home/tvstats/TvstatsHome.vue")['default']>
export const LazyIconCommunity: LazyComponent<typeof import("../app/components/icons/IconCommunity.vue")['default']>
export const LazyIconDocumentation: LazyComponent<typeof import("../app/components/icons/IconDocumentation.vue")['default']>
export const LazyIconEcosystem: LazyComponent<typeof import("../app/components/icons/IconEcosystem.vue")['default']>
export const LazyIconSupport: LazyComponent<typeof import("../app/components/icons/IconSupport.vue")['default']>
export const LazyIconTooling: LazyComponent<typeof import("../app/components/icons/IconTooling.vue")['default']>
export const LazyAppAccessibilityPanel: LazyComponent<typeof import("../app/components/layout/AppAccessibilityPanel.vue")['default']>
export const LazyAppBootstrapError: LazyComponent<typeof import("../app/components/layout/AppBootstrapError.vue")['default']>
export const LazyAppCreateFab: LazyComponent<typeof import("../app/components/layout/AppCreateFab.vue")['default']>
export const LazyAppDropdownMenu: LazyComponent<typeof import("../app/components/layout/AppDropdownMenu.vue")['default']>
export const LazyAppDropdownMenuItem: LazyComponent<typeof import("../app/components/layout/AppDropdownMenuItem.vue")['default']>
export const LazyAppFooter: LazyComponent<typeof import("../app/components/layout/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/layout/AppHeader.vue")['default']>
export const LazyAppHeaderMegaMenu: LazyComponent<typeof import("../app/components/layout/AppHeaderMegaMenu.vue")['default']>
export const LazyAppHeaderSearch: LazyComponent<typeof import("../app/components/layout/AppHeaderSearch.vue")['default']>
export const LazyAppLoadingBar: LazyComponent<typeof import("../app/components/layout/AppLoadingBar.vue")['default']>
export const LazyAppNavIcon: LazyComponent<typeof import("../app/components/layout/AppNavIcon.vue")['default']>
export const LazyAppNotificationStack: LazyComponent<typeof import("../app/components/layout/AppNotificationStack.vue")['default']>
export const LazyAppPromoBanner: LazyComponent<typeof import("../app/components/layout/AppPromoBanner.vue")['default']>
export const LazyDashboardShell: LazyComponent<typeof import("../app/components/layout/DashboardShell.vue")['default']>
export const LazyCatalogChipRow: LazyComponent<typeof import("../app/components/listing/CatalogChipRow.vue")['default']>
export const LazyCatalogCta: LazyComponent<typeof import("../app/components/listing/CatalogCta.vue")['default']>
export const LazyCatalogEmpty: LazyComponent<typeof import("../app/components/listing/CatalogEmpty.vue")['default']>
export const LazyCatalogFavButton: LazyComponent<typeof import("../app/components/listing/CatalogFavButton.vue")['default']>
export const LazyCatalogHero: LazyComponent<typeof import("../app/components/listing/CatalogHero.vue")['default']>
export const LazyCatalogLoadMore: LazyComponent<typeof import("../app/components/listing/CatalogLoadMore.vue")['default']>
export const LazyCatalogPublisherRow: LazyComponent<typeof import("../app/components/listing/CatalogPublisherRow.vue")['default']>
export const LazyCatalogResultBar: LazyComponent<typeof import("../app/components/listing/CatalogResultBar.vue")['default']>
export const LazyCatalogSearchField: LazyComponent<typeof import("../app/components/listing/CatalogSearchField.vue")['default']>
export const LazyCatalogSortPills: LazyComponent<typeof import("../app/components/listing/CatalogSortPills.vue")['default']>
export const LazyCatalogSubBrandTag: LazyComponent<typeof import("../app/components/listing/CatalogSubBrandTag.vue")['default']>
export const LazyCatalogToggleChip: LazyComponent<typeof import("../app/components/listing/CatalogToggleChip.vue")['default']>
export const LazyCatalogToolbar: LazyComponent<typeof import("../app/components/listing/CatalogToolbar.vue")['default']>
export const LazyCatalogViewToggle: LazyComponent<typeof import("../app/components/listing/CatalogViewToggle.vue")['default']>
export const LazyMaladiesCard: LazyComponent<typeof import("../app/components/maladies/MaladiesCard.vue")['default']>
export const LazyMaladiesDetail: LazyComponent<typeof import("../app/components/maladies/MaladiesDetail.vue")['default']>
export const LazyMaladiesExplorer: LazyComponent<typeof import("../app/components/maladies/MaladiesExplorer.vue")['default']>
export const LazyMaladiesRankedList: LazyComponent<typeof import("../app/components/maladies/MaladiesRankedList.vue")['default']>
export const LazyMedicamentsCard: LazyComponent<typeof import("../app/components/medicaments/MedicamentsCard.vue")['default']>
export const LazyMedicamentsDetail: LazyComponent<typeof import("../app/components/medicaments/MedicamentsDetail.vue")['default']>
export const LazyMedicamentsExplorer: LazyComponent<typeof import("../app/components/medicaments/MedicamentsExplorer.vue")['default']>
export const LazySourceSyncToast: LazyComponent<typeof import("../app/components/notifications/SourceSyncToast.vue")['default']>
export const LazyCountryCard: LazyComponent<typeof import("../app/components/pays/CountryCard.vue")['default']>
export const LazyPaysDetail: LazyComponent<typeof import("../app/components/pays/PaysDetail.vue")['default']>
export const LazyPaysMap: LazyComponent<typeof import("../app/components/pays/PaysMap.vue")['default']>
export const LazyPollPulseBanner: LazyComponent<typeof import("../app/components/polls/PollPulseBanner.vue")['default']>
export const LazySondageDetailView: LazyComponent<typeof import("../app/components/polls/SondageDetailView.vue")['default']>
export const LazySondagesListingView: LazyComponent<typeof import("../app/components/polls/SondagesListingView.vue")['default']>
export const LazySurveyCatalogCard: LazyComponent<typeof import("../app/components/polls/SurveyCatalogCard.vue")['default']>
export const LazySurveyCatalogRow: LazyComponent<typeof import("../app/components/polls/SurveyCatalogRow.vue")['default']>
export const LazySurveyFeaturedCard: LazyComponent<typeof import("../app/components/polls/SurveyFeaturedCard.vue")['default']>
export const LazySoinsMap: LazyComponent<typeof import("../app/components/soins/SoinsMap.vue")['default']>
export const LazyStagingGate: LazyComponent<typeof import("../app/components/staging/StagingGate.vue")['default']>
export const LazyDatasetCard: LazyComponent<typeof import("../app/components/statsdata/DatasetCard.vue")['default']>
export const LazyStatsDataCatalogCard: LazyComponent<typeof import("../app/components/statsdata/StatsDataCatalogCard.vue")['default']>
export const LazyStatsDataCatalogRow: LazyComponent<typeof import("../app/components/statsdata/StatsDataCatalogRow.vue")['default']>
export const LazyStatsDataFeaturedCard: LazyComponent<typeof import("../app/components/statsdata/StatsDataFeaturedCard.vue")['default']>
export const LazyStatsDataListingView: LazyComponent<typeof import("../app/components/statsdata/StatsDataListingView.vue")['default']>
export const LazyStatsDataToolbar: LazyComponent<typeof import("../app/components/statsdata/StatsDataToolbar.vue")['default']>
export const LazyStatsDataActionButton: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataActionButton.vue")['default']>
export const LazyStatsDataBreadcrumb: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataBreadcrumb.vue")['default']>
export const LazyStatsDataContent: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataContent.vue")['default']>
export const LazyStatsDataCover: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataCover.vue")['default']>
export const LazyStatsDataDetailView: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataDetailView.vue")['default']>
export const LazyStatsDataEmbedModal: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataEmbedModal.vue")['default']>
export const LazyStatsDataFreshnessBadge: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataFreshnessBadge.vue")['default']>
export const LazyStatsDataHero: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataHero.vue")['default']>
export const LazyStatsDataLinkButton: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataLinkButton.vue")['default']>
export const LazyStatsDataLinkCard: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataLinkCard.vue")['default']>
export const LazyStatsDataPageTabs: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataPageTabs.vue")['default']>
export const LazyStatsDataPublisherCard: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataPublisherCard.vue")['default']>
export const LazyStatsDataSection: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataSection.vue")['default']>
export const LazyStatsDataShareMenu: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataShareMenu.vue")['default']>
export const LazyStatsDataSourceCard: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataSourceCard.vue")['default']>
export const LazyStatsDataSubHeader: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataSubHeader.vue")['default']>
export const LazyStatsDataToc: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataToc.vue")['default']>
export const LazyStatsDataToggleButton: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataToggleButton.vue")['default']>
export const LazyStatsDataUsefulBar: LazyComponent<typeof import("../app/components/statsdata/detail/StatsDataUsefulBar.vue")['default']>
export const LazyStatsDataSettingsBreadcrumb: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsBreadcrumb.vue")['default']>
export const LazyStatsDataSettingsCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsCard.vue")['default']>
export const LazyStatsDataSettingsCategoriesCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsCategoriesCard.vue")['default']>
export const LazyStatsDataSettingsDangerZoneCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsDangerZoneCard.vue")['default']>
export const LazyStatsDataSettingsEmojiCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsEmojiCard.vue")['default']>
export const LazyStatsDataSettingsGeneralCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsGeneralCard.vue")['default']>
export const LazyStatsDataSettingsHeader: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsHeader.vue")['default']>
export const LazyStatsDataSettingsIdentityCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsIdentityCard.vue")['default']>
export const LazyStatsDataSettingsResponseDeadlineCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsResponseDeadlineCard.vue")['default']>
export const LazyStatsDataSettingsStudioCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsStudioCard.vue")['default']>
export const LazyStatsDataSettingsSurveyKindCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsSurveyKindCard.vue")['default']>
export const LazyStatsDataSettingsThumbnailCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsThumbnailCard.vue")['default']>
export const LazyStatsDataSettingsVisibilityCard: LazyComponent<typeof import("../app/components/statsdata/settings/StatsDataSettingsVisibilityCard.vue")['default']>
export const LazyStudioHeader: LazyComponent<typeof import("../app/components/studio/StudioHeader.vue")['default']>
export const LazyStudioSidebarLeft: LazyComponent<typeof import("../app/components/studio/StudioSidebarLeft.vue")['default']>
export const LazyStudioSidebarRight: LazyComponent<typeof import("../app/components/studio/StudioSidebarRight.vue")['default']>
export const LazyTextFormatToolbar: LazyComponent<typeof import("../app/components/studio/TextFormatToolbar.vue")['default']>
export const LazyVariablePickerModal: LazyComponent<typeof import("../app/components/studio/VariablePickerModal.vue")['default']>
export const LazyMentionPicker: LazyComponent<typeof import("../app/components/studio/assistant/MentionPicker.vue")['default']>
export const LazyStudioAssistantPanel: LazyComponent<typeof import("../app/components/studio/assistant/StudioAssistantPanel.vue")['default']>
export const LazyBarChartBlock: LazyComponent<typeof import("../app/components/studio/blocks/BarChartBlock.vue")['default']>
export const LazyBlockCard: LazyComponent<typeof import("../app/components/studio/blocks/BlockCard.vue")['default']>
export const LazyBlockRenderer: LazyComponent<typeof import("../app/components/studio/blocks/BlockRenderer.vue")['default']>
export const LazyButtonBlock: LazyComponent<typeof import("../app/components/studio/blocks/ButtonBlock.vue")['default']>
export const LazyCheckboxesBlock: LazyComponent<typeof import("../app/components/studio/blocks/CheckboxesBlock.vue")['default']>
export const LazyDropdownBlock: LazyComponent<typeof import("../app/components/studio/blocks/DropdownBlock.vue")['default']>
export const LazyFieldGridBlock: LazyComponent<typeof import("../app/components/studio/blocks/FieldGridBlock.vue")['default']>
export const LazyIfBlock: LazyComponent<typeof import("../app/components/studio/blocks/IfBlock.vue")['default']>
export const LazyImageBlock: LazyComponent<typeof import("../app/components/studio/blocks/ImageBlock.vue")['default']>
export const LazyKpiBlock: LazyComponent<typeof import("../app/components/studio/blocks/KpiBlock.vue")['default']>
export const LazyLineChartBlock: LazyComponent<typeof import("../app/components/studio/blocks/LineChartBlock.vue")['default']>
export const LazyLinearScaleBlock: LazyComponent<typeof import("../app/components/studio/blocks/LinearScaleBlock.vue")['default']>
export const LazyLinkCardBlock: LazyComponent<typeof import("../app/components/studio/blocks/LinkCardBlock.vue")['default']>
export const LazyLoopBlock: LazyComponent<typeof import("../app/components/studio/blocks/LoopBlock.vue")['default']>
export const LazyMapBlock: LazyComponent<typeof import("../app/components/studio/blocks/MapBlock.vue")['default']>
export const LazyMultipleChoiceBlock: LazyComponent<typeof import("../app/components/studio/blocks/MultipleChoiceBlock.vue")['default']>
export const LazyParamBlock: LazyComponent<typeof import("../app/components/studio/blocks/ParamBlock.vue")['default']>
export const LazyPieChartBlock: LazyComponent<typeof import("../app/components/studio/blocks/PieChartBlock.vue")['default']>
export const LazyRatingBlock: LazyComponent<typeof import("../app/components/studio/blocks/RatingBlock.vue")['default']>
export const LazyRecordBlock: LazyComponent<typeof import("../app/components/studio/blocks/RecordBlock.vue")['default']>
export const LazyRelatedBlock: LazyComponent<typeof import("../app/components/studio/blocks/RelatedBlock.vue")['default']>
export const LazyRetenirBlock: LazyComponent<typeof import("../app/components/studio/blocks/RetenirBlock.vue")['default']>
export const LazySdEmbedBlock: LazyComponent<typeof import("../app/components/studio/blocks/SdEmbedBlock.vue")['default']>
export const LazySearchBlock: LazyComponent<typeof import("../app/components/studio/blocks/SearchBlock.vue")['default']>
export const LazyTableBlock: LazyComponent<typeof import("../app/components/studio/blocks/TableBlock.vue")['default']>
export const LazyTextBlock: LazyComponent<typeof import("../app/components/studio/blocks/TextBlock.vue")['default']>
export const LazyVideoBlock: LazyComponent<typeof import("../app/components/studio/blocks/VideoBlock.vue")['default']>
export const LazyBlockWrapper: LazyComponent<typeof import("../app/components/studio/canvas/BlockWrapper.vue")['default']>
export const LazyCanvasGrid: LazyComponent<typeof import("../app/components/studio/canvas/CanvasGrid.vue")['default']>
export const LazyCanvasSection: LazyComponent<typeof import("../app/components/studio/canvas/CanvasSection.vue")['default']>
export const LazyCanvasZone: LazyComponent<typeof import("../app/components/studio/canvas/CanvasZone.vue")['default']>
export const LazySectionContext: LazyComponent<typeof import("../app/components/studio/canvas/section-context")['default']>
export const LazyFieldChips: LazyComponent<typeof import("../app/components/studio/fields/FieldChips.vue")['default']>
export const LazyFieldColorSwatches: LazyComponent<typeof import("../app/components/studio/fields/FieldColorSwatches.vue")['default']>
export const LazyFieldColumns: LazyComponent<typeof import("../app/components/studio/fields/FieldColumns.vue")['default']>
export const LazyFieldFilters: LazyComponent<typeof import("../app/components/studio/fields/FieldFilters.vue")['default']>
export const LazyFieldList: LazyComponent<typeof import("../app/components/studio/fields/FieldList.vue")['default']>
export const LazyFieldNote: LazyComponent<typeof import("../app/components/studio/fields/FieldNote.vue")['default']>
export const LazyFieldPicker: LazyComponent<typeof import("../app/components/studio/fields/FieldPicker.vue")['default']>
export const LazyFieldPreview: LazyComponent<typeof import("../app/components/studio/fields/FieldPreview.vue")['default']>
export const LazyFieldSegmented: LazyComponent<typeof import("../app/components/studio/fields/FieldSegmented.vue")['default']>
export const LazyFieldText: LazyComponent<typeof import("../app/components/studio/fields/FieldText.vue")['default']>
export const LazyFieldTextarea: LazyComponent<typeof import("../app/components/studio/fields/FieldTextarea.vue")['default']>
export const LazyFieldToggle: LazyComponent<typeof import("../app/components/studio/fields/FieldToggle.vue")['default']>
export const LazyInspectorSection: LazyComponent<typeof import("../app/components/studio/fields/InspectorSection.vue")['default']>
export const LazyInspectorTabs: LazyComponent<typeof import("../app/components/studio/fields/InspectorTabs.vue")['default']>
export const LazyStudioField: LazyComponent<typeof import("../app/components/studio/fields/StudioField.vue")['default']>
export const LazyVariableButton: LazyComponent<typeof import("../app/components/studio/fields/VariableButton.vue")['default']>
export const LazyOptions: LazyComponent<typeof import("../app/components/studio/fields/options")['default']>
export const LazyDataBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/DataBlockInspector.vue")['default']>
export const LazyFormBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/FormBlockInspector.vue")['default']>
export const LazyIfBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/IfBlockInspector.vue")['default']>
export const LazyLoopBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/LoopBlockInspector.vue")['default']>
export const LazyMediaBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/MediaBlockInspector.vue")['default']>
export const LazyParamBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/ParamBlockInspector.vue")['default']>
export const LazyRecordBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/RecordBlockInspector.vue")['default']>
export const LazyRichBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/RichBlockInspector.vue")['default']>
export const LazySdEmbedBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/SdEmbedBlockInspector.vue")['default']>
export const LazySearchBlockInspector: LazyComponent<typeof import("../app/components/studio/inspector/SearchBlockInspector.vue")['default']>
export const LazySectionInspector: LazyComponent<typeof import("../app/components/studio/inspector/SectionInspector.vue")['default']>
export const LazyAddSourceModal: LazyComponent<typeof import("../app/components/studio/sidebar/AddSourceModal.vue")['default']>
export const LazyBlockConfigPanel: LazyComponent<typeof import("../app/components/studio/sidebar/BlockConfigPanel.vue")['default']>
export const LazyDatasetSchemaPreview: LazyComponent<typeof import("../app/components/studio/sidebar/DatasetSchemaPreview.vue")['default']>
export const LazyDetectedFiltersTable: LazyComponent<typeof import("../app/components/studio/sidebar/DetectedFiltersTable.vue")['default']>
export const LazyDynamicParamsPanel: LazyComponent<typeof import("../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']>
export const LazyEditSourceModal: LazyComponent<typeof import("../app/components/studio/sidebar/EditSourceModal.vue")['default']>
export const LazySidebarBlocks: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarBlocks.vue")['default']>
export const LazySidebarDataSources: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarDataSources.vue")['default']>
export const LazySidebarLayouts: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarLayouts.vue")['default']>
export const LazySidebarScript: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarScript.vue")['default']>
export const LazySourceCompatibilityCard: LazyComponent<typeof import("../app/components/studio/sidebar/SourceCompatibilityCard.vue")['default']>
export const LazyViewSourceDataModal: LazyComponent<typeof import("../app/components/studio/sidebar/ViewSourceDataModal.vue")['default']>
export const LazyApiDetectionResults: LazyComponent<typeof import("../app/components/studio/sidebar/add-source-steps/ApiDetectionResults.vue")['default']>
export const LazyStepApiDetect: LazyComponent<typeof import("../app/components/studio/sidebar/add-source-steps/StepApiDetect.vue")['default']>
export const LazyStepProvenance: LazyComponent<typeof import("../app/components/studio/sidebar/add-source-steps/StepProvenance.vue")['default']>
export const LazyStepSourceConfigure: LazyComponent<typeof import("../app/components/studio/sidebar/add-source-steps/StepSourceConfigure.vue")['default']>
export const LazyStepSourceType: LazyComponent<typeof import("../app/components/studio/sidebar/add-source-steps/StepSourceType.vue")['default']>
export const LazyStepVisibility: LazyComponent<typeof import("../app/components/studio/sidebar/add-source-steps/StepVisibility.vue")['default']>
export const LazyAggregationSelect: LazyComponent<typeof import("../app/components/studio/ui/AggregationSelect.vue")['default']>
export const LazyColumnButton: LazyComponent<typeof import("../app/components/studio/ui/ColumnButton.vue")['default']>
export const LazyColumnInput: LazyComponent<typeof import("../app/components/studio/ui/ColumnInput.vue")['default']>
export const LazyColumnPickerModal: LazyComponent<typeof import("../app/components/studio/ui/ColumnPickerModal.vue")['default']>
export const LazyColumnsMappingModal: LazyComponent<typeof import("../app/components/studio/ui/ColumnsMappingModal.vue")['default']>
export const LazyDataSourceModal: LazyComponent<typeof import("../app/components/studio/ui/DataSourceModal.vue")['default']>
export const LazyDataSourcePickerModal: LazyComponent<typeof import("../app/components/studio/ui/DataSourcePickerModal.vue")['default']>
export const LazyEditorialContentModal: LazyComponent<typeof import("../app/components/studio/ui/EditorialContentModal.vue")['default']>
export const LazyFiltersModal: LazyComponent<typeof import("../app/components/studio/ui/FiltersModal.vue")['default']>
export const LazySearchResultsDisplayModal: LazyComponent<typeof import("../app/components/studio/ui/SearchResultsDisplayModal.vue")['default']>
export const LazyStudioModal: LazyComponent<typeof import("../app/components/studio/ui/StudioModal.vue")['default']>
export const LazyStudioSubModal: LazyComponent<typeof import("../app/components/studio/ui/StudioSubModal.vue")['default']>
export const LazyStudioWizardModal: LazyComponent<typeof import("../app/components/studio/ui/StudioWizardModal.vue")['default']>
export const LazyURLParamPickerModal: LazyComponent<typeof import("../app/components/studio/ui/URLParamPickerModal.vue")['default']>
export const LazyTvAudiencesEvolutionChart: LazyComponent<typeof import("../app/components/tv/TvAudiencesEvolutionChart.vue")['default']>
export const LazyTvAudiencesRankingTable: LazyComponent<typeof import("../app/components/tv/TvAudiencesRankingTable.vue")['default']>
export const LazyTvAudiencesTop50Table: LazyComponent<typeof import("../app/components/tv/TvAudiencesTop50Table.vue")['default']>
export const LazyTvBroadcastActionCard: LazyComponent<typeof import("../app/components/tv/TvBroadcastActionCard.vue")['default']>
export const LazyTvBroadcastAudienceCard: LazyComponent<typeof import("../app/components/tv/TvBroadcastAudienceCard.vue")['default']>
export const LazyTvBroadcastDiffusions: LazyComponent<typeof import("../app/components/tv/TvBroadcastDiffusions.vue")['default']>
export const LazyTvBroadcastHero: LazyComponent<typeof import("../app/components/tv/TvBroadcastHero.vue")['default']>
export const LazyTvBroadcastInfoCard: LazyComponent<typeof import("../app/components/tv/TvBroadcastInfoCard.vue")['default']>
export const LazyTvBroadcastReviews: LazyComponent<typeof import("../app/components/tv/TvBroadcastReviews.vue")['default']>
export const LazyTvBroadcastScores: LazyComponent<typeof import("../app/components/tv/TvBroadcastScores.vue")['default']>
export const LazyTvChannelBanner: LazyComponent<typeof import("../app/components/tv/TvChannelBanner.vue")['default']>
export const LazyTvChannelLogo: LazyComponent<typeof import("../app/components/tv/TvChannelLogo.vue")['default']>
export const LazyTvPopularProgrammeCard: LazyComponent<typeof import("../app/components/tv/TvPopularProgrammeCard.vue")['default']>
export const LazyTvProgrammeCard: LazyComponent<typeof import("../app/components/tv/TvProgrammeCard.vue")['default']>
export const LazyTvProgrammeCardIcon: LazyComponent<typeof import("../app/components/tv/TvProgrammeCardIcon.vue")['default']>
export const LazyTvReviewModal: LazyComponent<typeof import("../app/components/tv/TvReviewModal.vue")['default']>
export const LazyTvScheduleCardView: LazyComponent<typeof import("../app/components/tv/TvScheduleCardView.vue")['default']>
export const LazyTvScheduleChannelRow: LazyComponent<typeof import("../app/components/tv/TvScheduleChannelRow.vue")['default']>
export const LazyTvScheduleEmptyState: LazyComponent<typeof import("../app/components/tv/TvScheduleEmptyState.vue")['default']>
export const LazyTvScheduleFilters: LazyComponent<typeof import("../app/components/tv/TvScheduleFilters.vue")['default']>
export const LazyTvScheduleGrid: LazyComponent<typeof import("../app/components/tv/TvScheduleGrid.vue")['default']>
export const LazyTvScheduleNowNext: LazyComponent<typeof import("../app/components/tv/TvScheduleNowNext.vue")['default']>
export const LazyTvScheduleProgrammeBlock: LazyComponent<typeof import("../app/components/tv/TvScheduleProgrammeBlock.vue")['default']>
export const LazyTvScheduleTimeline: LazyComponent<typeof import("../app/components/tv/TvScheduleTimeline.vue")['default']>
export const LazyAppAvatar: LazyComponent<typeof import("../app/components/ui/AppAvatar.vue")['default']>
export const LazyAppBadge: LazyComponent<typeof import("../app/components/ui/AppBadge.vue")['default']>
export const LazyAppButton: LazyComponent<typeof import("../app/components/ui/AppButton.vue")['default']>
export const LazyAppCheckbox: LazyComponent<typeof import("../app/components/ui/AppCheckbox.vue")['default']>
export const LazyAppColorPickerModal: LazyComponent<typeof import("../app/components/ui/AppColorPickerModal.vue")['default']>
export const LazyAppLockedPanel: LazyComponent<typeof import("../app/components/ui/AppLockedPanel.vue")['default']>
export const LazyAppModal: LazyComponent<typeof import("../app/components/ui/AppModal.vue")['default']>
export const LazyAppPageSection: LazyComponent<typeof import("../app/components/ui/AppPageSection.vue")['default']>
export const LazyAppPagination: LazyComponent<typeof import("../app/components/ui/AppPagination.vue")['default']>
export const LazyAppRankingList: LazyComponent<typeof import("../app/components/ui/AppRankingList.vue")['default']>
export const LazyAppRelatedSlider: LazyComponent<typeof import("../app/components/ui/AppRelatedSlider.vue")['default']>
export const LazyAppSectionHeader: LazyComponent<typeof import("../app/components/ui/AppSectionHeader.vue")['default']>
export const LazyAppSectionTabs: LazyComponent<typeof import("../app/components/ui/AppSectionTabs.vue")['default']>
export const LazyAppSelect: LazyComponent<typeof import("../app/components/ui/AppSelect.vue")['default']>
export const LazyAppSidebarNavItem: LazyComponent<typeof import("../app/components/ui/AppSidebarNavItem.vue")['default']>
export const LazyAppSparkline: LazyComponent<typeof import("../app/components/ui/AppSparkline.vue")['default']>
export const LazyAppStatCard: LazyComponent<typeof import("../app/components/ui/AppStatCard.vue")['default']>
export const LazyAppStepModal: LazyComponent<typeof import("../app/components/ui/AppStepModal.vue")['default']>
export const LazyAppTooltip: LazyComponent<typeof import("../app/components/ui/AppTooltip.vue")['default']>
export const LazyAppTurnstile: LazyComponent<typeof import("../app/components/ui/AppTurnstile.vue")['default']>
export const LazyAppWordmark: LazyComponent<typeof import("../app/components/ui/AppWordmark.vue")['default']>
export const LazyAppWorldScatterMap: LazyComponent<typeof import("../app/components/ui/AppWorldScatterMap.vue")['default']>
export const LazyAccountAvatarUploader: LazyComponent<typeof import("../app/components/user/AccountAvatarUploader.vue")['default']>
export const LazyAccountContentThumb: LazyComponent<typeof import("../app/components/user/AccountContentThumb.vue")['default']>
export const LazyAccountDangerZone: LazyComponent<typeof import("../app/components/user/AccountDangerZone.vue")['default']>
export const LazyAccountDemographicsCard: LazyComponent<typeof import("../app/components/user/AccountDemographicsCard.vue")['default']>
export const LazyAccountNotificationsCard: LazyComponent<typeof import("../app/components/user/AccountNotificationsCard.vue")['default']>
export const LazyAccountPageHeader: LazyComponent<typeof import("../app/components/user/AccountPageHeader.vue")['default']>
export const LazyAccountProfileCard: LazyComponent<typeof import("../app/components/user/AccountProfileCard.vue")['default']>
export const LazyAccountSearch: LazyComponent<typeof import("../app/components/user/AccountSearch.vue")['default']>
export const LazyAccountSidebar: LazyComponent<typeof import("../app/components/user/AccountSidebar.vue")['default']>
export const LazyAccountToggle: LazyComponent<typeof import("../app/components/user/AccountToggle.vue")['default']>
export const LazyAccountTopbar: LazyComponent<typeof import("../app/components/user/AccountTopbar.vue")['default']>
export const LazyFavoriteCard: LazyComponent<typeof import("../app/components/user/FavoriteCard.vue")['default']>
export const LazySubscriptionRow: LazyComponent<typeof import("../app/components/user/SubscriptionRow.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
