export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptLinkedInInsight, useScriptCalendly, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { $fetch } from '#build/fetch.mjs';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useLayout } from '#app/composables/layout';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { STUDIO_EMBED_CONTEXT, StudioEmbedContext } from '../app/composables/studioEmbedContext';
export { useAccountFavorites } from '../app/composables/useAccountFavorites';
export { useAccountHistory } from '../app/composables/useAccountHistory';
export { useAccountOverview } from '../app/composables/useAccountOverview';
export { useAccountSearch } from '../app/composables/useAccountSearch';
export { useAccountSubscriptions } from '../app/composables/useAccountSubscriptions';
export { useActiveEditor } from '../app/composables/useActiveEditor';
export { DATAGOUV_TABULAR_API_BASE, parseDatagouvResourceId, datagouvTabularUrl, defaultPagination, ADD_SOURCE_WIZARD_STEPS, apiFormAuthHeaders, useApiStructureDetection, useAddSourceWizard, SourceType, AuthType, HttpMethod, ApiFormPagination, ProvenanceSelection, ApiFormShape } from '../app/composables/useAddSourceWizard';
export { useAppNotifications } from '../app/composables/useAppNotifications';
export { useBlockData, resolveAggregationParams, BlockDataOverrides } from '../app/composables/useBlockData';
export { fmtScheduleDate, fmtRelative, useBroadcastDetail } from '../app/composables/useBroadcastDetail';
export { CONTENT_TYPE_FILTER_OPTIONS, useChannelContents, ContentTypeFilter } from '../app/composables/useChannelContents';
export { useChannelDashboard } from '../app/composables/useChannelDashboard';
export { useChannelDataSources } from '../app/composables/useChannelDataSources';
export { useChannelDetail, ChannelTab } from '../app/composables/useChannelDetail';
export { useChannelProfile, ChannelProfileTab } from '../app/composables/useChannelProfile';
export { useChannelPublicContent } from '../app/composables/useChannelPublicContent';
export { useChannelStats } from '../app/composables/useChannelStats';
export { useChannelsCatalog } from '../app/composables/useChannelsCatalog';
export { PALETTE, useChart } from '../app/composables/useChart';
export { useClickOutside } from '../app/composables/useClickOutside';
export { useContentBasePath } from '../app/composables/useContentBasePath';
export { useContentDashboard } from '../app/composables/useContentDashboard';
export { useContentDataSources } from '../app/composables/useContentDataSources';
export { useCookieBanner } from '../app/composables/useCookieBanner';
export { wizardStepsFor, CONTENT_WIZARD_STEPS, useCreateContentWizard } from '../app/composables/useCreateContentWizard';
export { EDIT_SOURCE_WIZARD_STEPS, useEditSourceWizard } from '../app/composables/useEditSourceWizard';
export { useFavicon } from '../app/composables/useFavicon';
export { useFormBlockResponse } from '../app/composables/useFormBlockResponse';
export { loadArticleMenu, loadStatsDataMenu, loadSurveyMenu, loadChannelsMenu, loadAudiencesMenu, loadProgrammeTvMenu, loadMaladiesMenu, loadMedicamentsMenu, loadSoinsMenu, loadPromoTicker, HeaderMenuData } from '../app/composables/useHeaderMegaMenuData';
export { useHomeCatalogSection } from '../app/composables/useHomeCatalogSection';
export { useMaladies } from '../app/composables/useMaladies';
export { useMedicamentImage } from '../app/composables/useMedicamentImage';
export { POPULAR_MEDICAMENTS, useMedicaments } from '../app/composables/useMedicaments';
export { useModalA11y } from '../app/composables/useModalA11y';
export { useMyChannels } from '../app/composables/useMyChannels';
export { OWNER_FILTER_OPTIONS, useMyStudioContents, OwnerFilter, DisplayContent } from '../app/composables/useMyStudioContents';
export { useNowNext, NowNext } from '../app/composables/useNowNext';
export { usePageSeo, PageSeoOgType, PageSeoOptions } from '../app/composables/usePageSeo';
export { usePays } from '../app/composables/usePays';
export { usePublicCatalog } from '../app/composables/usePublicCatalog';
export { clearAggregateCache, useResolvedTokens, useAggregateValues, useExpressionNumber, useResolvedTokenList } from '../app/composables/useResolvedTokens';
export { useRespondentToken } from '../app/composables/useRespondentToken';
export { useScrollAnim } from '../app/composables/useScrollAnim';
export { useSimilarChannels } from '../app/composables/useSimilarChannels';
export { useSoins } from '../app/composables/useSoins';
export { useStatsDataChrome } from '../app/composables/useStatsDataChrome';
export { useStatsDataDetail } from '../app/composables/useStatsDataDetail';
export { useStudioAutosave } from '../app/composables/useStudioAutosave';
export { useStudioVariables, VariableItem, VariableGroup } from '../app/composables/useStudioVariables';
export { CHANNEL_CHART_COLORS, useTvAudiences, YearDataWithChannel } from '../app/composables/useTvAudiences';
export { useTvSchedule } from '../app/composables/useTvSchedule';
export { isoToFlagEmoji } from '../app/utils/flag';
export { getMedicamentFormEmoji, extractMedicamentBrandName } from '../app/utils/medicaments';
export { formatCompactNumber } from '../app/utils/number';
export { formatStatsDataDate, formatDisplayValue, parseNumericValue, formatRowCount, relativeUpdate } from '../app/utils/statsDataFormat';
export { getStatsDataVisual, getStatsDataPalette, seededSparklinePoints, StatsDataVisual } from '../app/utils/statsDataVisuals';
export { useAppNotificationsStore } from '../app/stores/app-notifications';
export { useAuthStore } from '../app/stores/auth';
export { useContextStore, ContextState } from '../app/stores/context';
export { usePrefsStore } from '../app/stores/prefs';
export { useStudioAgentStore, AgentStatus, AgentChatMessage } from '../app/stores/studio-agent';
export { useStudioDatasetsStore } from '../app/stores/studio-datasets';
export { useStudioStore } from '../app/stores/studio';
export { listAgentConversations, createAgentConversation, deleteAgentConversation, fetchAgentConversation, sendAgentMessage, fetchAgentRun, AgentRunStatus, AgentPatchOp, AgentRun, AgentMessage, AgentConversation, AgentConversationSummary } from '../app/api/ai';
export { checkHandleAvailability } from '../app/api/channels-validation';
export { CHANNEL_BADGE_LABELS, createChannel, getChannelCategories, getMyChannels, getChannels, getPublicChannels, getChannel, fetchChannelCatalog, getChannelStats, getChannelDataSources, toggleChannelSubscription, updateChannel, INVITABLE_ROLES, channelRoleLabels, updateChannelProfile, updateChannelMedia, getChannelMembers, getChannelPermissionsCatalog, inviteChannelMembers, getChannelInvitations, revokeChannelInvitation, getInvitationByToken, acceptChannelInvitation, getChannelSubscribers, deleteChannel, getJoinableOrganizations, createOrganization, joinOrganization, leaveOrganization, channelCategoryLabels, ChannelKind, ChannelCategory, CreateChannelPayload, ChannelProfile, ChannelOrganization, Channel, ChannelCategoryItem, ChannelSort, ChannelsListParams, PaginatedChannels, ChannelStats, ChannelDataSourceUsage, ChannelDataSource, ToggleSubscriptionResponse, ChannelRole, ChannelPermission, ChannelPermissionCategory, ChannelMember, ChannelInvitation, ChannelSubscriber, UpdateChannelPayload, InviteChannelMembersPayload, InviteChannelMembersResult, InvitationDetails } from '../app/api/channels';
export { submitContactMessage, ContactReason, ContactMessagePayload } from '../app/api/contact';
export { fetchContentCategories } from '../app/api/content-categories';
export { mapQueryMappingToApi, mapPaginationToApi, detectApiStructure, fetchDataSource, previewSpreadsheet, createApiDataSource, refreshDataSource, updateDataSource, RefreshFrequency, PaginationStyle, Materialization, QueryMappingFilter, QueryMapping, SemanticRole, DetectedSchemaColumn, ChartType, SourceCapabilities, DataSourcePagination, DataSourceApiConfig, DataSourceDetail, DetectStructureResult, SpreadsheetPreview, UpdateDataSourcePayload } from '../app/api/data-sources';
export { startIdentityVerification, fetchIdentityStatus, IdentityStatus, IdentityStartResult } from '../app/api/identity';
export { fetchMaladiesSearch, fetchMaladiesPopulaires, fetchMaladieDetail } from '../app/api/maladies';
export { fetchMedicamentsSearch, fetchMedicamentGeneriques, fetchMedicamentDetail, fetchMedicamentVentes, fetchMedicamentsTopVentes, fetchMedicamentImage } from '../app/api/medicaments';
export { fetchPaysList, fetchPaysDetail } from '../app/api/pays';
export { fetchSoinsList } from '../app/api/soins';
export { fetchSourceProvenances, SourceProvenance } from '../app/api/source-provenances';
export { uploadAvatar, deleteAvatar, fetchFavorites, toggleFavorite, removeFavorite, fetchHistory, fetchInProgress, recordContentView, clearHistory, fetchSubscriptions, searchAccount } from '../app/api/statsio-account';
export { STATSIO_API } from '../app/api/statsio-endpoints';
export { fetchStatsioAuthMe, fetchStatsioMe, updateProfile, fetchProfileReferenceData, anonymizeAccount, ProfileReferenceData, UpdateProfilePayload } from '../app/api/statsio-user';
export { fetchBlockResponse, submitBlockResponse, FormAnswerValue, BlockResponseOption, DemographicBucket, ResponseDemographics, BlockResponseAggregate, BlockResponseState } from '../app/api/studio-responses';
export { fetchDatasets, fetchDatasetSchema, fetchDatasetPreview, updateDataset, deleteDataset, fetchBlockData, fetchPublicBlockData, fetchSearchRows, fetchPublicSearchRows, fetchDistinctValues, fetchPublicDistinctValues, fetchScalarAggregate, fetchPublicScalarAggregate, fetchUserStudioContents, createStudioContent, fetchPublicStatsDataCatalog, fetchPublicSurveys, fetchPublicArticles, fetchPublicCatalog, fetchStatsDataDocument, fetchPublicStatsDataDocument, fetchContentMentions, fetchStatsDataEmbeddableBlocks, fetchPublicStatsDataBlock, saveStatsDataDocument, deleteStatsDataDocument, publishStatsDataDocument, setStatsDataDocumentStatus, fetchContentDataSources, DatasetPreview, ScalarAggregateParams, ContentChannel, ContentDataset, StatsDataDocument, CreateStudioContentPayload, ContentMention, EmbeddedBlockDoc, EmbeddableBlockSummary, ResolvedEmbeddedBlock, SaveStatsDataDocumentPayload } from '../app/api/studio';
export { fetchTvAudiences } from '../app/api/tv-audiences';
export { fetchBroadcast, toggleBroadcastView, fetchProgrammeSchedule, fetchBroadcastReviews, fetchReviewQuestions, submitBroadcastReview, BroadcastCategory, BroadcastDetail, BroadcastScoreSummary, ToggleViewResponse, ProgrammeBroadcast, ProgrammeSchedule, BroadcastReview, ReviewsResponse, ReviewQuestion, ReviewSubmitPayload } from '../app/api/tv-broadcast';
export { fetchChannelDetail, fetchChannelPopularProgrammes, toggleChannelFollow, ChannelDetail, PopularProgramme, ToggleFollowResponse } from '../app/api/tv-channel';
export { fetchChannelSchedules, invalidateDbChannelCache } from '../app/api/tv-schedule';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../node_modules/@pinia/nuxt/dist/runtime/composables';
export { useNuxtDevTools } from '../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';