name = "statsio-front"
main = ".output/server/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".output/public"

[observability.logs]
enabled = true
invocation_logs = true

[env.staging]
name = "statsio-front-staging"

[env.staging.site]
bucket = ".output/public"

[env.staging.observability.logs]
enabled = true
invocation_logs = true
