
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  CookieBanner: typeof import("../../app/components/CookieBanner.vue")['default']
  AdminSidebar: typeof import("../../app/components/admin/AdminSidebar.vue")['default']
  AuthGoogleButton: typeof import("../../app/components/auth/AuthGoogleButton.vue")['default']
  ChannelDashboardSidebar: typeof import("../../app/components/channels/ChannelDashboardSidebar.vue")['default']
  CreateChannelModal: typeof import("../../app/components/channels/CreateChannelModal.vue")['default']
  StepChannelCategories: typeof import("../../app/components/channels/steps/StepChannelCategories.vue")['default']
  StepChannelEditorial: typeof import("../../app/components/channels/steps/StepChannelEditorial.vue")['default']
  StepChannelIdentity: typeof import("../../app/components/channels/steps/StepChannelIdentity.vue")['default']
  StepChannelLegal: typeof import("../../app/components/channels/steps/StepChannelLegal.vue")['default']
  StepChannelSuccess: typeof import("../../app/components/channels/steps/StepChannelSuccess.vue")['default']
  StepChannelVisuals: typeof import("../../app/components/channels/steps/StepChannelVisuals.vue")['default']
  ComingSoonGate: typeof import("../../app/components/coming-soon/ComingSoonGate.vue")['default']
  ComingSoonPage: typeof import("../../app/components/coming-soon/ComingSoonPage.vue")['default']
  CreateContentModal: typeof import("../../app/components/create/CreateContentModal.vue")['default']
  StepCategories: typeof import("../../app/components/create/steps/StepCategories.vue")['default']
  StepCoverage: typeof import("../../app/components/create/steps/StepCoverage.vue")['default']
  StepPublication: typeof import("../../app/components/create/steps/StepPublication.vue")['default']
  StepSuccess: typeof import("../../app/components/create/steps/StepSuccess.vue")['default']
  StepTitle: typeof import("../../app/components/create/steps/StepTitle.vue")['default']
  UserDashboardCreatorSection: typeof import("../../app/components/dashboard/UserDashboardCreatorSection.vue")['default']
  UserDashboardHistorySection: typeof import("../../app/components/dashboard/UserDashboardHistorySection.vue")['default']
  UserDashboardLayout: typeof import("../../app/components/dashboard/UserDashboardLayout.vue")['default']
  UserDashboardSidebarCompletion: typeof import("../../app/components/dashboard/UserDashboardSidebarCompletion.vue")['default']
  UserDashboardSidebarNav: typeof import("../../app/components/dashboard/UserDashboardSidebarNav.vue")['default']
  UserDashboardSidebarProfileCard: typeof import("../../app/components/dashboard/UserDashboardSidebarProfileCard.vue")['default']
  UserDashboardSubscriptionsSection: typeof import("../../app/components/dashboard/UserDashboardSubscriptionsSection.vue")['default']
  UserDashboardUsageCard: typeof import("../../app/components/dashboard/UserDashboardUsageCard.vue")['default']
  HomeArticles: typeof import("../../app/components/home/HomeArticles.vue")['default']
  HomeCTA: typeof import("../../app/components/home/HomeCTA.vue")['default']
  HomeHero: typeof import("../../app/components/home/HomeHero.vue")['default']
  HomeHighlights: typeof import("../../app/components/home/HomeHighlights.vue")['default']
  HomePageFrame: typeof import("../../app/components/home/HomePageFrame.vue")['default']
  HomePolls: typeof import("../../app/components/home/HomePolls.vue")['default']
  HomeSectionHeader: typeof import("../../app/components/home/HomeSectionHeader.vue")['default']
  HomeStatsData: typeof import("../../app/components/home/HomeStatsData.vue")['default']
  HomeStatsStrip: typeof import("../../app/components/home/HomeStatsStrip.vue")['default']
  IconCommunity: typeof import("../../app/components/icons/IconCommunity.vue")['default']
  IconDocumentation: typeof import("../../app/components/icons/IconDocumentation.vue")['default']
  IconEcosystem: typeof import("../../app/components/icons/IconEcosystem.vue")['default']
  IconSupport: typeof import("../../app/components/icons/IconSupport.vue")['default']
  IconTooling: typeof import("../../app/components/icons/IconTooling.vue")['default']
  AppAccessibilityPanel: typeof import("../../app/components/layout/AppAccessibilityPanel.vue")['default']
  AppBootstrapError: typeof import("../../app/components/layout/AppBootstrapError.vue")['default']
  AppCreateFab: typeof import("../../app/components/layout/AppCreateFab.vue")['default']
  AppDropdownMenu: typeof import("../../app/components/layout/AppDropdownMenu.vue")['default']
  AppDropdownMenuItem: typeof import("../../app/components/layout/AppDropdownMenuItem.vue")['default']
  AppFooter: typeof import("../../app/components/layout/AppFooter.vue")['default']
  AppHeader: typeof import("../../app/components/layout/AppHeader.vue")['default']
  AppLoadingBar: typeof import("../../app/components/layout/AppLoadingBar.vue")['default']
  AppNavIcon: typeof import("../../app/components/layout/AppNavIcon.vue")['default']
  AppNotificationStack: typeof import("../../app/components/layout/AppNotificationStack.vue")['default']
  AppPromoBanner: typeof import("../../app/components/layout/AppPromoBanner.vue")['default']
  AuthInputField: typeof import("../../app/components/login/AuthInputField.vue")['default']
  AuthLayout: typeof import("../../app/components/login/AuthLayout.vue")['default']
  ForgotPasswordFormCard: typeof import("../../app/components/login/ForgotPasswordFormCard.vue")['default']
  LoginFormCard: typeof import("../../app/components/login/LoginFormCard.vue")['default']
  LoginHeader: typeof import("../../app/components/login/LoginHeader.vue")['default']
  LoginIntroPanel: typeof import("../../app/components/login/LoginIntroPanel.vue")['default']
  RegisterFormCard: typeof import("../../app/components/login/RegisterFormCard.vue")['default']
  VerifyEmailCard: typeof import("../../app/components/login/VerifyEmailCard.vue")['default']
  PollCard: typeof import("../../app/components/polls/PollCard.vue")['default']
  StagingGate: typeof import("../../app/components/staging/StagingGate.vue")['default']
  StudioHeader: typeof import("../../app/components/studio/StudioHeader.vue")['default']
  StudioSidebarLeft: typeof import("../../app/components/studio/StudioSidebarLeft.vue")['default']
  StudioSidebarRight: typeof import("../../app/components/studio/StudioSidebarRight.vue")['default']
  TextFormatToolbar: typeof import("../../app/components/studio/TextFormatToolbar.vue")['default']
  BarChartBlock: typeof import("../../app/components/studio/blocks/BarChartBlock.vue")['default']
  BlockRenderer: typeof import("../../app/components/studio/blocks/BlockRenderer.vue")['default']
  ButtonBlock: typeof import("../../app/components/studio/blocks/ButtonBlock.vue")['default']
  CheckboxesBlock: typeof import("../../app/components/studio/blocks/CheckboxesBlock.vue")['default']
  DropdownBlock: typeof import("../../app/components/studio/blocks/DropdownBlock.vue")['default']
  ImageBlock: typeof import("../../app/components/studio/blocks/ImageBlock.vue")['default']
  KpiBlock: typeof import("../../app/components/studio/blocks/KpiBlock.vue")['default']
  LineChartBlock: typeof import("../../app/components/studio/blocks/LineChartBlock.vue")['default']
  LinearScaleBlock: typeof import("../../app/components/studio/blocks/LinearScaleBlock.vue")['default']
  LinkCardBlock: typeof import("../../app/components/studio/blocks/LinkCardBlock.vue")['default']
  MultipleChoiceBlock: typeof import("../../app/components/studio/blocks/MultipleChoiceBlock.vue")['default']
  PieChartBlock: typeof import("../../app/components/studio/blocks/PieChartBlock.vue")['default']
  RatingBlock: typeof import("../../app/components/studio/blocks/RatingBlock.vue")['default']
  RetenirBlock: typeof import("../../app/components/studio/blocks/RetenirBlock.vue")['default']
  SearchBlock: typeof import("../../app/components/studio/blocks/SearchBlock.vue")['default']
  TableBlock: typeof import("../../app/components/studio/blocks/TableBlock.vue")['default']
  TextBlock: typeof import("../../app/components/studio/blocks/TextBlock.vue")['default']
  VideoBlock: typeof import("../../app/components/studio/blocks/VideoBlock.vue")['default']
  BlockWrapper: typeof import("../../app/components/studio/canvas/BlockWrapper.vue")['default']
  CanvasGrid: typeof import("../../app/components/studio/canvas/CanvasGrid.vue")['default']
  CanvasPageTabs: typeof import("../../app/components/studio/canvas/CanvasPageTabs.vue")['default']
  CanvasSection: typeof import("../../app/components/studio/canvas/CanvasSection.vue")['default']
  CanvasZone: typeof import("../../app/components/studio/canvas/CanvasZone.vue")['default']
  AddSourceModal: typeof import("../../app/components/studio/sidebar/AddSourceModal.vue")['default']
  BlockConfigPanel: typeof import("../../app/components/studio/sidebar/BlockConfigPanel.vue")['default']
  DynamicParamsPanel: typeof import("../../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']
  EditSourceModal: typeof import("../../app/components/studio/sidebar/EditSourceModal.vue")['default']
  SidebarBlocks: typeof import("../../app/components/studio/sidebar/SidebarBlocks.vue")['default']
  SidebarDataSources: typeof import("../../app/components/studio/sidebar/SidebarDataSources.vue")['default']
  SidebarLayouts: typeof import("../../app/components/studio/sidebar/SidebarLayouts.vue")['default']
  SidebarVariables: typeof import("../../app/components/studio/sidebar/SidebarVariables.vue")['default']
  ViewSourceDataModal: typeof import("../../app/components/studio/sidebar/ViewSourceDataModal.vue")['default']
  StepProvenance: typeof import("../../app/components/studio/sidebar/add-source-steps/StepProvenance.vue")['default']
  StepSourceConfigure: typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceConfigure.vue")['default']
  StepSourceType: typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceType.vue")['default']
  StepVisibility: typeof import("../../app/components/studio/sidebar/add-source-steps/StepVisibility.vue")['default']
  AggregationSelect: typeof import("../../app/components/studio/ui/AggregationSelect.vue")['default']
  ColumnButton: typeof import("../../app/components/studio/ui/ColumnButton.vue")['default']
  ColumnInput: typeof import("../../app/components/studio/ui/ColumnInput.vue")['default']
  ColumnPickerModal: typeof import("../../app/components/studio/ui/ColumnPickerModal.vue")['default']
  ColumnsMappingModal: typeof import("../../app/components/studio/ui/ColumnsMappingModal.vue")['default']
  DataSourceModal: typeof import("../../app/components/studio/ui/DataSourceModal.vue")['default']
  EditorialContentModal: typeof import("../../app/components/studio/ui/EditorialContentModal.vue")['default']
  FiltersModal: typeof import("../../app/components/studio/ui/FiltersModal.vue")['default']
  SearchResultsDisplayModal: typeof import("../../app/components/studio/ui/SearchResultsDisplayModal.vue")['default']
  URLParamPickerModal: typeof import("../../app/components/studio/ui/URLParamPickerModal.vue")['default']
  TvAudiencesEvolutionChart: typeof import("../../app/components/tv/TvAudiencesEvolutionChart.vue")['default']
  TvAudiencesRankingTable: typeof import("../../app/components/tv/TvAudiencesRankingTable.vue")['default']
  TvAudiencesTop50Table: typeof import("../../app/components/tv/TvAudiencesTop50Table.vue")['default']
  TvChannelLogo: typeof import("../../app/components/tv/TvChannelLogo.vue")['default']
  TvProgrammeCardIcon: typeof import("../../app/components/tv/TvProgrammeCardIcon.vue")['default']
  TvReviewModal: typeof import("../../app/components/tv/TvReviewModal.vue")['default']
  TvScheduleChannelRow: typeof import("../../app/components/tv/TvScheduleChannelRow.vue")['default']
  TvScheduleGrid: typeof import("../../app/components/tv/TvScheduleGrid.vue")['default']
  TvScheduleNowNext: typeof import("../../app/components/tv/TvScheduleNowNext.vue")['default']
  TvScheduleProgrammeBlock: typeof import("../../app/components/tv/TvScheduleProgrammeBlock.vue")['default']
  TvScheduleTimeline: typeof import("../../app/components/tv/TvScheduleTimeline.vue")['default']
  AppAvatar: typeof import("../../app/components/ui/AppAvatar.vue")['default']
  AppButton: typeof import("../../app/components/ui/AppButton.vue")['default']
  AppCheckbox: typeof import("../../app/components/ui/AppCheckbox.vue")['default']
  AppColorPickerModal: typeof import("../../app/components/ui/AppColorPickerModal.vue")['default']
  AppModal: typeof import("../../app/components/ui/AppModal.vue")['default']
  AppSelect: typeof import("../../app/components/ui/AppSelect.vue")['default']
  AppStepModal: typeof import("../../app/components/ui/AppStepModal.vue")['default']
  AppWordmark: typeof import("../../app/components/ui/AppWordmark.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyCookieBanner: LazyComponent<typeof import("../../app/components/CookieBanner.vue")['default']>
  LazyAdminSidebar: LazyComponent<typeof import("../../app/components/admin/AdminSidebar.vue")['default']>
  LazyAuthGoogleButton: LazyComponent<typeof import("../../app/components/auth/AuthGoogleButton.vue")['default']>
  LazyChannelDashboardSidebar: LazyComponent<typeof import("../../app/components/channels/ChannelDashboardSidebar.vue")['default']>
  LazyCreateChannelModal: LazyComponent<typeof import("../../app/components/channels/CreateChannelModal.vue")['default']>
  LazyStepChannelCategories: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelCategories.vue")['default']>
  LazyStepChannelEditorial: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelEditorial.vue")['default']>
  LazyStepChannelIdentity: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelIdentity.vue")['default']>
  LazyStepChannelLegal: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelLegal.vue")['default']>
  LazyStepChannelSuccess: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelSuccess.vue")['default']>
  LazyStepChannelVisuals: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelVisuals.vue")['default']>
  LazyComingSoonGate: LazyComponent<typeof import("../../app/components/coming-soon/ComingSoonGate.vue")['default']>
  LazyComingSoonPage: LazyComponent<typeof import("../../app/components/coming-soon/ComingSoonPage.vue")['default']>
  LazyCreateContentModal: LazyComponent<typeof import("../../app/components/create/CreateContentModal.vue")['default']>
  LazyStepCategories: LazyComponent<typeof import("../../app/components/create/steps/StepCategories.vue")['default']>
  LazyStepCoverage: LazyComponent<typeof import("../../app/components/create/steps/StepCoverage.vue")['default']>
  LazyStepPublication: LazyComponent<typeof import("../../app/components/create/steps/StepPublication.vue")['default']>
  LazyStepSuccess: LazyComponent<typeof import("../../app/components/create/steps/StepSuccess.vue")['default']>
  LazyStepTitle: LazyComponent<typeof import("../../app/components/create/steps/StepTitle.vue")['default']>
  LazyUserDashboardCreatorSection: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardCreatorSection.vue")['default']>
  LazyUserDashboardHistorySection: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardHistorySection.vue")['default']>
  LazyUserDashboardLayout: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardLayout.vue")['default']>
  LazyUserDashboardSidebarCompletion: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSidebarCompletion.vue")['default']>
  LazyUserDashboardSidebarNav: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSidebarNav.vue")['default']>
  LazyUserDashboardSidebarProfileCard: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSidebarProfileCard.vue")['default']>
  LazyUserDashboardSubscriptionsSection: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardSubscriptionsSection.vue")['default']>
  LazyUserDashboardUsageCard: LazyComponent<typeof import("../../app/components/dashboard/UserDashboardUsageCard.vue")['default']>
  LazyHomeArticles: LazyComponent<typeof import("../../app/components/home/HomeArticles.vue")['default']>
  LazyHomeCTA: LazyComponent<typeof import("../../app/components/home/HomeCTA.vue")['default']>
  LazyHomeHero: LazyComponent<typeof import("../../app/components/home/HomeHero.vue")['default']>
  LazyHomeHighlights: LazyComponent<typeof import("../../app/components/home/HomeHighlights.vue")['default']>
  LazyHomePageFrame: LazyComponent<typeof import("../../app/components/home/HomePageFrame.vue")['default']>
  LazyHomePolls: LazyComponent<typeof import("../../app/components/home/HomePolls.vue")['default']>
  LazyHomeSectionHeader: LazyComponent<typeof import("../../app/components/home/HomeSectionHeader.vue")['default']>
  LazyHomeStatsData: LazyComponent<typeof import("../../app/components/home/HomeStatsData.vue")['default']>
  LazyHomeStatsStrip: LazyComponent<typeof import("../../app/components/home/HomeStatsStrip.vue")['default']>
  LazyIconCommunity: LazyComponent<typeof import("../../app/components/icons/IconCommunity.vue")['default']>
  LazyIconDocumentation: LazyComponent<typeof import("../../app/components/icons/IconDocumentation.vue")['default']>
  LazyIconEcosystem: LazyComponent<typeof import("../../app/components/icons/IconEcosystem.vue")['default']>
  LazyIconSupport: LazyComponent<typeof import("../../app/components/icons/IconSupport.vue")['default']>
  LazyIconTooling: LazyComponent<typeof import("../../app/components/icons/IconTooling.vue")['default']>
  LazyAppAccessibilityPanel: LazyComponent<typeof import("../../app/components/layout/AppAccessibilityPanel.vue")['default']>
  LazyAppBootstrapError: LazyComponent<typeof import("../../app/components/layout/AppBootstrapError.vue")['default']>
  LazyAppCreateFab: LazyComponent<typeof import("../../app/components/layout/AppCreateFab.vue")['default']>
  LazyAppDropdownMenu: LazyComponent<typeof import("../../app/components/layout/AppDropdownMenu.vue")['default']>
  LazyAppDropdownMenuItem: LazyComponent<typeof import("../../app/components/layout/AppDropdownMenuItem.vue")['default']>
  LazyAppFooter: LazyComponent<typeof import("../../app/components/layout/AppFooter.vue")['default']>
  LazyAppHeader: LazyComponent<typeof import("../../app/components/layout/AppHeader.vue")['default']>
  LazyAppLoadingBar: LazyComponent<typeof import("../../app/components/layout/AppLoadingBar.vue")['default']>
  LazyAppNavIcon: LazyComponent<typeof import("../../app/components/layout/AppNavIcon.vue")['default']>
  LazyAppNotificationStack: LazyComponent<typeof import("../../app/components/layout/AppNotificationStack.vue")['default']>
  LazyAppPromoBanner: LazyComponent<typeof import("../../app/components/layout/AppPromoBanner.vue")['default']>
  LazyAuthInputField: LazyComponent<typeof import("../../app/components/login/AuthInputField.vue")['default']>
  LazyAuthLayout: LazyComponent<typeof import("../../app/components/login/AuthLayout.vue")['default']>
  LazyForgotPasswordFormCard: LazyComponent<typeof import("../../app/components/login/ForgotPasswordFormCard.vue")['default']>
  LazyLoginFormCard: LazyComponent<typeof import("../../app/components/login/LoginFormCard.vue")['default']>
  LazyLoginHeader: LazyComponent<typeof import("../../app/components/login/LoginHeader.vue")['default']>
  LazyLoginIntroPanel: LazyComponent<typeof import("../../app/components/login/LoginIntroPanel.vue")['default']>
  LazyRegisterFormCard: LazyComponent<typeof import("../../app/components/login/RegisterFormCard.vue")['default']>
  LazyVerifyEmailCard: LazyComponent<typeof import("../../app/components/login/VerifyEmailCard.vue")['default']>
  LazyPollCard: LazyComponent<typeof import("../../app/components/polls/PollCard.vue")['default']>
  LazyStagingGate: LazyComponent<typeof import("../../app/components/staging/StagingGate.vue")['default']>
  LazyStudioHeader: LazyComponent<typeof import("../../app/components/studio/StudioHeader.vue")['default']>
  LazyStudioSidebarLeft: LazyComponent<typeof import("../../app/components/studio/StudioSidebarLeft.vue")['default']>
  LazyStudioSidebarRight: LazyComponent<typeof import("../../app/components/studio/StudioSidebarRight.vue")['default']>
  LazyTextFormatToolbar: LazyComponent<typeof import("../../app/components/studio/TextFormatToolbar.vue")['default']>
  LazyBarChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/BarChartBlock.vue")['default']>
  LazyBlockRenderer: LazyComponent<typeof import("../../app/components/studio/blocks/BlockRenderer.vue")['default']>
  LazyButtonBlock: LazyComponent<typeof import("../../app/components/studio/blocks/ButtonBlock.vue")['default']>
  LazyCheckboxesBlock: LazyComponent<typeof import("../../app/components/studio/blocks/CheckboxesBlock.vue")['default']>
  LazyDropdownBlock: LazyComponent<typeof import("../../app/components/studio/blocks/DropdownBlock.vue")['default']>
  LazyImageBlock: LazyComponent<typeof import("../../app/components/studio/blocks/ImageBlock.vue")['default']>
  LazyKpiBlock: LazyComponent<typeof import("../../app/components/studio/blocks/KpiBlock.vue")['default']>
  LazyLineChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LineChartBlock.vue")['default']>
  LazyLinearScaleBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LinearScaleBlock.vue")['default']>
  LazyLinkCardBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LinkCardBlock.vue")['default']>
  LazyMultipleChoiceBlock: LazyComponent<typeof import("../../app/components/studio/blocks/MultipleChoiceBlock.vue")['default']>
  LazyPieChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/PieChartBlock.vue")['default']>
  LazyRatingBlock: LazyComponent<typeof import("../../app/components/studio/blocks/RatingBlock.vue")['default']>
  LazyRetenirBlock: LazyComponent<typeof import("../../app/components/studio/blocks/RetenirBlock.vue")['default']>
  LazySearchBlock: LazyComponent<typeof import("../../app/components/studio/blocks/SearchBlock.vue")['default']>
  LazyTableBlock: LazyComponent<typeof import("../../app/components/studio/blocks/TableBlock.vue")['default']>
  LazyTextBlock: LazyComponent<typeof import("../../app/components/studio/blocks/TextBlock.vue")['default']>
  LazyVideoBlock: LazyComponent<typeof import("../../app/components/studio/blocks/VideoBlock.vue")['default']>
  LazyBlockWrapper: LazyComponent<typeof import("../../app/components/studio/canvas/BlockWrapper.vue")['default']>
  LazyCanvasGrid: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasGrid.vue")['default']>
  LazyCanvasPageTabs: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasPageTabs.vue")['default']>
  LazyCanvasSection: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasSection.vue")['default']>
  LazyCanvasZone: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasZone.vue")['default']>
  LazyAddSourceModal: LazyComponent<typeof import("../../app/components/studio/sidebar/AddSourceModal.vue")['default']>
  LazyBlockConfigPanel: LazyComponent<typeof import("../../app/components/studio/sidebar/BlockConfigPanel.vue")['default']>
  LazyDynamicParamsPanel: LazyComponent<typeof import("../../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']>
  LazyEditSourceModal: LazyComponent<typeof import("../../app/components/studio/sidebar/EditSourceModal.vue")['default']>
  LazySidebarBlocks: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarBlocks.vue")['default']>
  LazySidebarDataSources: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarDataSources.vue")['default']>
  LazySidebarLayouts: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarLayouts.vue")['default']>
  LazySidebarVariables: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarVariables.vue")['default']>
  LazyViewSourceDataModal: LazyComponent<typeof import("../../app/components/studio/sidebar/ViewSourceDataModal.vue")['default']>
  LazyStepProvenance: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepProvenance.vue")['default']>
  LazyStepSourceConfigure: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceConfigure.vue")['default']>
  LazyStepSourceType: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceType.vue")['default']>
  LazyStepVisibility: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepVisibility.vue")['default']>
  LazyAggregationSelect: LazyComponent<typeof import("../../app/components/studio/ui/AggregationSelect.vue")['default']>
  LazyColumnButton: LazyComponent<typeof import("../../app/components/studio/ui/ColumnButton.vue")['default']>
  LazyColumnInput: LazyComponent<typeof import("../../app/components/studio/ui/ColumnInput.vue")['default']>
  LazyColumnPickerModal: LazyComponent<typeof import("../../app/components/studio/ui/ColumnPickerModal.vue")['default']>
  LazyColumnsMappingModal: LazyComponent<typeof import("../../app/components/studio/ui/ColumnsMappingModal.vue")['default']>
  LazyDataSourceModal: LazyComponent<typeof import("../../app/components/studio/ui/DataSourceModal.vue")['default']>
  LazyEditorialContentModal: LazyComponent<typeof import("../../app/components/studio/ui/EditorialContentModal.vue")['default']>
  LazyFiltersModal: LazyComponent<typeof import("../../app/components/studio/ui/FiltersModal.vue")['default']>
  LazySearchResultsDisplayModal: LazyComponent<typeof import("../../app/components/studio/ui/SearchResultsDisplayModal.vue")['default']>
  LazyURLParamPickerModal: LazyComponent<typeof import("../../app/components/studio/ui/URLParamPickerModal.vue")['default']>
  LazyTvAudiencesEvolutionChart: LazyComponent<typeof import("../../app/components/tv/TvAudiencesEvolutionChart.vue")['default']>
  LazyTvAudiencesRankingTable: LazyComponent<typeof import("../../app/components/tv/TvAudiencesRankingTable.vue")['default']>
  LazyTvAudiencesTop50Table: LazyComponent<typeof import("../../app/components/tv/TvAudiencesTop50Table.vue")['default']>
  LazyTvChannelLogo: LazyComponent<typeof import("../../app/components/tv/TvChannelLogo.vue")['default']>
  LazyTvProgrammeCardIcon: LazyComponent<typeof import("../../app/components/tv/TvProgrammeCardIcon.vue")['default']>
  LazyTvReviewModal: LazyComponent<typeof import("../../app/components/tv/TvReviewModal.vue")['default']>
  LazyTvScheduleChannelRow: LazyComponent<typeof import("../../app/components/tv/TvScheduleChannelRow.vue")['default']>
  LazyTvScheduleGrid: LazyComponent<typeof import("../../app/components/tv/TvScheduleGrid.vue")['default']>
  LazyTvScheduleNowNext: LazyComponent<typeof import("../../app/components/tv/TvScheduleNowNext.vue")['default']>
  LazyTvScheduleProgrammeBlock: LazyComponent<typeof import("../../app/components/tv/TvScheduleProgrammeBlock.vue")['default']>
  LazyTvScheduleTimeline: LazyComponent<typeof import("../../app/components/tv/TvScheduleTimeline.vue")['default']>
  LazyAppAvatar: LazyComponent<typeof import("../../app/components/ui/AppAvatar.vue")['default']>
  LazyAppButton: LazyComponent<typeof import("../../app/components/ui/AppButton.vue")['default']>
  LazyAppCheckbox: LazyComponent<typeof import("../../app/components/ui/AppCheckbox.vue")['default']>
  LazyAppColorPickerModal: LazyComponent<typeof import("../../app/components/ui/AppColorPickerModal.vue")['default']>
  LazyAppModal: LazyComponent<typeof import("../../app/components/ui/AppModal.vue")['default']>
  LazyAppSelect: LazyComponent<typeof import("../../app/components/ui/AppSelect.vue")['default']>
  LazyAppStepModal: LazyComponent<typeof import("../../app/components/ui/AppStepModal.vue")['default']>
  LazyAppWordmark: LazyComponent<typeof import("../../app/components/ui/AppWordmark.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
