
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  CookieBanner: typeof import("../../app/components/CookieBanner.vue")['default']
  ArticleBody: typeof import("../../app/components/articles/ArticleBody.vue")['default']
  ArticleCatalogCard: typeof import("../../app/components/articles/ArticleCatalogCard.vue")['default']
  ArticleCatalogRow: typeof import("../../app/components/articles/ArticleCatalogRow.vue")['default']
  ArticleDetailView: typeof import("../../app/components/articles/ArticleDetailView.vue")['default']
  ArticleFeaturedCard: typeof import("../../app/components/articles/ArticleFeaturedCard.vue")['default']
  ArticleHero: typeof import("../../app/components/articles/ArticleHero.vue")['default']
  ArticleSubHeader: typeof import("../../app/components/articles/ArticleSubHeader.vue")['default']
  ArticleTeaserCard: typeof import("../../app/components/articles/ArticleTeaserCard.vue")['default']
  ArticleToc: typeof import("../../app/components/articles/ArticleToc.vue")['default']
  ArticlesListingView: typeof import("../../app/components/articles/ArticlesListingView.vue")['default']
  AuthBrandPanel: typeof import("../../app/components/auth/AuthBrandPanel.vue")['default']
  AuthCard: typeof import("../../app/components/auth/AuthCard.vue")['default']
  AuthDivider: typeof import("../../app/components/auth/AuthDivider.vue")['default']
  AuthErrorAlert: typeof import("../../app/components/auth/AuthErrorAlert.vue")['default']
  AuthGoogleButton: typeof import("../../app/components/auth/AuthGoogleButton.vue")['default']
  AuthInputField: typeof import("../../app/components/auth/AuthInputField.vue")['default']
  AuthShell: typeof import("../../app/components/auth/AuthShell.vue")['default']
  AuthStatCard: typeof import("../../app/components/auth/AuthStatCard.vue")['default']
  AuthTopBar: typeof import("../../app/components/auth/AuthTopBar.vue")['default']
  ForgotPasswordFormCard: typeof import("../../app/components/auth/ForgotPasswordFormCard.vue")['default']
  LoginFormCard: typeof import("../../app/components/auth/LoginFormCard.vue")['default']
  PasswordStrengthMeter: typeof import("../../app/components/auth/PasswordStrengthMeter.vue")['default']
  RegisterFormCard: typeof import("../../app/components/auth/RegisterFormCard.vue")['default']
  ResetPasswordFormCard: typeof import("../../app/components/auth/ResetPasswordFormCard.vue")['default']
  VerifyEmailFormCard: typeof import("../../app/components/auth/VerifyEmailFormCard.vue")['default']
  ChannelConsentModal: typeof import("../../app/components/chaines/ChannelConsentModal.vue")['default']
  ChannelCreateCard: typeof import("../../app/components/chaines/ChannelCreateCard.vue")['default']
  ChannelBadgeList: typeof import("../../app/components/channels/ChannelBadgeList.vue")['default']
  ChannelCard: typeof import("../../app/components/channels/ChannelCard.vue")['default']
  ChannelCatalogCard: typeof import("../../app/components/channels/ChannelCatalogCard.vue")['default']
  ChannelCatalogRow: typeof import("../../app/components/channels/ChannelCatalogRow.vue")['default']
  ChannelContentTypeFilter: typeof import("../../app/components/channels/ChannelContentTypeFilter.vue")['default']
  ChannelFeaturedCard: typeof import("../../app/components/channels/ChannelFeaturedCard.vue")['default']
  ChannelInviteMembersModal: typeof import("../../app/components/channels/ChannelInviteMembersModal.vue")['default']
  ChannelOrganizationBadge: typeof import("../../app/components/channels/ChannelOrganizationBadge.vue")['default']
  ChannelPopularityCard: typeof import("../../app/components/channels/ChannelPopularityCard.vue")['default']
  ChannelSwitcher: typeof import("../../app/components/channels/ChannelSwitcher.vue")['default']
  ChannelVerifiedBadge: typeof import("../../app/components/channels/ChannelVerifiedBadge.vue")['default']
  ChannelsListingView: typeof import("../../app/components/channels/ChannelsListingView.vue")['default']
  ChannelDashboardHeader: typeof import("../../app/components/channels/dashboard/ChannelDashboardHeader.vue")['default']
  ChannelDashboardSearch: typeof import("../../app/components/channels/dashboard/ChannelDashboardSearch.vue")['default']
  ChannelDataSourceRow: typeof import("../../app/components/channels/dashboard/ChannelDataSourceRow.vue")['default']
  ChannelSidebar: typeof import("../../app/components/channels/dashboard/ChannelSidebar.vue")['default']
  ChannelTopbar: typeof import("../../app/components/channels/dashboard/ChannelTopbar.vue")['default']
  ChannelViewsBreakdownCard: typeof import("../../app/components/channels/dashboard/ChannelViewsBreakdownCard.vue")['default']
  ChannelAboutTab: typeof import("../../app/components/channels/detail/ChannelAboutTab.vue")['default']
  ChannelBanner: typeof import("../../app/components/channels/detail/ChannelBanner.vue")['default']
  ChannelBreadcrumb: typeof import("../../app/components/channels/detail/ChannelBreadcrumb.vue")['default']
  ChannelDatasetList: typeof import("../../app/components/channels/detail/ChannelDatasetList.vue")['default']
  ChannelDetailTabs: typeof import("../../app/components/channels/detail/ChannelDetailTabs.vue")['default']
  ChannelDetailView: typeof import("../../app/components/channels/detail/ChannelDetailView.vue")['default']
  ChannelFeaturedTab: typeof import("../../app/components/channels/detail/ChannelFeaturedTab.vue")['default']
  ChannelFeedList: typeof import("../../app/components/channels/detail/ChannelFeedList.vue")['default']
  ChannelPollGridCard: typeof import("../../app/components/channels/detail/ChannelPollGridCard.vue")['default']
  ChannelPollsTab: typeof import("../../app/components/channels/detail/ChannelPollsTab.vue")['default']
  ChannelProfileHeader: typeof import("../../app/components/channels/detail/ChannelProfileHeader.vue")['default']
  ChannelShareModal: typeof import("../../app/components/channels/detail/ChannelShareModal.vue")['default']
  ChannelSimilarSlider: typeof import("../../app/components/channels/detail/ChannelSimilarSlider.vue")['default']
  ChannelStatsStrip: typeof import("../../app/components/channels/detail/ChannelStatsStrip.vue")['default']
  ChannelOrganizationSettings: typeof import("../../app/components/channels/settings/ChannelOrganizationSettings.vue")['default']
  ChannelPrivacySettings: typeof import("../../app/components/channels/settings/ChannelPrivacySettings.vue")['default']
  ChannelProfileSettings: typeof import("../../app/components/channels/settings/ChannelProfileSettings.vue")['default']
  StepChannelCategories: typeof import("../../app/components/channels/steps/StepChannelCategories.vue")['default']
  StepChannelLegal: typeof import("../../app/components/channels/steps/StepChannelLegal.vue")['default']
  ComingSoonGate: typeof import("../../app/components/coming-soon/ComingSoonGate.vue")['default']
  ComingSoonPage: typeof import("../../app/components/coming-soon/ComingSoonPage.vue")['default']
  ContentComingSoonCard: typeof import("../../app/components/contents/dashboard/ContentComingSoonCard.vue")['default']
  ContentDashboardHeader: typeof import("../../app/components/contents/dashboard/ContentDashboardHeader.vue")['default']
  ContentSidebar: typeof import("../../app/components/contents/dashboard/ContentSidebar.vue")['default']
  ContentTopbar: typeof import("../../app/components/contents/dashboard/ContentTopbar.vue")['default']
  ContentCard: typeof import("../../app/components/contenus/ContentCard.vue")['default']
  ContenusCreateButton: typeof import("../../app/components/contenus/ContenusCreateButton.vue")['default']
  ContenusEmptyState: typeof import("../../app/components/contenus/ContenusEmptyState.vue")['default']
  ContenusFilters: typeof import("../../app/components/contenus/ContenusFilters.vue")['default']
  ContenusLegend: typeof import("../../app/components/contenus/ContenusLegend.vue")['default']
  CreateContentMenu: typeof import("../../app/components/create/CreateContentMenu.vue")['default']
  CreateContentModal: typeof import("../../app/components/create/CreateContentModal.vue")['default']
  StepCategories: typeof import("../../app/components/create/steps/StepCategories.vue")['default']
  StepCoverage: typeof import("../../app/components/create/steps/StepCoverage.vue")['default']
  StepPublication: typeof import("../../app/components/create/steps/StepPublication.vue")['default']
  StepSuccess: typeof import("../../app/components/create/steps/StepSuccess.vue")['default']
  StepSurveyType: typeof import("../../app/components/create/steps/StepSurveyType.vue")['default']
  StepTitle: typeof import("../../app/components/create/steps/StepTitle.vue")['default']
  PageHero: typeof import("../../app/components/home/PageHero.vue")['default']
  MedistatsHero: typeof import("../../app/components/home/medistats/MedistatsHero.vue")['default']
  MedistatsHighlights: typeof import("../../app/components/home/medistats/MedistatsHighlights.vue")['default']
  MedistatsHome: typeof import("../../app/components/home/medistats/MedistatsHome.vue")['default']
  HomeArticlesV2: typeof import("../../app/components/home/statsio/HomeArticlesV2.vue")['default']
  HomeCarousel: typeof import("../../app/components/home/statsio/HomeCarousel.vue")['default']
  HomeChannelsStrip: typeof import("../../app/components/home/statsio/HomeChannelsStrip.vue")['default']
  HomeCreateSteps: typeof import("../../app/components/home/statsio/HomeCreateSteps.vue")['default']
  HomeCtaBanner: typeof import("../../app/components/home/statsio/HomeCtaBanner.vue")['default']
  HomeFaq: typeof import("../../app/components/home/statsio/HomeFaq.vue")['default']
  HomeHeroV2: typeof import("../../app/components/home/statsio/HomeHeroV2.vue")['default']
  HomeSondagesV2: typeof import("../../app/components/home/statsio/HomeSondagesV2.vue")['default']
  HomeStatsDataV2: typeof import("../../app/components/home/statsio/HomeStatsDataV2.vue")['default']
  StatsioHome: typeof import("../../app/components/home/statsio/StatsioHome.vue")['default']
  TvstatsHero: typeof import("../../app/components/home/tvstats/TvstatsHero.vue")['default']
  TvstatsHighlights: typeof import("../../app/components/home/tvstats/TvstatsHighlights.vue")['default']
  TvstatsHome: typeof import("../../app/components/home/tvstats/TvstatsHome.vue")['default']
  IconCommunity: typeof import("../../app/components/icons/IconCommunity.vue")['default']
  IconDocumentation: typeof import("../../app/components/icons/IconDocumentation.vue")['default']
  IconEcosystem: typeof import("../../app/components/icons/IconEcosystem.vue")['default']
  IconSupport: typeof import("../../app/components/icons/IconSupport.vue")['default']
  IconTooling: typeof import("../../app/components/icons/IconTooling.vue")['default']
  AppAccessibilityPanel: typeof import("../../app/components/layout/AppAccessibilityPanel.vue")['default']
  AppBootstrapError: typeof import("../../app/components/layout/AppBootstrapError.vue")['default']
  AppCreateFab: typeof import("../../app/components/layout/AppCreateFab.vue")['default']
  AppDropdownMenu: typeof import("../../app/components/layout/AppDropdownMenu.vue")['default']
  AppDropdownMenuItem: typeof import("../../app/components/layout/AppDropdownMenuItem.vue")['default']
  AppFooter: typeof import("../../app/components/layout/AppFooter.vue")['default']
  AppHeader: typeof import("../../app/components/layout/AppHeader.vue")['default']
  AppHeaderMegaMenu: typeof import("../../app/components/layout/AppHeaderMegaMenu.vue")['default']
  AppHeaderSearch: typeof import("../../app/components/layout/AppHeaderSearch.vue")['default']
  AppLoadingBar: typeof import("../../app/components/layout/AppLoadingBar.vue")['default']
  AppNavIcon: typeof import("../../app/components/layout/AppNavIcon.vue")['default']
  AppNotificationStack: typeof import("../../app/components/layout/AppNotificationStack.vue")['default']
  AppPromoBanner: typeof import("../../app/components/layout/AppPromoBanner.vue")['default']
  DashboardShell: typeof import("../../app/components/layout/DashboardShell.vue")['default']
  CatalogChipRow: typeof import("../../app/components/listing/CatalogChipRow.vue")['default']
  CatalogCta: typeof import("../../app/components/listing/CatalogCta.vue")['default']
  CatalogEmpty: typeof import("../../app/components/listing/CatalogEmpty.vue")['default']
  CatalogFavButton: typeof import("../../app/components/listing/CatalogFavButton.vue")['default']
  CatalogHero: typeof import("../../app/components/listing/CatalogHero.vue")['default']
  CatalogLoadMore: typeof import("../../app/components/listing/CatalogLoadMore.vue")['default']
  CatalogPublisherRow: typeof import("../../app/components/listing/CatalogPublisherRow.vue")['default']
  CatalogResultBar: typeof import("../../app/components/listing/CatalogResultBar.vue")['default']
  CatalogSearchField: typeof import("../../app/components/listing/CatalogSearchField.vue")['default']
  CatalogSortPills: typeof import("../../app/components/listing/CatalogSortPills.vue")['default']
  CatalogSubBrandTag: typeof import("../../app/components/listing/CatalogSubBrandTag.vue")['default']
  CatalogToggleChip: typeof import("../../app/components/listing/CatalogToggleChip.vue")['default']
  CatalogToolbar: typeof import("../../app/components/listing/CatalogToolbar.vue")['default']
  CatalogViewToggle: typeof import("../../app/components/listing/CatalogViewToggle.vue")['default']
  MaladiesCard: typeof import("../../app/components/maladies/MaladiesCard.vue")['default']
  MaladiesDetail: typeof import("../../app/components/maladies/MaladiesDetail.vue")['default']
  MaladiesExplorer: typeof import("../../app/components/maladies/MaladiesExplorer.vue")['default']
  MaladiesRankedList: typeof import("../../app/components/maladies/MaladiesRankedList.vue")['default']
  MedicamentsCard: typeof import("../../app/components/medicaments/MedicamentsCard.vue")['default']
  MedicamentsDetail: typeof import("../../app/components/medicaments/MedicamentsDetail.vue")['default']
  MedicamentsExplorer: typeof import("../../app/components/medicaments/MedicamentsExplorer.vue")['default']
  SourceSyncToast: typeof import("../../app/components/notifications/SourceSyncToast.vue")['default']
  CountryCard: typeof import("../../app/components/pays/CountryCard.vue")['default']
  PaysDetail: typeof import("../../app/components/pays/PaysDetail.vue")['default']
  PaysMap: typeof import("../../app/components/pays/PaysMap.vue")['default']
  PollPulseBanner: typeof import("../../app/components/polls/PollPulseBanner.vue")['default']
  SondageDetailView: typeof import("../../app/components/polls/SondageDetailView.vue")['default']
  SondagesListingView: typeof import("../../app/components/polls/SondagesListingView.vue")['default']
  SurveyCatalogCard: typeof import("../../app/components/polls/SurveyCatalogCard.vue")['default']
  SurveyCatalogRow: typeof import("../../app/components/polls/SurveyCatalogRow.vue")['default']
  SurveyFeaturedCard: typeof import("../../app/components/polls/SurveyFeaturedCard.vue")['default']
  SoinsMap: typeof import("../../app/components/soins/SoinsMap.vue")['default']
  StagingGate: typeof import("../../app/components/staging/StagingGate.vue")['default']
  DatasetCard: typeof import("../../app/components/statsdata/DatasetCard.vue")['default']
  StatsDataCatalogCard: typeof import("../../app/components/statsdata/StatsDataCatalogCard.vue")['default']
  StatsDataCatalogRow: typeof import("../../app/components/statsdata/StatsDataCatalogRow.vue")['default']
  StatsDataFeaturedCard: typeof import("../../app/components/statsdata/StatsDataFeaturedCard.vue")['default']
  StatsDataListingView: typeof import("../../app/components/statsdata/StatsDataListingView.vue")['default']
  StatsDataToolbar: typeof import("../../app/components/statsdata/StatsDataToolbar.vue")['default']
  StatsDataActionButton: typeof import("../../app/components/statsdata/detail/StatsDataActionButton.vue")['default']
  StatsDataBreadcrumb: typeof import("../../app/components/statsdata/detail/StatsDataBreadcrumb.vue")['default']
  StatsDataContent: typeof import("../../app/components/statsdata/detail/StatsDataContent.vue")['default']
  StatsDataCover: typeof import("../../app/components/statsdata/detail/StatsDataCover.vue")['default']
  StatsDataDetailView: typeof import("../../app/components/statsdata/detail/StatsDataDetailView.vue")['default']
  StatsDataEmbedModal: typeof import("../../app/components/statsdata/detail/StatsDataEmbedModal.vue")['default']
  StatsDataFreshnessBadge: typeof import("../../app/components/statsdata/detail/StatsDataFreshnessBadge.vue")['default']
  StatsDataHero: typeof import("../../app/components/statsdata/detail/StatsDataHero.vue")['default']
  StatsDataLinkButton: typeof import("../../app/components/statsdata/detail/StatsDataLinkButton.vue")['default']
  StatsDataLinkCard: typeof import("../../app/components/statsdata/detail/StatsDataLinkCard.vue")['default']
  StatsDataPageTabs: typeof import("../../app/components/statsdata/detail/StatsDataPageTabs.vue")['default']
  StatsDataPublisherCard: typeof import("../../app/components/statsdata/detail/StatsDataPublisherCard.vue")['default']
  StatsDataSection: typeof import("../../app/components/statsdata/detail/StatsDataSection.vue")['default']
  StatsDataShareMenu: typeof import("../../app/components/statsdata/detail/StatsDataShareMenu.vue")['default']
  StatsDataSourceCard: typeof import("../../app/components/statsdata/detail/StatsDataSourceCard.vue")['default']
  StatsDataSubHeader: typeof import("../../app/components/statsdata/detail/StatsDataSubHeader.vue")['default']
  StatsDataToc: typeof import("../../app/components/statsdata/detail/StatsDataToc.vue")['default']
  StatsDataToggleButton: typeof import("../../app/components/statsdata/detail/StatsDataToggleButton.vue")['default']
  StatsDataUsefulBar: typeof import("../../app/components/statsdata/detail/StatsDataUsefulBar.vue")['default']
  StatsDataSettingsBreadcrumb: typeof import("../../app/components/statsdata/settings/StatsDataSettingsBreadcrumb.vue")['default']
  StatsDataSettingsCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsCard.vue")['default']
  StatsDataSettingsCategoriesCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsCategoriesCard.vue")['default']
  StatsDataSettingsDangerZoneCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsDangerZoneCard.vue")['default']
  StatsDataSettingsEmojiCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsEmojiCard.vue")['default']
  StatsDataSettingsGeneralCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsGeneralCard.vue")['default']
  StatsDataSettingsHeader: typeof import("../../app/components/statsdata/settings/StatsDataSettingsHeader.vue")['default']
  StatsDataSettingsIdentityCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsIdentityCard.vue")['default']
  StatsDataSettingsResponseDeadlineCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsResponseDeadlineCard.vue")['default']
  StatsDataSettingsStudioCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsStudioCard.vue")['default']
  StatsDataSettingsSurveyKindCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsSurveyKindCard.vue")['default']
  StatsDataSettingsThumbnailCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsThumbnailCard.vue")['default']
  StatsDataSettingsVisibilityCard: typeof import("../../app/components/statsdata/settings/StatsDataSettingsVisibilityCard.vue")['default']
  StudioHeader: typeof import("../../app/components/studio/StudioHeader.vue")['default']
  StudioSidebarLeft: typeof import("../../app/components/studio/StudioSidebarLeft.vue")['default']
  StudioSidebarRight: typeof import("../../app/components/studio/StudioSidebarRight.vue")['default']
  TextFormatToolbar: typeof import("../../app/components/studio/TextFormatToolbar.vue")['default']
  VariablePickerModal: typeof import("../../app/components/studio/VariablePickerModal.vue")['default']
  MentionPicker: typeof import("../../app/components/studio/assistant/MentionPicker.vue")['default']
  StudioAssistantPanel: typeof import("../../app/components/studio/assistant/StudioAssistantPanel.vue")['default']
  BarChartBlock: typeof import("../../app/components/studio/blocks/BarChartBlock.vue")['default']
  BlockCard: typeof import("../../app/components/studio/blocks/BlockCard.vue")['default']
  BlockRenderer: typeof import("../../app/components/studio/blocks/BlockRenderer.vue")['default']
  ButtonBlock: typeof import("../../app/components/studio/blocks/ButtonBlock.vue")['default']
  CheckboxesBlock: typeof import("../../app/components/studio/blocks/CheckboxesBlock.vue")['default']
  DropdownBlock: typeof import("../../app/components/studio/blocks/DropdownBlock.vue")['default']
  FieldGridBlock: typeof import("../../app/components/studio/blocks/FieldGridBlock.vue")['default']
  IfBlock: typeof import("../../app/components/studio/blocks/IfBlock.vue")['default']
  ImageBlock: typeof import("../../app/components/studio/blocks/ImageBlock.vue")['default']
  KpiBlock: typeof import("../../app/components/studio/blocks/KpiBlock.vue")['default']
  LineChartBlock: typeof import("../../app/components/studio/blocks/LineChartBlock.vue")['default']
  LinearScaleBlock: typeof import("../../app/components/studio/blocks/LinearScaleBlock.vue")['default']
  LinkCardBlock: typeof import("../../app/components/studio/blocks/LinkCardBlock.vue")['default']
  LoopBlock: typeof import("../../app/components/studio/blocks/LoopBlock.vue")['default']
  MapBlock: typeof import("../../app/components/studio/blocks/MapBlock.vue")['default']
  MultipleChoiceBlock: typeof import("../../app/components/studio/blocks/MultipleChoiceBlock.vue")['default']
  ParamBlock: typeof import("../../app/components/studio/blocks/ParamBlock.vue")['default']
  PieChartBlock: typeof import("../../app/components/studio/blocks/PieChartBlock.vue")['default']
  RatingBlock: typeof import("../../app/components/studio/blocks/RatingBlock.vue")['default']
  RecordBlock: typeof import("../../app/components/studio/blocks/RecordBlock.vue")['default']
  RelatedBlock: typeof import("../../app/components/studio/blocks/RelatedBlock.vue")['default']
  RetenirBlock: typeof import("../../app/components/studio/blocks/RetenirBlock.vue")['default']
  SdEmbedBlock: typeof import("../../app/components/studio/blocks/SdEmbedBlock.vue")['default']
  SearchBlock: typeof import("../../app/components/studio/blocks/SearchBlock.vue")['default']
  TableBlock: typeof import("../../app/components/studio/blocks/TableBlock.vue")['default']
  TextBlock: typeof import("../../app/components/studio/blocks/TextBlock.vue")['default']
  VideoBlock: typeof import("../../app/components/studio/blocks/VideoBlock.vue")['default']
  BlockWrapper: typeof import("../../app/components/studio/canvas/BlockWrapper.vue")['default']
  CanvasGrid: typeof import("../../app/components/studio/canvas/CanvasGrid.vue")['default']
  CanvasSection: typeof import("../../app/components/studio/canvas/CanvasSection.vue")['default']
  CanvasZone: typeof import("../../app/components/studio/canvas/CanvasZone.vue")['default']
  SectionContext: typeof import("../../app/components/studio/canvas/section-context")['default']
  FieldChips: typeof import("../../app/components/studio/fields/FieldChips.vue")['default']
  FieldColorSwatches: typeof import("../../app/components/studio/fields/FieldColorSwatches.vue")['default']
  FieldColumns: typeof import("../../app/components/studio/fields/FieldColumns.vue")['default']
  FieldFilters: typeof import("../../app/components/studio/fields/FieldFilters.vue")['default']
  FieldList: typeof import("../../app/components/studio/fields/FieldList.vue")['default']
  FieldNote: typeof import("../../app/components/studio/fields/FieldNote.vue")['default']
  FieldPicker: typeof import("../../app/components/studio/fields/FieldPicker.vue")['default']
  FieldPreview: typeof import("../../app/components/studio/fields/FieldPreview.vue")['default']
  FieldSegmented: typeof import("../../app/components/studio/fields/FieldSegmented.vue")['default']
  FieldText: typeof import("../../app/components/studio/fields/FieldText.vue")['default']
  FieldTextarea: typeof import("../../app/components/studio/fields/FieldTextarea.vue")['default']
  FieldToggle: typeof import("../../app/components/studio/fields/FieldToggle.vue")['default']
  InspectorSection: typeof import("../../app/components/studio/fields/InspectorSection.vue")['default']
  InspectorTabs: typeof import("../../app/components/studio/fields/InspectorTabs.vue")['default']
  StudioField: typeof import("../../app/components/studio/fields/StudioField.vue")['default']
  VariableButton: typeof import("../../app/components/studio/fields/VariableButton.vue")['default']
  Options: typeof import("../../app/components/studio/fields/options")['default']
  DataBlockInspector: typeof import("../../app/components/studio/inspector/DataBlockInspector.vue")['default']
  FormBlockInspector: typeof import("../../app/components/studio/inspector/FormBlockInspector.vue")['default']
  IfBlockInspector: typeof import("../../app/components/studio/inspector/IfBlockInspector.vue")['default']
  LoopBlockInspector: typeof import("../../app/components/studio/inspector/LoopBlockInspector.vue")['default']
  MediaBlockInspector: typeof import("../../app/components/studio/inspector/MediaBlockInspector.vue")['default']
  ParamBlockInspector: typeof import("../../app/components/studio/inspector/ParamBlockInspector.vue")['default']
  RecordBlockInspector: typeof import("../../app/components/studio/inspector/RecordBlockInspector.vue")['default']
  RichBlockInspector: typeof import("../../app/components/studio/inspector/RichBlockInspector.vue")['default']
  SdEmbedBlockInspector: typeof import("../../app/components/studio/inspector/SdEmbedBlockInspector.vue")['default']
  SearchBlockInspector: typeof import("../../app/components/studio/inspector/SearchBlockInspector.vue")['default']
  SectionInspector: typeof import("../../app/components/studio/inspector/SectionInspector.vue")['default']
  AddSourceModal: typeof import("../../app/components/studio/sidebar/AddSourceModal.vue")['default']
  BlockConfigPanel: typeof import("../../app/components/studio/sidebar/BlockConfigPanel.vue")['default']
  DatasetSchemaPreview: typeof import("../../app/components/studio/sidebar/DatasetSchemaPreview.vue")['default']
  DetectedFiltersTable: typeof import("../../app/components/studio/sidebar/DetectedFiltersTable.vue")['default']
  DynamicParamsPanel: typeof import("../../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']
  EditSourceModal: typeof import("../../app/components/studio/sidebar/EditSourceModal.vue")['default']
  SidebarBlocks: typeof import("../../app/components/studio/sidebar/SidebarBlocks.vue")['default']
  SidebarDataSources: typeof import("../../app/components/studio/sidebar/SidebarDataSources.vue")['default']
  SidebarLayouts: typeof import("../../app/components/studio/sidebar/SidebarLayouts.vue")['default']
  SidebarScript: typeof import("../../app/components/studio/sidebar/SidebarScript.vue")['default']
  SourceCompatibilityCard: typeof import("../../app/components/studio/sidebar/SourceCompatibilityCard.vue")['default']
  ViewSourceDataModal: typeof import("../../app/components/studio/sidebar/ViewSourceDataModal.vue")['default']
  ApiDetectionResults: typeof import("../../app/components/studio/sidebar/add-source-steps/ApiDetectionResults.vue")['default']
  StepApiDetect: typeof import("../../app/components/studio/sidebar/add-source-steps/StepApiDetect.vue")['default']
  StepProvenance: typeof import("../../app/components/studio/sidebar/add-source-steps/StepProvenance.vue")['default']
  StepSourceConfigure: typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceConfigure.vue")['default']
  StepSourceType: typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceType.vue")['default']
  StepVisibility: typeof import("../../app/components/studio/sidebar/add-source-steps/StepVisibility.vue")['default']
  AggregationSelect: typeof import("../../app/components/studio/ui/AggregationSelect.vue")['default']
  ColumnButton: typeof import("../../app/components/studio/ui/ColumnButton.vue")['default']
  ColumnInput: typeof import("../../app/components/studio/ui/ColumnInput.vue")['default']
  ColumnPickerModal: typeof import("../../app/components/studio/ui/ColumnPickerModal.vue")['default']
  ColumnsMappingModal: typeof import("../../app/components/studio/ui/ColumnsMappingModal.vue")['default']
  DataSourceModal: typeof import("../../app/components/studio/ui/DataSourceModal.vue")['default']
  DataSourcePickerModal: typeof import("../../app/components/studio/ui/DataSourcePickerModal.vue")['default']
  EditorialContentModal: typeof import("../../app/components/studio/ui/EditorialContentModal.vue")['default']
  FiltersModal: typeof import("../../app/components/studio/ui/FiltersModal.vue")['default']
  SearchResultsDisplayModal: typeof import("../../app/components/studio/ui/SearchResultsDisplayModal.vue")['default']
  StudioModal: typeof import("../../app/components/studio/ui/StudioModal.vue")['default']
  StudioSubModal: typeof import("../../app/components/studio/ui/StudioSubModal.vue")['default']
  StudioWizardModal: typeof import("../../app/components/studio/ui/StudioWizardModal.vue")['default']
  URLParamPickerModal: typeof import("../../app/components/studio/ui/URLParamPickerModal.vue")['default']
  TvAudiencesEvolutionChart: typeof import("../../app/components/tv/TvAudiencesEvolutionChart.vue")['default']
  TvAudiencesRankingTable: typeof import("../../app/components/tv/TvAudiencesRankingTable.vue")['default']
  TvAudiencesTop50Table: typeof import("../../app/components/tv/TvAudiencesTop50Table.vue")['default']
  TvBroadcastActionCard: typeof import("../../app/components/tv/TvBroadcastActionCard.vue")['default']
  TvBroadcastAudienceCard: typeof import("../../app/components/tv/TvBroadcastAudienceCard.vue")['default']
  TvBroadcastDiffusions: typeof import("../../app/components/tv/TvBroadcastDiffusions.vue")['default']
  TvBroadcastHero: typeof import("../../app/components/tv/TvBroadcastHero.vue")['default']
  TvBroadcastInfoCard: typeof import("../../app/components/tv/TvBroadcastInfoCard.vue")['default']
  TvBroadcastReviews: typeof import("../../app/components/tv/TvBroadcastReviews.vue")['default']
  TvBroadcastScores: typeof import("../../app/components/tv/TvBroadcastScores.vue")['default']
  TvChannelBanner: typeof import("../../app/components/tv/TvChannelBanner.vue")['default']
  TvChannelLogo: typeof import("../../app/components/tv/TvChannelLogo.vue")['default']
  TvPopularProgrammeCard: typeof import("../../app/components/tv/TvPopularProgrammeCard.vue")['default']
  TvProgrammeCard: typeof import("../../app/components/tv/TvProgrammeCard.vue")['default']
  TvProgrammeCardIcon: typeof import("../../app/components/tv/TvProgrammeCardIcon.vue")['default']
  TvReviewModal: typeof import("../../app/components/tv/TvReviewModal.vue")['default']
  TvScheduleCardView: typeof import("../../app/components/tv/TvScheduleCardView.vue")['default']
  TvScheduleChannelRow: typeof import("../../app/components/tv/TvScheduleChannelRow.vue")['default']
  TvScheduleEmptyState: typeof import("../../app/components/tv/TvScheduleEmptyState.vue")['default']
  TvScheduleFilters: typeof import("../../app/components/tv/TvScheduleFilters.vue")['default']
  TvScheduleGrid: typeof import("../../app/components/tv/TvScheduleGrid.vue")['default']
  TvScheduleNowNext: typeof import("../../app/components/tv/TvScheduleNowNext.vue")['default']
  TvScheduleProgrammeBlock: typeof import("../../app/components/tv/TvScheduleProgrammeBlock.vue")['default']
  TvScheduleTimeline: typeof import("../../app/components/tv/TvScheduleTimeline.vue")['default']
  AppAvatar: typeof import("../../app/components/ui/AppAvatar.vue")['default']
  AppBadge: typeof import("../../app/components/ui/AppBadge.vue")['default']
  AppButton: typeof import("../../app/components/ui/AppButton.vue")['default']
  AppCheckbox: typeof import("../../app/components/ui/AppCheckbox.vue")['default']
  AppColorPickerModal: typeof import("../../app/components/ui/AppColorPickerModal.vue")['default']
  AppLockedPanel: typeof import("../../app/components/ui/AppLockedPanel.vue")['default']
  AppModal: typeof import("../../app/components/ui/AppModal.vue")['default']
  AppPageSection: typeof import("../../app/components/ui/AppPageSection.vue")['default']
  AppPagination: typeof import("../../app/components/ui/AppPagination.vue")['default']
  AppRankingList: typeof import("../../app/components/ui/AppRankingList.vue")['default']
  AppRelatedSlider: typeof import("../../app/components/ui/AppRelatedSlider.vue")['default']
  AppSectionHeader: typeof import("../../app/components/ui/AppSectionHeader.vue")['default']
  AppSectionTabs: typeof import("../../app/components/ui/AppSectionTabs.vue")['default']
  AppSelect: typeof import("../../app/components/ui/AppSelect.vue")['default']
  AppSidebarNavItem: typeof import("../../app/components/ui/AppSidebarNavItem.vue")['default']
  AppSparkline: typeof import("../../app/components/ui/AppSparkline.vue")['default']
  AppStatCard: typeof import("../../app/components/ui/AppStatCard.vue")['default']
  AppStepModal: typeof import("../../app/components/ui/AppStepModal.vue")['default']
  AppTooltip: typeof import("../../app/components/ui/AppTooltip.vue")['default']
  AppTurnstile: typeof import("../../app/components/ui/AppTurnstile.vue")['default']
  AppWordmark: typeof import("../../app/components/ui/AppWordmark.vue")['default']
  AppWorldScatterMap: typeof import("../../app/components/ui/AppWorldScatterMap.vue")['default']
  AccountAvatarUploader: typeof import("../../app/components/user/AccountAvatarUploader.vue")['default']
  AccountContentThumb: typeof import("../../app/components/user/AccountContentThumb.vue")['default']
  AccountDangerZone: typeof import("../../app/components/user/AccountDangerZone.vue")['default']
  AccountDemographicsCard: typeof import("../../app/components/user/AccountDemographicsCard.vue")['default']
  AccountNotificationsCard: typeof import("../../app/components/user/AccountNotificationsCard.vue")['default']
  AccountPageHeader: typeof import("../../app/components/user/AccountPageHeader.vue")['default']
  AccountProfileCard: typeof import("../../app/components/user/AccountProfileCard.vue")['default']
  AccountSearch: typeof import("../../app/components/user/AccountSearch.vue")['default']
  AccountSidebar: typeof import("../../app/components/user/AccountSidebar.vue")['default']
  AccountToggle: typeof import("../../app/components/user/AccountToggle.vue")['default']
  AccountTopbar: typeof import("../../app/components/user/AccountTopbar.vue")['default']
  FavoriteCard: typeof import("../../app/components/user/FavoriteCard.vue")['default']
  SubscriptionRow: typeof import("../../app/components/user/SubscriptionRow.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyCookieBanner: LazyComponent<typeof import("../../app/components/CookieBanner.vue")['default']>
  LazyArticleBody: LazyComponent<typeof import("../../app/components/articles/ArticleBody.vue")['default']>
  LazyArticleCatalogCard: LazyComponent<typeof import("../../app/components/articles/ArticleCatalogCard.vue")['default']>
  LazyArticleCatalogRow: LazyComponent<typeof import("../../app/components/articles/ArticleCatalogRow.vue")['default']>
  LazyArticleDetailView: LazyComponent<typeof import("../../app/components/articles/ArticleDetailView.vue")['default']>
  LazyArticleFeaturedCard: LazyComponent<typeof import("../../app/components/articles/ArticleFeaturedCard.vue")['default']>
  LazyArticleHero: LazyComponent<typeof import("../../app/components/articles/ArticleHero.vue")['default']>
  LazyArticleSubHeader: LazyComponent<typeof import("../../app/components/articles/ArticleSubHeader.vue")['default']>
  LazyArticleTeaserCard: LazyComponent<typeof import("../../app/components/articles/ArticleTeaserCard.vue")['default']>
  LazyArticleToc: LazyComponent<typeof import("../../app/components/articles/ArticleToc.vue")['default']>
  LazyArticlesListingView: LazyComponent<typeof import("../../app/components/articles/ArticlesListingView.vue")['default']>
  LazyAuthBrandPanel: LazyComponent<typeof import("../../app/components/auth/AuthBrandPanel.vue")['default']>
  LazyAuthCard: LazyComponent<typeof import("../../app/components/auth/AuthCard.vue")['default']>
  LazyAuthDivider: LazyComponent<typeof import("../../app/components/auth/AuthDivider.vue")['default']>
  LazyAuthErrorAlert: LazyComponent<typeof import("../../app/components/auth/AuthErrorAlert.vue")['default']>
  LazyAuthGoogleButton: LazyComponent<typeof import("../../app/components/auth/AuthGoogleButton.vue")['default']>
  LazyAuthInputField: LazyComponent<typeof import("../../app/components/auth/AuthInputField.vue")['default']>
  LazyAuthShell: LazyComponent<typeof import("../../app/components/auth/AuthShell.vue")['default']>
  LazyAuthStatCard: LazyComponent<typeof import("../../app/components/auth/AuthStatCard.vue")['default']>
  LazyAuthTopBar: LazyComponent<typeof import("../../app/components/auth/AuthTopBar.vue")['default']>
  LazyForgotPasswordFormCard: LazyComponent<typeof import("../../app/components/auth/ForgotPasswordFormCard.vue")['default']>
  LazyLoginFormCard: LazyComponent<typeof import("../../app/components/auth/LoginFormCard.vue")['default']>
  LazyPasswordStrengthMeter: LazyComponent<typeof import("../../app/components/auth/PasswordStrengthMeter.vue")['default']>
  LazyRegisterFormCard: LazyComponent<typeof import("../../app/components/auth/RegisterFormCard.vue")['default']>
  LazyResetPasswordFormCard: LazyComponent<typeof import("../../app/components/auth/ResetPasswordFormCard.vue")['default']>
  LazyVerifyEmailFormCard: LazyComponent<typeof import("../../app/components/auth/VerifyEmailFormCard.vue")['default']>
  LazyChannelConsentModal: LazyComponent<typeof import("../../app/components/chaines/ChannelConsentModal.vue")['default']>
  LazyChannelCreateCard: LazyComponent<typeof import("../../app/components/chaines/ChannelCreateCard.vue")['default']>
  LazyChannelBadgeList: LazyComponent<typeof import("../../app/components/channels/ChannelBadgeList.vue")['default']>
  LazyChannelCard: LazyComponent<typeof import("../../app/components/channels/ChannelCard.vue")['default']>
  LazyChannelCatalogCard: LazyComponent<typeof import("../../app/components/channels/ChannelCatalogCard.vue")['default']>
  LazyChannelCatalogRow: LazyComponent<typeof import("../../app/components/channels/ChannelCatalogRow.vue")['default']>
  LazyChannelContentTypeFilter: LazyComponent<typeof import("../../app/components/channels/ChannelContentTypeFilter.vue")['default']>
  LazyChannelFeaturedCard: LazyComponent<typeof import("../../app/components/channels/ChannelFeaturedCard.vue")['default']>
  LazyChannelInviteMembersModal: LazyComponent<typeof import("../../app/components/channels/ChannelInviteMembersModal.vue")['default']>
  LazyChannelOrganizationBadge: LazyComponent<typeof import("../../app/components/channels/ChannelOrganizationBadge.vue")['default']>
  LazyChannelPopularityCard: LazyComponent<typeof import("../../app/components/channels/ChannelPopularityCard.vue")['default']>
  LazyChannelSwitcher: LazyComponent<typeof import("../../app/components/channels/ChannelSwitcher.vue")['default']>
  LazyChannelVerifiedBadge: LazyComponent<typeof import("../../app/components/channels/ChannelVerifiedBadge.vue")['default']>
  LazyChannelsListingView: LazyComponent<typeof import("../../app/components/channels/ChannelsListingView.vue")['default']>
  LazyChannelDashboardHeader: LazyComponent<typeof import("../../app/components/channels/dashboard/ChannelDashboardHeader.vue")['default']>
  LazyChannelDashboardSearch: LazyComponent<typeof import("../../app/components/channels/dashboard/ChannelDashboardSearch.vue")['default']>
  LazyChannelDataSourceRow: LazyComponent<typeof import("../../app/components/channels/dashboard/ChannelDataSourceRow.vue")['default']>
  LazyChannelSidebar: LazyComponent<typeof import("../../app/components/channels/dashboard/ChannelSidebar.vue")['default']>
  LazyChannelTopbar: LazyComponent<typeof import("../../app/components/channels/dashboard/ChannelTopbar.vue")['default']>
  LazyChannelViewsBreakdownCard: LazyComponent<typeof import("../../app/components/channels/dashboard/ChannelViewsBreakdownCard.vue")['default']>
  LazyChannelAboutTab: LazyComponent<typeof import("../../app/components/channels/detail/ChannelAboutTab.vue")['default']>
  LazyChannelBanner: LazyComponent<typeof import("../../app/components/channels/detail/ChannelBanner.vue")['default']>
  LazyChannelBreadcrumb: LazyComponent<typeof import("../../app/components/channels/detail/ChannelBreadcrumb.vue")['default']>
  LazyChannelDatasetList: LazyComponent<typeof import("../../app/components/channels/detail/ChannelDatasetList.vue")['default']>
  LazyChannelDetailTabs: LazyComponent<typeof import("../../app/components/channels/detail/ChannelDetailTabs.vue")['default']>
  LazyChannelDetailView: LazyComponent<typeof import("../../app/components/channels/detail/ChannelDetailView.vue")['default']>
  LazyChannelFeaturedTab: LazyComponent<typeof import("../../app/components/channels/detail/ChannelFeaturedTab.vue")['default']>
  LazyChannelFeedList: LazyComponent<typeof import("../../app/components/channels/detail/ChannelFeedList.vue")['default']>
  LazyChannelPollGridCard: LazyComponent<typeof import("../../app/components/channels/detail/ChannelPollGridCard.vue")['default']>
  LazyChannelPollsTab: LazyComponent<typeof import("../../app/components/channels/detail/ChannelPollsTab.vue")['default']>
  LazyChannelProfileHeader: LazyComponent<typeof import("../../app/components/channels/detail/ChannelProfileHeader.vue")['default']>
  LazyChannelShareModal: LazyComponent<typeof import("../../app/components/channels/detail/ChannelShareModal.vue")['default']>
  LazyChannelSimilarSlider: LazyComponent<typeof import("../../app/components/channels/detail/ChannelSimilarSlider.vue")['default']>
  LazyChannelStatsStrip: LazyComponent<typeof import("../../app/components/channels/detail/ChannelStatsStrip.vue")['default']>
  LazyChannelOrganizationSettings: LazyComponent<typeof import("../../app/components/channels/settings/ChannelOrganizationSettings.vue")['default']>
  LazyChannelPrivacySettings: LazyComponent<typeof import("../../app/components/channels/settings/ChannelPrivacySettings.vue")['default']>
  LazyChannelProfileSettings: LazyComponent<typeof import("../../app/components/channels/settings/ChannelProfileSettings.vue")['default']>
  LazyStepChannelCategories: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelCategories.vue")['default']>
  LazyStepChannelLegal: LazyComponent<typeof import("../../app/components/channels/steps/StepChannelLegal.vue")['default']>
  LazyComingSoonGate: LazyComponent<typeof import("../../app/components/coming-soon/ComingSoonGate.vue")['default']>
  LazyComingSoonPage: LazyComponent<typeof import("../../app/components/coming-soon/ComingSoonPage.vue")['default']>
  LazyContentComingSoonCard: LazyComponent<typeof import("../../app/components/contents/dashboard/ContentComingSoonCard.vue")['default']>
  LazyContentDashboardHeader: LazyComponent<typeof import("../../app/components/contents/dashboard/ContentDashboardHeader.vue")['default']>
  LazyContentSidebar: LazyComponent<typeof import("../../app/components/contents/dashboard/ContentSidebar.vue")['default']>
  LazyContentTopbar: LazyComponent<typeof import("../../app/components/contents/dashboard/ContentTopbar.vue")['default']>
  LazyContentCard: LazyComponent<typeof import("../../app/components/contenus/ContentCard.vue")['default']>
  LazyContenusCreateButton: LazyComponent<typeof import("../../app/components/contenus/ContenusCreateButton.vue")['default']>
  LazyContenusEmptyState: LazyComponent<typeof import("../../app/components/contenus/ContenusEmptyState.vue")['default']>
  LazyContenusFilters: LazyComponent<typeof import("../../app/components/contenus/ContenusFilters.vue")['default']>
  LazyContenusLegend: LazyComponent<typeof import("../../app/components/contenus/ContenusLegend.vue")['default']>
  LazyCreateContentMenu: LazyComponent<typeof import("../../app/components/create/CreateContentMenu.vue")['default']>
  LazyCreateContentModal: LazyComponent<typeof import("../../app/components/create/CreateContentModal.vue")['default']>
  LazyStepCategories: LazyComponent<typeof import("../../app/components/create/steps/StepCategories.vue")['default']>
  LazyStepCoverage: LazyComponent<typeof import("../../app/components/create/steps/StepCoverage.vue")['default']>
  LazyStepPublication: LazyComponent<typeof import("../../app/components/create/steps/StepPublication.vue")['default']>
  LazyStepSuccess: LazyComponent<typeof import("../../app/components/create/steps/StepSuccess.vue")['default']>
  LazyStepSurveyType: LazyComponent<typeof import("../../app/components/create/steps/StepSurveyType.vue")['default']>
  LazyStepTitle: LazyComponent<typeof import("../../app/components/create/steps/StepTitle.vue")['default']>
  LazyPageHero: LazyComponent<typeof import("../../app/components/home/PageHero.vue")['default']>
  LazyMedistatsHero: LazyComponent<typeof import("../../app/components/home/medistats/MedistatsHero.vue")['default']>
  LazyMedistatsHighlights: LazyComponent<typeof import("../../app/components/home/medistats/MedistatsHighlights.vue")['default']>
  LazyMedistatsHome: LazyComponent<typeof import("../../app/components/home/medistats/MedistatsHome.vue")['default']>
  LazyHomeArticlesV2: LazyComponent<typeof import("../../app/components/home/statsio/HomeArticlesV2.vue")['default']>
  LazyHomeCarousel: LazyComponent<typeof import("../../app/components/home/statsio/HomeCarousel.vue")['default']>
  LazyHomeChannelsStrip: LazyComponent<typeof import("../../app/components/home/statsio/HomeChannelsStrip.vue")['default']>
  LazyHomeCreateSteps: LazyComponent<typeof import("../../app/components/home/statsio/HomeCreateSteps.vue")['default']>
  LazyHomeCtaBanner: LazyComponent<typeof import("../../app/components/home/statsio/HomeCtaBanner.vue")['default']>
  LazyHomeFaq: LazyComponent<typeof import("../../app/components/home/statsio/HomeFaq.vue")['default']>
  LazyHomeHeroV2: LazyComponent<typeof import("../../app/components/home/statsio/HomeHeroV2.vue")['default']>
  LazyHomeSondagesV2: LazyComponent<typeof import("../../app/components/home/statsio/HomeSondagesV2.vue")['default']>
  LazyHomeStatsDataV2: LazyComponent<typeof import("../../app/components/home/statsio/HomeStatsDataV2.vue")['default']>
  LazyStatsioHome: LazyComponent<typeof import("../../app/components/home/statsio/StatsioHome.vue")['default']>
  LazyTvstatsHero: LazyComponent<typeof import("../../app/components/home/tvstats/TvstatsHero.vue")['default']>
  LazyTvstatsHighlights: LazyComponent<typeof import("../../app/components/home/tvstats/TvstatsHighlights.vue")['default']>
  LazyTvstatsHome: LazyComponent<typeof import("../../app/components/home/tvstats/TvstatsHome.vue")['default']>
  LazyIconCommunity: LazyComponent<typeof import("../../app/components/icons/IconCommunity.vue")['default']>
  LazyIconDocumentation: LazyComponent<typeof import("../../app/components/icons/IconDocumentation.vue")['default']>
  LazyIconEcosystem: LazyComponent<typeof import("../../app/components/icons/IconEcosystem.vue")['default']>
  LazyIconSupport: LazyComponent<typeof import("../../app/components/icons/IconSupport.vue")['default']>
  LazyIconTooling: LazyComponent<typeof import("../../app/components/icons/IconTooling.vue")['default']>
  LazyAppAccessibilityPanel: LazyComponent<typeof import("../../app/components/layout/AppAccessibilityPanel.vue")['default']>
  LazyAppBootstrapError: LazyComponent<typeof import("../../app/components/layout/AppBootstrapError.vue")['default']>
  LazyAppCreateFab: LazyComponent<typeof import("../../app/components/layout/AppCreateFab.vue")['default']>
  LazyAppDropdownMenu: LazyComponent<typeof import("../../app/components/layout/AppDropdownMenu.vue")['default']>
  LazyAppDropdownMenuItem: LazyComponent<typeof import("../../app/components/layout/AppDropdownMenuItem.vue")['default']>
  LazyAppFooter: LazyComponent<typeof import("../../app/components/layout/AppFooter.vue")['default']>
  LazyAppHeader: LazyComponent<typeof import("../../app/components/layout/AppHeader.vue")['default']>
  LazyAppHeaderMegaMenu: LazyComponent<typeof import("../../app/components/layout/AppHeaderMegaMenu.vue")['default']>
  LazyAppHeaderSearch: LazyComponent<typeof import("../../app/components/layout/AppHeaderSearch.vue")['default']>
  LazyAppLoadingBar: LazyComponent<typeof import("../../app/components/layout/AppLoadingBar.vue")['default']>
  LazyAppNavIcon: LazyComponent<typeof import("../../app/components/layout/AppNavIcon.vue")['default']>
  LazyAppNotificationStack: LazyComponent<typeof import("../../app/components/layout/AppNotificationStack.vue")['default']>
  LazyAppPromoBanner: LazyComponent<typeof import("../../app/components/layout/AppPromoBanner.vue")['default']>
  LazyDashboardShell: LazyComponent<typeof import("../../app/components/layout/DashboardShell.vue")['default']>
  LazyCatalogChipRow: LazyComponent<typeof import("../../app/components/listing/CatalogChipRow.vue")['default']>
  LazyCatalogCta: LazyComponent<typeof import("../../app/components/listing/CatalogCta.vue")['default']>
  LazyCatalogEmpty: LazyComponent<typeof import("../../app/components/listing/CatalogEmpty.vue")['default']>
  LazyCatalogFavButton: LazyComponent<typeof import("../../app/components/listing/CatalogFavButton.vue")['default']>
  LazyCatalogHero: LazyComponent<typeof import("../../app/components/listing/CatalogHero.vue")['default']>
  LazyCatalogLoadMore: LazyComponent<typeof import("../../app/components/listing/CatalogLoadMore.vue")['default']>
  LazyCatalogPublisherRow: LazyComponent<typeof import("../../app/components/listing/CatalogPublisherRow.vue")['default']>
  LazyCatalogResultBar: LazyComponent<typeof import("../../app/components/listing/CatalogResultBar.vue")['default']>
  LazyCatalogSearchField: LazyComponent<typeof import("../../app/components/listing/CatalogSearchField.vue")['default']>
  LazyCatalogSortPills: LazyComponent<typeof import("../../app/components/listing/CatalogSortPills.vue")['default']>
  LazyCatalogSubBrandTag: LazyComponent<typeof import("../../app/components/listing/CatalogSubBrandTag.vue")['default']>
  LazyCatalogToggleChip: LazyComponent<typeof import("../../app/components/listing/CatalogToggleChip.vue")['default']>
  LazyCatalogToolbar: LazyComponent<typeof import("../../app/components/listing/CatalogToolbar.vue")['default']>
  LazyCatalogViewToggle: LazyComponent<typeof import("../../app/components/listing/CatalogViewToggle.vue")['default']>
  LazyMaladiesCard: LazyComponent<typeof import("../../app/components/maladies/MaladiesCard.vue")['default']>
  LazyMaladiesDetail: LazyComponent<typeof import("../../app/components/maladies/MaladiesDetail.vue")['default']>
  LazyMaladiesExplorer: LazyComponent<typeof import("../../app/components/maladies/MaladiesExplorer.vue")['default']>
  LazyMaladiesRankedList: LazyComponent<typeof import("../../app/components/maladies/MaladiesRankedList.vue")['default']>
  LazyMedicamentsCard: LazyComponent<typeof import("../../app/components/medicaments/MedicamentsCard.vue")['default']>
  LazyMedicamentsDetail: LazyComponent<typeof import("../../app/components/medicaments/MedicamentsDetail.vue")['default']>
  LazyMedicamentsExplorer: LazyComponent<typeof import("../../app/components/medicaments/MedicamentsExplorer.vue")['default']>
  LazySourceSyncToast: LazyComponent<typeof import("../../app/components/notifications/SourceSyncToast.vue")['default']>
  LazyCountryCard: LazyComponent<typeof import("../../app/components/pays/CountryCard.vue")['default']>
  LazyPaysDetail: LazyComponent<typeof import("../../app/components/pays/PaysDetail.vue")['default']>
  LazyPaysMap: LazyComponent<typeof import("../../app/components/pays/PaysMap.vue")['default']>
  LazyPollPulseBanner: LazyComponent<typeof import("../../app/components/polls/PollPulseBanner.vue")['default']>
  LazySondageDetailView: LazyComponent<typeof import("../../app/components/polls/SondageDetailView.vue")['default']>
  LazySondagesListingView: LazyComponent<typeof import("../../app/components/polls/SondagesListingView.vue")['default']>
  LazySurveyCatalogCard: LazyComponent<typeof import("../../app/components/polls/SurveyCatalogCard.vue")['default']>
  LazySurveyCatalogRow: LazyComponent<typeof import("../../app/components/polls/SurveyCatalogRow.vue")['default']>
  LazySurveyFeaturedCard: LazyComponent<typeof import("../../app/components/polls/SurveyFeaturedCard.vue")['default']>
  LazySoinsMap: LazyComponent<typeof import("../../app/components/soins/SoinsMap.vue")['default']>
  LazyStagingGate: LazyComponent<typeof import("../../app/components/staging/StagingGate.vue")['default']>
  LazyDatasetCard: LazyComponent<typeof import("../../app/components/statsdata/DatasetCard.vue")['default']>
  LazyStatsDataCatalogCard: LazyComponent<typeof import("../../app/components/statsdata/StatsDataCatalogCard.vue")['default']>
  LazyStatsDataCatalogRow: LazyComponent<typeof import("../../app/components/statsdata/StatsDataCatalogRow.vue")['default']>
  LazyStatsDataFeaturedCard: LazyComponent<typeof import("../../app/components/statsdata/StatsDataFeaturedCard.vue")['default']>
  LazyStatsDataListingView: LazyComponent<typeof import("../../app/components/statsdata/StatsDataListingView.vue")['default']>
  LazyStatsDataToolbar: LazyComponent<typeof import("../../app/components/statsdata/StatsDataToolbar.vue")['default']>
  LazyStatsDataActionButton: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataActionButton.vue")['default']>
  LazyStatsDataBreadcrumb: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataBreadcrumb.vue")['default']>
  LazyStatsDataContent: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataContent.vue")['default']>
  LazyStatsDataCover: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataCover.vue")['default']>
  LazyStatsDataDetailView: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataDetailView.vue")['default']>
  LazyStatsDataEmbedModal: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataEmbedModal.vue")['default']>
  LazyStatsDataFreshnessBadge: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataFreshnessBadge.vue")['default']>
  LazyStatsDataHero: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataHero.vue")['default']>
  LazyStatsDataLinkButton: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataLinkButton.vue")['default']>
  LazyStatsDataLinkCard: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataLinkCard.vue")['default']>
  LazyStatsDataPageTabs: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataPageTabs.vue")['default']>
  LazyStatsDataPublisherCard: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataPublisherCard.vue")['default']>
  LazyStatsDataSection: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataSection.vue")['default']>
  LazyStatsDataShareMenu: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataShareMenu.vue")['default']>
  LazyStatsDataSourceCard: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataSourceCard.vue")['default']>
  LazyStatsDataSubHeader: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataSubHeader.vue")['default']>
  LazyStatsDataToc: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataToc.vue")['default']>
  LazyStatsDataToggleButton: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataToggleButton.vue")['default']>
  LazyStatsDataUsefulBar: LazyComponent<typeof import("../../app/components/statsdata/detail/StatsDataUsefulBar.vue")['default']>
  LazyStatsDataSettingsBreadcrumb: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsBreadcrumb.vue")['default']>
  LazyStatsDataSettingsCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsCard.vue")['default']>
  LazyStatsDataSettingsCategoriesCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsCategoriesCard.vue")['default']>
  LazyStatsDataSettingsDangerZoneCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsDangerZoneCard.vue")['default']>
  LazyStatsDataSettingsEmojiCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsEmojiCard.vue")['default']>
  LazyStatsDataSettingsGeneralCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsGeneralCard.vue")['default']>
  LazyStatsDataSettingsHeader: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsHeader.vue")['default']>
  LazyStatsDataSettingsIdentityCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsIdentityCard.vue")['default']>
  LazyStatsDataSettingsResponseDeadlineCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsResponseDeadlineCard.vue")['default']>
  LazyStatsDataSettingsStudioCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsStudioCard.vue")['default']>
  LazyStatsDataSettingsSurveyKindCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsSurveyKindCard.vue")['default']>
  LazyStatsDataSettingsThumbnailCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsThumbnailCard.vue")['default']>
  LazyStatsDataSettingsVisibilityCard: LazyComponent<typeof import("../../app/components/statsdata/settings/StatsDataSettingsVisibilityCard.vue")['default']>
  LazyStudioHeader: LazyComponent<typeof import("../../app/components/studio/StudioHeader.vue")['default']>
  LazyStudioSidebarLeft: LazyComponent<typeof import("../../app/components/studio/StudioSidebarLeft.vue")['default']>
  LazyStudioSidebarRight: LazyComponent<typeof import("../../app/components/studio/StudioSidebarRight.vue")['default']>
  LazyTextFormatToolbar: LazyComponent<typeof import("../../app/components/studio/TextFormatToolbar.vue")['default']>
  LazyVariablePickerModal: LazyComponent<typeof import("../../app/components/studio/VariablePickerModal.vue")['default']>
  LazyMentionPicker: LazyComponent<typeof import("../../app/components/studio/assistant/MentionPicker.vue")['default']>
  LazyStudioAssistantPanel: LazyComponent<typeof import("../../app/components/studio/assistant/StudioAssistantPanel.vue")['default']>
  LazyBarChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/BarChartBlock.vue")['default']>
  LazyBlockCard: LazyComponent<typeof import("../../app/components/studio/blocks/BlockCard.vue")['default']>
  LazyBlockRenderer: LazyComponent<typeof import("../../app/components/studio/blocks/BlockRenderer.vue")['default']>
  LazyButtonBlock: LazyComponent<typeof import("../../app/components/studio/blocks/ButtonBlock.vue")['default']>
  LazyCheckboxesBlock: LazyComponent<typeof import("../../app/components/studio/blocks/CheckboxesBlock.vue")['default']>
  LazyDropdownBlock: LazyComponent<typeof import("../../app/components/studio/blocks/DropdownBlock.vue")['default']>
  LazyFieldGridBlock: LazyComponent<typeof import("../../app/components/studio/blocks/FieldGridBlock.vue")['default']>
  LazyIfBlock: LazyComponent<typeof import("../../app/components/studio/blocks/IfBlock.vue")['default']>
  LazyImageBlock: LazyComponent<typeof import("../../app/components/studio/blocks/ImageBlock.vue")['default']>
  LazyKpiBlock: LazyComponent<typeof import("../../app/components/studio/blocks/KpiBlock.vue")['default']>
  LazyLineChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LineChartBlock.vue")['default']>
  LazyLinearScaleBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LinearScaleBlock.vue")['default']>
  LazyLinkCardBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LinkCardBlock.vue")['default']>
  LazyLoopBlock: LazyComponent<typeof import("../../app/components/studio/blocks/LoopBlock.vue")['default']>
  LazyMapBlock: LazyComponent<typeof import("../../app/components/studio/blocks/MapBlock.vue")['default']>
  LazyMultipleChoiceBlock: LazyComponent<typeof import("../../app/components/studio/blocks/MultipleChoiceBlock.vue")['default']>
  LazyParamBlock: LazyComponent<typeof import("../../app/components/studio/blocks/ParamBlock.vue")['default']>
  LazyPieChartBlock: LazyComponent<typeof import("../../app/components/studio/blocks/PieChartBlock.vue")['default']>
  LazyRatingBlock: LazyComponent<typeof import("../../app/components/studio/blocks/RatingBlock.vue")['default']>
  LazyRecordBlock: LazyComponent<typeof import("../../app/components/studio/blocks/RecordBlock.vue")['default']>
  LazyRelatedBlock: LazyComponent<typeof import("../../app/components/studio/blocks/RelatedBlock.vue")['default']>
  LazyRetenirBlock: LazyComponent<typeof import("../../app/components/studio/blocks/RetenirBlock.vue")['default']>
  LazySdEmbedBlock: LazyComponent<typeof import("../../app/components/studio/blocks/SdEmbedBlock.vue")['default']>
  LazySearchBlock: LazyComponent<typeof import("../../app/components/studio/blocks/SearchBlock.vue")['default']>
  LazyTableBlock: LazyComponent<typeof import("../../app/components/studio/blocks/TableBlock.vue")['default']>
  LazyTextBlock: LazyComponent<typeof import("../../app/components/studio/blocks/TextBlock.vue")['default']>
  LazyVideoBlock: LazyComponent<typeof import("../../app/components/studio/blocks/VideoBlock.vue")['default']>
  LazyBlockWrapper: LazyComponent<typeof import("../../app/components/studio/canvas/BlockWrapper.vue")['default']>
  LazyCanvasGrid: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasGrid.vue")['default']>
  LazyCanvasSection: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasSection.vue")['default']>
  LazyCanvasZone: LazyComponent<typeof import("../../app/components/studio/canvas/CanvasZone.vue")['default']>
  LazySectionContext: LazyComponent<typeof import("../../app/components/studio/canvas/section-context")['default']>
  LazyFieldChips: LazyComponent<typeof import("../../app/components/studio/fields/FieldChips.vue")['default']>
  LazyFieldColorSwatches: LazyComponent<typeof import("../../app/components/studio/fields/FieldColorSwatches.vue")['default']>
  LazyFieldColumns: LazyComponent<typeof import("../../app/components/studio/fields/FieldColumns.vue")['default']>
  LazyFieldFilters: LazyComponent<typeof import("../../app/components/studio/fields/FieldFilters.vue")['default']>
  LazyFieldList: LazyComponent<typeof import("../../app/components/studio/fields/FieldList.vue")['default']>
  LazyFieldNote: LazyComponent<typeof import("../../app/components/studio/fields/FieldNote.vue")['default']>
  LazyFieldPicker: LazyComponent<typeof import("../../app/components/studio/fields/FieldPicker.vue")['default']>
  LazyFieldPreview: LazyComponent<typeof import("../../app/components/studio/fields/FieldPreview.vue")['default']>
  LazyFieldSegmented: LazyComponent<typeof import("../../app/components/studio/fields/FieldSegmented.vue")['default']>
  LazyFieldText: LazyComponent<typeof import("../../app/components/studio/fields/FieldText.vue")['default']>
  LazyFieldTextarea: LazyComponent<typeof import("../../app/components/studio/fields/FieldTextarea.vue")['default']>
  LazyFieldToggle: LazyComponent<typeof import("../../app/components/studio/fields/FieldToggle.vue")['default']>
  LazyInspectorSection: LazyComponent<typeof import("../../app/components/studio/fields/InspectorSection.vue")['default']>
  LazyInspectorTabs: LazyComponent<typeof import("../../app/components/studio/fields/InspectorTabs.vue")['default']>
  LazyStudioField: LazyComponent<typeof import("../../app/components/studio/fields/StudioField.vue")['default']>
  LazyVariableButton: LazyComponent<typeof import("../../app/components/studio/fields/VariableButton.vue")['default']>
  LazyOptions: LazyComponent<typeof import("../../app/components/studio/fields/options")['default']>
  LazyDataBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/DataBlockInspector.vue")['default']>
  LazyFormBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/FormBlockInspector.vue")['default']>
  LazyIfBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/IfBlockInspector.vue")['default']>
  LazyLoopBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/LoopBlockInspector.vue")['default']>
  LazyMediaBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/MediaBlockInspector.vue")['default']>
  LazyParamBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/ParamBlockInspector.vue")['default']>
  LazyRecordBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/RecordBlockInspector.vue")['default']>
  LazyRichBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/RichBlockInspector.vue")['default']>
  LazySdEmbedBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/SdEmbedBlockInspector.vue")['default']>
  LazySearchBlockInspector: LazyComponent<typeof import("../../app/components/studio/inspector/SearchBlockInspector.vue")['default']>
  LazySectionInspector: LazyComponent<typeof import("../../app/components/studio/inspector/SectionInspector.vue")['default']>
  LazyAddSourceModal: LazyComponent<typeof import("../../app/components/studio/sidebar/AddSourceModal.vue")['default']>
  LazyBlockConfigPanel: LazyComponent<typeof import("../../app/components/studio/sidebar/BlockConfigPanel.vue")['default']>
  LazyDatasetSchemaPreview: LazyComponent<typeof import("../../app/components/studio/sidebar/DatasetSchemaPreview.vue")['default']>
  LazyDetectedFiltersTable: LazyComponent<typeof import("../../app/components/studio/sidebar/DetectedFiltersTable.vue")['default']>
  LazyDynamicParamsPanel: LazyComponent<typeof import("../../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']>
  LazyEditSourceModal: LazyComponent<typeof import("../../app/components/studio/sidebar/EditSourceModal.vue")['default']>
  LazySidebarBlocks: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarBlocks.vue")['default']>
  LazySidebarDataSources: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarDataSources.vue")['default']>
  LazySidebarLayouts: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarLayouts.vue")['default']>
  LazySidebarScript: LazyComponent<typeof import("../../app/components/studio/sidebar/SidebarScript.vue")['default']>
  LazySourceCompatibilityCard: LazyComponent<typeof import("../../app/components/studio/sidebar/SourceCompatibilityCard.vue")['default']>
  LazyViewSourceDataModal: LazyComponent<typeof import("../../app/components/studio/sidebar/ViewSourceDataModal.vue")['default']>
  LazyApiDetectionResults: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/ApiDetectionResults.vue")['default']>
  LazyStepApiDetect: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepApiDetect.vue")['default']>
  LazyStepProvenance: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepProvenance.vue")['default']>
  LazyStepSourceConfigure: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceConfigure.vue")['default']>
  LazyStepSourceType: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepSourceType.vue")['default']>
  LazyStepVisibility: LazyComponent<typeof import("../../app/components/studio/sidebar/add-source-steps/StepVisibility.vue")['default']>
  LazyAggregationSelect: LazyComponent<typeof import("../../app/components/studio/ui/AggregationSelect.vue")['default']>
  LazyColumnButton: LazyComponent<typeof import("../../app/components/studio/ui/ColumnButton.vue")['default']>
  LazyColumnInput: LazyComponent<typeof import("../../app/components/studio/ui/ColumnInput.vue")['default']>
  LazyColumnPickerModal: LazyComponent<typeof import("../../app/components/studio/ui/ColumnPickerModal.vue")['default']>
  LazyColumnsMappingModal: LazyComponent<typeof import("../../app/components/studio/ui/ColumnsMappingModal.vue")['default']>
  LazyDataSourceModal: LazyComponent<typeof import("../../app/components/studio/ui/DataSourceModal.vue")['default']>
  LazyDataSourcePickerModal: LazyComponent<typeof import("../../app/components/studio/ui/DataSourcePickerModal.vue")['default']>
  LazyEditorialContentModal: LazyComponent<typeof import("../../app/components/studio/ui/EditorialContentModal.vue")['default']>
  LazyFiltersModal: LazyComponent<typeof import("../../app/components/studio/ui/FiltersModal.vue")['default']>
  LazySearchResultsDisplayModal: LazyComponent<typeof import("../../app/components/studio/ui/SearchResultsDisplayModal.vue")['default']>
  LazyStudioModal: LazyComponent<typeof import("../../app/components/studio/ui/StudioModal.vue")['default']>
  LazyStudioSubModal: LazyComponent<typeof import("../../app/components/studio/ui/StudioSubModal.vue")['default']>
  LazyStudioWizardModal: LazyComponent<typeof import("../../app/components/studio/ui/StudioWizardModal.vue")['default']>
  LazyURLParamPickerModal: LazyComponent<typeof import("../../app/components/studio/ui/URLParamPickerModal.vue")['default']>
  LazyTvAudiencesEvolutionChart: LazyComponent<typeof import("../../app/components/tv/TvAudiencesEvolutionChart.vue")['default']>
  LazyTvAudiencesRankingTable: LazyComponent<typeof import("../../app/components/tv/TvAudiencesRankingTable.vue")['default']>
  LazyTvAudiencesTop50Table: LazyComponent<typeof import("../../app/components/tv/TvAudiencesTop50Table.vue")['default']>
  LazyTvBroadcastActionCard: LazyComponent<typeof import("../../app/components/tv/TvBroadcastActionCard.vue")['default']>
  LazyTvBroadcastAudienceCard: LazyComponent<typeof import("../../app/components/tv/TvBroadcastAudienceCard.vue")['default']>
  LazyTvBroadcastDiffusions: LazyComponent<typeof import("../../app/components/tv/TvBroadcastDiffusions.vue")['default']>
  LazyTvBroadcastHero: LazyComponent<typeof import("../../app/components/tv/TvBroadcastHero.vue")['default']>
  LazyTvBroadcastInfoCard: LazyComponent<typeof import("../../app/components/tv/TvBroadcastInfoCard.vue")['default']>
  LazyTvBroadcastReviews: LazyComponent<typeof import("../../app/components/tv/TvBroadcastReviews.vue")['default']>
  LazyTvBroadcastScores: LazyComponent<typeof import("../../app/components/tv/TvBroadcastScores.vue")['default']>
  LazyTvChannelBanner: LazyComponent<typeof import("../../app/components/tv/TvChannelBanner.vue")['default']>
  LazyTvChannelLogo: LazyComponent<typeof import("../../app/components/tv/TvChannelLogo.vue")['default']>
  LazyTvPopularProgrammeCard: LazyComponent<typeof import("../../app/components/tv/TvPopularProgrammeCard.vue")['default']>
  LazyTvProgrammeCard: LazyComponent<typeof import("../../app/components/tv/TvProgrammeCard.vue")['default']>
  LazyTvProgrammeCardIcon: LazyComponent<typeof import("../../app/components/tv/TvProgrammeCardIcon.vue")['default']>
  LazyTvReviewModal: LazyComponent<typeof import("../../app/components/tv/TvReviewModal.vue")['default']>
  LazyTvScheduleCardView: LazyComponent<typeof import("../../app/components/tv/TvScheduleCardView.vue")['default']>
  LazyTvScheduleChannelRow: LazyComponent<typeof import("../../app/components/tv/TvScheduleChannelRow.vue")['default']>
  LazyTvScheduleEmptyState: LazyComponent<typeof import("../../app/components/tv/TvScheduleEmptyState.vue")['default']>
  LazyTvScheduleFilters: LazyComponent<typeof import("../../app/components/tv/TvScheduleFilters.vue")['default']>
  LazyTvScheduleGrid: LazyComponent<typeof import("../../app/components/tv/TvScheduleGrid.vue")['default']>
  LazyTvScheduleNowNext: LazyComponent<typeof import("../../app/components/tv/TvScheduleNowNext.vue")['default']>
  LazyTvScheduleProgrammeBlock: LazyComponent<typeof import("../../app/components/tv/TvScheduleProgrammeBlock.vue")['default']>
  LazyTvScheduleTimeline: LazyComponent<typeof import("../../app/components/tv/TvScheduleTimeline.vue")['default']>
  LazyAppAvatar: LazyComponent<typeof import("../../app/components/ui/AppAvatar.vue")['default']>
  LazyAppBadge: LazyComponent<typeof import("../../app/components/ui/AppBadge.vue")['default']>
  LazyAppButton: LazyComponent<typeof import("../../app/components/ui/AppButton.vue")['default']>
  LazyAppCheckbox: LazyComponent<typeof import("../../app/components/ui/AppCheckbox.vue")['default']>
  LazyAppColorPickerModal: LazyComponent<typeof import("../../app/components/ui/AppColorPickerModal.vue")['default']>
  LazyAppLockedPanel: LazyComponent<typeof import("../../app/components/ui/AppLockedPanel.vue")['default']>
  LazyAppModal: LazyComponent<typeof import("../../app/components/ui/AppModal.vue")['default']>
  LazyAppPageSection: LazyComponent<typeof import("../../app/components/ui/AppPageSection.vue")['default']>
  LazyAppPagination: LazyComponent<typeof import("../../app/components/ui/AppPagination.vue")['default']>
  LazyAppRankingList: LazyComponent<typeof import("../../app/components/ui/AppRankingList.vue")['default']>
  LazyAppRelatedSlider: LazyComponent<typeof import("../../app/components/ui/AppRelatedSlider.vue")['default']>
  LazyAppSectionHeader: LazyComponent<typeof import("../../app/components/ui/AppSectionHeader.vue")['default']>
  LazyAppSectionTabs: LazyComponent<typeof import("../../app/components/ui/AppSectionTabs.vue")['default']>
  LazyAppSelect: LazyComponent<typeof import("../../app/components/ui/AppSelect.vue")['default']>
  LazyAppSidebarNavItem: LazyComponent<typeof import("../../app/components/ui/AppSidebarNavItem.vue")['default']>
  LazyAppSparkline: LazyComponent<typeof import("../../app/components/ui/AppSparkline.vue")['default']>
  LazyAppStatCard: LazyComponent<typeof import("../../app/components/ui/AppStatCard.vue")['default']>
  LazyAppStepModal: LazyComponent<typeof import("../../app/components/ui/AppStepModal.vue")['default']>
  LazyAppTooltip: LazyComponent<typeof import("../../app/components/ui/AppTooltip.vue")['default']>
  LazyAppTurnstile: LazyComponent<typeof import("../../app/components/ui/AppTurnstile.vue")['default']>
  LazyAppWordmark: LazyComponent<typeof import("../../app/components/ui/AppWordmark.vue")['default']>
  LazyAppWorldScatterMap: LazyComponent<typeof import("../../app/components/ui/AppWorldScatterMap.vue")['default']>
  LazyAccountAvatarUploader: LazyComponent<typeof import("../../app/components/user/AccountAvatarUploader.vue")['default']>
  LazyAccountContentThumb: LazyComponent<typeof import("../../app/components/user/AccountContentThumb.vue")['default']>
  LazyAccountDangerZone: LazyComponent<typeof import("../../app/components/user/AccountDangerZone.vue")['default']>
  LazyAccountDemographicsCard: LazyComponent<typeof import("../../app/components/user/AccountDemographicsCard.vue")['default']>
  LazyAccountNotificationsCard: LazyComponent<typeof import("../../app/components/user/AccountNotificationsCard.vue")['default']>
  LazyAccountPageHeader: LazyComponent<typeof import("../../app/components/user/AccountPageHeader.vue")['default']>
  LazyAccountProfileCard: LazyComponent<typeof import("../../app/components/user/AccountProfileCard.vue")['default']>
  LazyAccountSearch: LazyComponent<typeof import("../../app/components/user/AccountSearch.vue")['default']>
  LazyAccountSidebar: LazyComponent<typeof import("../../app/components/user/AccountSidebar.vue")['default']>
  LazyAccountToggle: LazyComponent<typeof import("../../app/components/user/AccountToggle.vue")['default']>
  LazyAccountTopbar: LazyComponent<typeof import("../../app/components/user/AccountTopbar.vue")['default']>
  LazyFavoriteCard: LazyComponent<typeof import("../../app/components/user/FavoriteCard.vue")['default']>
  LazySubscriptionRow: LazyComponent<typeof import("../../app/components/user/SubscriptionRow.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
