// Generated by auto imports
export {}
declare global {
  const $fetch: typeof import('../fetch.mjs').$fetch
  const ADD_SOURCE_WIZARD_STEPS: typeof import('../../app/composables/useAddSourceWizard').ADD_SOURCE_WIZARD_STEPS
  const CHANNEL_BADGE_LABELS: typeof import('../../app/api/channels').CHANNEL_BADGE_LABELS
  const CHANNEL_CHART_COLORS: typeof import('../../app/composables/useTvAudiences').CHANNEL_CHART_COLORS
  const CONTENT_TYPE_FILTER_OPTIONS: typeof import('../../app/composables/useChannelContents').CONTENT_TYPE_FILTER_OPTIONS
  const CONTENT_WIZARD_STEPS: typeof import('../../app/composables/useCreateContentWizard').CONTENT_WIZARD_STEPS
  const DATAGOUV_TABULAR_API_BASE: typeof import('../../app/composables/useAddSourceWizard').DATAGOUV_TABULAR_API_BASE
  const EDIT_SOURCE_WIZARD_STEPS: typeof import('../../app/composables/useEditSourceWizard').EDIT_SOURCE_WIZARD_STEPS
  const INVITABLE_ROLES: typeof import('../../app/api/channels').INVITABLE_ROLES
  const OWNER_FILTER_OPTIONS: typeof import('../../app/composables/useMyStudioContents').OWNER_FILTER_OPTIONS
  const PALETTE: typeof import('../../app/composables/useChart').PALETTE
  const POPULAR_MEDICAMENTS: typeof import('../../app/composables/useMedicaments').POPULAR_MEDICAMENTS
  const STATSIO_API: typeof import('../../app/api/statsio-endpoints').STATSIO_API
  const STUDIO_EMBED_CONTEXT: typeof import('../../app/composables/studioEmbedContext').STUDIO_EMBED_CONTEXT
  const abortNavigation: typeof import('../../node_modules/nuxt/dist/app/composables/router').abortNavigation
  const acceptChannelInvitation: typeof import('../../app/api/channels').acceptChannelInvitation
  const acceptHMRUpdate: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').acceptHMRUpdate
  const addRouteMiddleware: typeof import('../../node_modules/nuxt/dist/app/composables/router').addRouteMiddleware
  const anonymizeAccount: typeof import('../../app/api/statsio-user').anonymizeAccount
  const apiFormAuthHeaders: typeof import('../../app/composables/useAddSourceWizard').apiFormAuthHeaders
  const callOnce: typeof import('../../node_modules/nuxt/dist/app/composables/once').callOnce
  const cancelIdleCallback: typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback').cancelIdleCallback
  const channelCategoryLabels: typeof import('../../app/api/channels').channelCategoryLabels
  const channelRoleLabels: typeof import('../../app/api/channels').channelRoleLabels
  const checkHandleAvailability: typeof import('../../app/api/channels-validation').checkHandleAvailability
  const clearAggregateCache: typeof import('../../app/composables/useResolvedTokens').clearAggregateCache
  const clearError: typeof import('../../node_modules/nuxt/dist/app/composables/error').clearError
  const clearHistory: typeof import('../../app/api/statsio-account').clearHistory
  const clearNuxtData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').clearNuxtData
  const clearNuxtState: typeof import('../../node_modules/nuxt/dist/app/composables/state').clearNuxtState
  const computed: typeof import('vue').computed
  const createAgentConversation: typeof import('../../app/api/ai').createAgentConversation
  const createApiDataSource: typeof import('../../app/api/data-sources').createApiDataSource
  const createChannel: typeof import('../../app/api/channels').createChannel
  const createError: typeof import('../../node_modules/nuxt/dist/app/composables/error').createError
  const createOrganization: typeof import('../../app/api/channels').createOrganization
  const createStudioContent: typeof import('../../app/api/studio').createStudioContent
  const createUseAsyncData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').createUseAsyncData
  const createUseFetch: typeof import('../../node_modules/nuxt/dist/app/composables/fetch').createUseFetch
  const customRef: typeof import('vue').customRef
  const datagouvTabularUrl: typeof import('../../app/composables/useAddSourceWizard').datagouvTabularUrl
  const defaultPagination: typeof import('../../app/composables/useAddSourceWizard').defaultPagination
  const defineAppConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineLazyHydrationComponent: typeof import('../../node_modules/nuxt/dist/app/composables/lazy-hydration').defineLazyHydrationComponent
  const defineNuxtComponent: typeof import('../../node_modules/nuxt/dist/app/composables/component').defineNuxtComponent
  const defineNuxtLink: typeof import('../../node_modules/nuxt/dist/app/components/nuxt-link').defineNuxtLink
  const defineNuxtPlugin: typeof import('../../node_modules/nuxt/dist/app/nuxt').defineNuxtPlugin
  const defineNuxtRouteMiddleware: typeof import('../../node_modules/nuxt/dist/app/composables/router').defineNuxtRouteMiddleware
  const definePageMeta: typeof import('../../node_modules/nuxt/dist/app/composables/pages').definePageMeta
  const definePayloadPlugin: typeof import('../../node_modules/nuxt/dist/app/nuxt').definePayloadPlugin
  const definePayloadReducer: typeof import('../../node_modules/nuxt/dist/app/composables/payload').definePayloadReducer
  const definePayloadReviver: typeof import('../../node_modules/nuxt/dist/app/composables/payload').definePayloadReviver
  const defineStore: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').defineStore
  const deleteAgentConversation: typeof import('../../app/api/ai').deleteAgentConversation
  const deleteAvatar: typeof import('../../app/api/statsio-account').deleteAvatar
  const deleteChannel: typeof import('../../app/api/channels').deleteChannel
  const deleteDataset: typeof import('../../app/api/studio').deleteDataset
  const deleteStatsDataDocument: typeof import('../../app/api/studio').deleteStatsDataDocument
  const detectApiStructure: typeof import('../../app/api/data-sources').detectApiStructure
  const effect: typeof import('vue').effect
  const effectScope: typeof import('vue').effectScope
  const extractMedicamentBrandName: typeof import('../../app/utils/medicaments').extractMedicamentBrandName
  const fetchAgentConversation: typeof import('../../app/api/ai').fetchAgentConversation
  const fetchAgentRun: typeof import('../../app/api/ai').fetchAgentRun
  const fetchBlockData: typeof import('../../app/api/studio').fetchBlockData
  const fetchBlockResponse: typeof import('../../app/api/studio-responses').fetchBlockResponse
  const fetchBroadcast: typeof import('../../app/api/tv-broadcast').fetchBroadcast
  const fetchBroadcastReviews: typeof import('../../app/api/tv-broadcast').fetchBroadcastReviews
  const fetchChannelCatalog: typeof import('../../app/api/channels').fetchChannelCatalog
  const fetchChannelDetail: typeof import('../../app/api/tv-channel').fetchChannelDetail
  const fetchChannelPopularProgrammes: typeof import('../../app/api/tv-channel').fetchChannelPopularProgrammes
  const fetchChannelSchedules: typeof import('../../app/api/tv-schedule').fetchChannelSchedules
  const fetchContentCategories: typeof import('../../app/api/content-categories').fetchContentCategories
  const fetchContentDataSources: typeof import('../../app/api/studio').fetchContentDataSources
  const fetchContentMentions: typeof import('../../app/api/studio').fetchContentMentions
  const fetchDataSource: typeof import('../../app/api/data-sources').fetchDataSource
  const fetchDatasetPreview: typeof import('../../app/api/studio').fetchDatasetPreview
  const fetchDatasetSchema: typeof import('../../app/api/studio').fetchDatasetSchema
  const fetchDatasets: typeof import('../../app/api/studio').fetchDatasets
  const fetchDistinctValues: typeof import('../../app/api/studio').fetchDistinctValues
  const fetchFavorites: typeof import('../../app/api/statsio-account').fetchFavorites
  const fetchHistory: typeof import('../../app/api/statsio-account').fetchHistory
  const fetchIdentityStatus: typeof import('../../app/api/identity').fetchIdentityStatus
  const fetchInProgress: typeof import('../../app/api/statsio-account').fetchInProgress
  const fetchMaladieDetail: typeof import('../../app/api/maladies').fetchMaladieDetail
  const fetchMaladiesPopulaires: typeof import('../../app/api/maladies').fetchMaladiesPopulaires
  const fetchMaladiesSearch: typeof import('../../app/api/maladies').fetchMaladiesSearch
  const fetchMedicamentDetail: typeof import('../../app/api/medicaments').fetchMedicamentDetail
  const fetchMedicamentGeneriques: typeof import('../../app/api/medicaments').fetchMedicamentGeneriques
  const fetchMedicamentImage: typeof import('../../app/api/medicaments').fetchMedicamentImage
  const fetchMedicamentVentes: typeof import('../../app/api/medicaments').fetchMedicamentVentes
  const fetchMedicamentsSearch: typeof import('../../app/api/medicaments').fetchMedicamentsSearch
  const fetchMedicamentsTopVentes: typeof import('../../app/api/medicaments').fetchMedicamentsTopVentes
  const fetchPaysDetail: typeof import('../../app/api/pays').fetchPaysDetail
  const fetchPaysList: typeof import('../../app/api/pays').fetchPaysList
  const fetchProfileReferenceData: typeof import('../../app/api/statsio-user').fetchProfileReferenceData
  const fetchProgrammeSchedule: typeof import('../../app/api/tv-broadcast').fetchProgrammeSchedule
  const fetchPublicArticles: typeof import('../../app/api/studio').fetchPublicArticles
  const fetchPublicBlockData: typeof import('../../app/api/studio').fetchPublicBlockData
  const fetchPublicCatalog: typeof import('../../app/api/studio').fetchPublicCatalog
  const fetchPublicDistinctValues: typeof import('../../app/api/studio').fetchPublicDistinctValues
  const fetchPublicScalarAggregate: typeof import('../../app/api/studio').fetchPublicScalarAggregate
  const fetchPublicSearchRows: typeof import('../../app/api/studio').fetchPublicSearchRows
  const fetchPublicStatsDataBlock: typeof import('../../app/api/studio').fetchPublicStatsDataBlock
  const fetchPublicStatsDataCatalog: typeof import('../../app/api/studio').fetchPublicStatsDataCatalog
  const fetchPublicStatsDataDocument: typeof import('../../app/api/studio').fetchPublicStatsDataDocument
  const fetchPublicSurveys: typeof import('../../app/api/studio').fetchPublicSurveys
  const fetchReviewQuestions: typeof import('../../app/api/tv-broadcast').fetchReviewQuestions
  const fetchScalarAggregate: typeof import('../../app/api/studio').fetchScalarAggregate
  const fetchSearchRows: typeof import('../../app/api/studio').fetchSearchRows
  const fetchSoinsList: typeof import('../../app/api/soins').fetchSoinsList
  const fetchSourceProvenances: typeof import('../../app/api/source-provenances').fetchSourceProvenances
  const fetchStatsDataDocument: typeof import('../../app/api/studio').fetchStatsDataDocument
  const fetchStatsDataEmbeddableBlocks: typeof import('../../app/api/studio').fetchStatsDataEmbeddableBlocks
  const fetchStatsioAuthMe: typeof import('../../app/api/statsio-user').fetchStatsioAuthMe
  const fetchStatsioMe: typeof import('../../app/api/statsio-user').fetchStatsioMe
  const fetchSubscriptions: typeof import('../../app/api/statsio-account').fetchSubscriptions
  const fetchTvAudiences: typeof import('../../app/api/tv-audiences').fetchTvAudiences
  const fetchUserStudioContents: typeof import('../../app/api/studio').fetchUserStudioContents
  const fmtRelative: typeof import('../../app/composables/useBroadcastDetail').fmtRelative
  const fmtScheduleDate: typeof import('../../app/composables/useBroadcastDetail').fmtScheduleDate
  const formatCompactNumber: typeof import('../../app/utils/number').formatCompactNumber
  const formatDisplayValue: typeof import('../../app/utils/statsDataFormat').formatDisplayValue
  const formatRowCount: typeof import('../../app/utils/statsDataFormat').formatRowCount
  const formatStatsDataDate: typeof import('../../app/utils/statsDataFormat').formatStatsDataDate
  const getAppManifest: typeof import('../../node_modules/nuxt/dist/app/composables/manifest').getAppManifest
  const getChannel: typeof import('../../app/api/channels').getChannel
  const getChannelCategories: typeof import('../../app/api/channels').getChannelCategories
  const getChannelDataSources: typeof import('../../app/api/channels').getChannelDataSources
  const getChannelInvitations: typeof import('../../app/api/channels').getChannelInvitations
  const getChannelMembers: typeof import('../../app/api/channels').getChannelMembers
  const getChannelPermissionsCatalog: typeof import('../../app/api/channels').getChannelPermissionsCatalog
  const getChannelStats: typeof import('../../app/api/channels').getChannelStats
  const getChannelSubscribers: typeof import('../../app/api/channels').getChannelSubscribers
  const getChannels: typeof import('../../app/api/channels').getChannels
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getInvitationByToken: typeof import('../../app/api/channels').getInvitationByToken
  const getJoinableOrganizations: typeof import('../../app/api/channels').getJoinableOrganizations
  const getMedicamentFormEmoji: typeof import('../../app/utils/medicaments').getMedicamentFormEmoji
  const getMyChannels: typeof import('../../app/api/channels').getMyChannels
  const getPublicChannels: typeof import('../../app/api/channels').getPublicChannels
  const getRouteRules: typeof import('../../node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const getStatsDataPalette: typeof import('../../app/utils/statsDataVisuals').getStatsDataPalette
  const getStatsDataVisual: typeof import('../../app/utils/statsDataVisuals').getStatsDataVisual
  const h: typeof import('vue').h
  const hasInjectionContext: typeof import('vue').hasInjectionContext
  const inject: typeof import('vue').inject
  const injectHead: typeof import('../../node_modules/nuxt/dist/app/composables/head').injectHead
  const invalidateDbChannelCache: typeof import('../../app/api/tv-schedule').invalidateDbChannelCache
  const inviteChannelMembers: typeof import('../../app/api/channels').inviteChannelMembers
  const isNuxtError: typeof import('../../node_modules/nuxt/dist/app/composables/error').isNuxtError
  const isPrerendered: typeof import('../../node_modules/nuxt/dist/app/composables/payload').isPrerendered
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isVue2: typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi').isVue2
  const isVue3: typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi').isVue3
  const isoToFlagEmoji: typeof import('../../app/utils/flag').isoToFlagEmoji
  const joinOrganization: typeof import('../../app/api/channels').joinOrganization
  const leaveOrganization: typeof import('../../app/api/channels').leaveOrganization
  const listAgentConversations: typeof import('../../app/api/ai').listAgentConversations
  const loadArticleMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadArticleMenu
  const loadAudiencesMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadAudiencesMenu
  const loadChannelsMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadChannelsMenu
  const loadMaladiesMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadMaladiesMenu
  const loadMedicamentsMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadMedicamentsMenu
  const loadPayload: typeof import('../../node_modules/nuxt/dist/app/composables/payload').loadPayload
  const loadProgrammeTvMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadProgrammeTvMenu
  const loadPromoTicker: typeof import('../../app/composables/useHeaderMegaMenuData').loadPromoTicker
  const loadSoinsMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadSoinsMenu
  const loadStatsDataMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadStatsDataMenu
  const loadSurveyMenu: typeof import('../../app/composables/useHeaderMegaMenuData').loadSurveyMenu
  const mapPaginationToApi: typeof import('../../app/api/data-sources').mapPaginationToApi
  const mapQueryMappingToApi: typeof import('../../app/api/data-sources').mapQueryMappingToApi
  const markRaw: typeof import('vue').markRaw
  const navigateTo: typeof import('../../node_modules/nuxt/dist/app/composables/router').navigateTo
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('../../node_modules/vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('../../node_modules/vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onNuxtReady: typeof import('../../node_modules/nuxt/dist/app/composables/ready').onNuxtReady
  const onPrehydrate: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').onPrehydrate
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseDatagouvResourceId: typeof import('../../app/composables/useAddSourceWizard').parseDatagouvResourceId
  const parseNumericValue: typeof import('../../app/utils/statsDataFormat').parseNumericValue
  const prefetchComponents: typeof import('../../node_modules/nuxt/dist/app/composables/preload').prefetchComponents
  const preloadComponents: typeof import('../../node_modules/nuxt/dist/app/composables/preload').preloadComponents
  const preloadPayload: typeof import('../../node_modules/nuxt/dist/app/composables/payload').preloadPayload
  const preloadRouteComponents: typeof import('../../node_modules/nuxt/dist/app/composables/preload').preloadRouteComponents
  const prerenderRoutes: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').prerenderRoutes
  const previewSpreadsheet: typeof import('../../app/api/data-sources').previewSpreadsheet
  const provide: typeof import('vue').provide
  const proxyRefs: typeof import('vue').proxyRefs
  const publishStatsDataDocument: typeof import('../../app/api/studio').publishStatsDataDocument
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const recordContentView: typeof import('../../app/api/statsio-account').recordContentView
  const ref: typeof import('vue').ref
  const refreshCookie: typeof import('../../node_modules/nuxt/dist/app/composables/cookie').refreshCookie
  const refreshDataSource: typeof import('../../app/api/data-sources').refreshDataSource
  const refreshNuxtData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').refreshNuxtData
  const relativeUpdate: typeof import('../../app/utils/statsDataFormat').relativeUpdate
  const reloadNuxtApp: typeof import('../../node_modules/nuxt/dist/app/composables/chunk').reloadNuxtApp
  const removeFavorite: typeof import('../../app/api/statsio-account').removeFavorite
  const requestIdleCallback: typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback').requestIdleCallback
  const resolveAggregationParams: typeof import('../../app/composables/useBlockData').resolveAggregationParams
  const resolveComponent: typeof import('vue').resolveComponent
  const revokeChannelInvitation: typeof import('../../app/api/channels').revokeChannelInvitation
  const saveStatsDataDocument: typeof import('../../app/api/studio').saveStatsDataDocument
  const searchAccount: typeof import('../../app/api/statsio-account').searchAccount
  const seededSparklinePoints: typeof import('../../app/utils/statsDataVisuals').seededSparklinePoints
  const sendAgentMessage: typeof import('../../app/api/ai').sendAgentMessage
  const setInterval: typeof import('../../node_modules/nuxt/dist/app/compat/interval').setInterval
  const setPageLayout: typeof import('../../node_modules/nuxt/dist/app/composables/router').setPageLayout
  const setResponseStatus: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const setStatsDataDocumentStatus: typeof import('../../app/api/studio').setStatsDataDocumentStatus
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showError: typeof import('../../node_modules/nuxt/dist/app/composables/error').showError
  const startIdentityVerification: typeof import('../../app/api/identity').startIdentityVerification
  const storeToRefs: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').storeToRefs
  const submitBlockResponse: typeof import('../../app/api/studio-responses').submitBlockResponse
  const submitBroadcastReview: typeof import('../../app/api/tv-broadcast').submitBroadcastReview
  const submitContactMessage: typeof import('../../app/api/contact').submitContactMessage
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toggleBroadcastView: typeof import('../../app/api/tv-broadcast').toggleBroadcastView
  const toggleChannelFollow: typeof import('../../app/api/tv-channel').toggleChannelFollow
  const toggleChannelSubscription: typeof import('../../app/api/channels').toggleChannelSubscription
  const toggleFavorite: typeof import('../../app/api/statsio-account').toggleFavorite
  const triggerRef: typeof import('vue').triggerRef
  const tryUseNuxtApp: typeof import('../../node_modules/nuxt/dist/app/nuxt').tryUseNuxtApp
  const unref: typeof import('vue').unref
  const updateAppConfig: typeof import('../../node_modules/nuxt/dist/app/config').updateAppConfig
  const updateChannel: typeof import('../../app/api/channels').updateChannel
  const updateChannelMedia: typeof import('../../app/api/channels').updateChannelMedia
  const updateChannelProfile: typeof import('../../app/api/channels').updateChannelProfile
  const updateDataSource: typeof import('../../app/api/data-sources').updateDataSource
  const updateDataset: typeof import('../../app/api/studio').updateDataset
  const updateProfile: typeof import('../../app/api/statsio-user').updateProfile
  const uploadAvatar: typeof import('../../app/api/statsio-account').uploadAvatar
  const useAccountFavorites: typeof import('../../app/composables/useAccountFavorites').useAccountFavorites
  const useAccountHistory: typeof import('../../app/composables/useAccountHistory').useAccountHistory
  const useAccountOverview: typeof import('../../app/composables/useAccountOverview').useAccountOverview
  const useAccountSearch: typeof import('../../app/composables/useAccountSearch').useAccountSearch
  const useAccountSubscriptions: typeof import('../../app/composables/useAccountSubscriptions').useAccountSubscriptions
  const useActiveEditor: typeof import('../../app/composables/useActiveEditor').useActiveEditor
  const useAddSourceWizard: typeof import('../../app/composables/useAddSourceWizard').useAddSourceWizard
  const useAggregateValues: typeof import('../../app/composables/useResolvedTokens').useAggregateValues
  const useAnnouncer: typeof import('../../node_modules/nuxt/dist/app/composables/announcer').useAnnouncer
  const useApiStructureDetection: typeof import('../../app/composables/useAddSourceWizard').useApiStructureDetection
  const useAppConfig: typeof import('../../node_modules/nuxt/dist/app/config').useAppConfig
  const useAppNotifications: typeof import('../../app/composables/useAppNotifications').useAppNotifications
  const useAppNotificationsStore: typeof import('../../app/stores/app-notifications').useAppNotificationsStore
  const useAsyncData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').useAsyncData
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('../../app/stores/auth').useAuthStore
  const useBlockData: typeof import('../../app/composables/useBlockData').useBlockData
  const useBroadcastDetail: typeof import('../../app/composables/useBroadcastDetail').useBroadcastDetail
  const useChannelContents: typeof import('../../app/composables/useChannelContents').useChannelContents
  const useChannelDashboard: typeof import('../../app/composables/useChannelDashboard').useChannelDashboard
  const useChannelDataSources: typeof import('../../app/composables/useChannelDataSources').useChannelDataSources
  const useChannelDetail: typeof import('../../app/composables/useChannelDetail').useChannelDetail
  const useChannelProfile: typeof import('../../app/composables/useChannelProfile').useChannelProfile
  const useChannelPublicContent: typeof import('../../app/composables/useChannelPublicContent').useChannelPublicContent
  const useChannelStats: typeof import('../../app/composables/useChannelStats').useChannelStats
  const useChannelsCatalog: typeof import('../../app/composables/useChannelsCatalog').useChannelsCatalog
  const useChart: typeof import('../../app/composables/useChart').useChart
  const useClickOutside: typeof import('../../app/composables/useClickOutside').useClickOutside
  const useContentBasePath: typeof import('../../app/composables/useContentBasePath').useContentBasePath
  const useContentDashboard: typeof import('../../app/composables/useContentDashboard').useContentDashboard
  const useContentDataSources: typeof import('../../app/composables/useContentDataSources').useContentDataSources
  const useContextStore: typeof import('../../app/stores/context').useContextStore
  const useCookie: typeof import('../../node_modules/nuxt/dist/app/composables/cookie').useCookie
  const useCookieBanner: typeof import('../../app/composables/useCookieBanner').useCookieBanner
  const useCreateContentWizard: typeof import('../../app/composables/useCreateContentWizard').useCreateContentWizard
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useEditSourceWizard: typeof import('../../app/composables/useEditSourceWizard').useEditSourceWizard
  const useError: typeof import('../../node_modules/nuxt/dist/app/composables/error').useError
  const useExpressionNumber: typeof import('../../app/composables/useResolvedTokens').useExpressionNumber
  const useFavicon: typeof import('../../app/composables/useFavicon').useFavicon
  const useFetch: typeof import('../../node_modules/nuxt/dist/app/composables/fetch').useFetch
  const useFormBlockResponse: typeof import('../../app/composables/useFormBlockResponse').useFormBlockResponse
  const useHead: typeof import('../../node_modules/nuxt/dist/app/composables/head').useHead
  const useHeadSafe: typeof import('../../node_modules/nuxt/dist/app/composables/head').useHeadSafe
  const useHomeCatalogSection: typeof import('../../app/composables/useHomeCatalogSection').useHomeCatalogSection
  const useHydration: typeof import('../../node_modules/nuxt/dist/app/composables/hydrate').useHydration
  const useId: typeof import('vue').useId
  const useLayout: typeof import('../../node_modules/nuxt/dist/app/composables/layout').useLayout
  const useLazyAsyncData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').useLazyAsyncData
  const useLazyFetch: typeof import('../../node_modules/nuxt/dist/app/composables/fetch').useLazyFetch
  const useLink: typeof import('../../node_modules/vue-router').useLink
  const useLoadingIndicator: typeof import('../../node_modules/nuxt/dist/app/composables/loading-indicator').useLoadingIndicator
  const useMaladies: typeof import('../../app/composables/useMaladies').useMaladies
  const useMedicamentImage: typeof import('../../app/composables/useMedicamentImage').useMedicamentImage
  const useMedicaments: typeof import('../../app/composables/useMedicaments').useMedicaments
  const useModalA11y: typeof import('../../app/composables/useModalA11y').useModalA11y
  const useModel: typeof import('vue').useModel
  const useMyChannels: typeof import('../../app/composables/useMyChannels').useMyChannels
  const useMyStudioContents: typeof import('../../app/composables/useMyStudioContents').useMyStudioContents
  const useNowNext: typeof import('../../app/composables/useNowNext').useNowNext
  const useNuxtApp: typeof import('../../node_modules/nuxt/dist/app/nuxt').useNuxtApp
  const useNuxtData: typeof import('../../node_modules/nuxt/dist/app/composables/asyncData').useNuxtData
  const useNuxtDevTools: typeof import('../../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools').useNuxtDevTools
  const usePageSeo: typeof import('../../app/composables/usePageSeo').usePageSeo
  const usePays: typeof import('../../app/composables/usePays').usePays
  const usePinia: typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables').usePinia
  const usePrefsStore: typeof import('../../app/stores/prefs').usePrefsStore
  const usePreviewMode: typeof import('../../node_modules/nuxt/dist/app/composables/preview').usePreviewMode
  const usePublicCatalog: typeof import('../../app/composables/usePublicCatalog').usePublicCatalog
  const useRequestEvent: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestEvent
  const useRequestFetch: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestFetch
  const useRequestHeader: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestHeader
  const useRequestHeaders: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useRequestHeaders
  const useRequestURL: typeof import('../../node_modules/nuxt/dist/app/composables/url').useRequestURL
  const useResolvedTokenList: typeof import('../../app/composables/useResolvedTokens').useResolvedTokenList
  const useResolvedTokens: typeof import('../../app/composables/useResolvedTokens').useResolvedTokens
  const useRespondentToken: typeof import('../../app/composables/useRespondentToken').useRespondentToken
  const useResponseHeader: typeof import('../../node_modules/nuxt/dist/app/composables/ssr').useResponseHeader
  const useRoute: typeof import('../../node_modules/nuxt/dist/app/composables/router').useRoute
  const useRouteAnnouncer: typeof import('../../node_modules/nuxt/dist/app/composables/route-announcer').useRouteAnnouncer
  const useRouter: typeof import('../../node_modules/nuxt/dist/app/composables/router').useRouter
  const useRuntimeConfig: typeof import('../../node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
  const useRuntimeHook: typeof import('../../node_modules/nuxt/dist/app/composables/runtime-hook').useRuntimeHook
  const useScript: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScript
  const useScriptAhrefsAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptAhrefsAnalytics
  const useScriptBingUet: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptBingUet
  const useScriptCalendly: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptCalendly
  const useScriptClarity: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptClarity
  const useScriptCloudflareWebAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptCloudflareWebAnalytics
  const useScriptCrisp: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptCrisp
  const useScriptDatabuddyAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptDatabuddyAnalytics
  const useScriptEventPage: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptEventPage
  const useScriptFathomAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptFathomAnalytics
  const useScriptGoogleAdsense: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleAdsense
  const useScriptGoogleAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleAnalytics
  const useScriptGoogleMaps: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleMaps
  const useScriptGoogleRecaptcha: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleRecaptcha
  const useScriptGoogleSignIn: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleSignIn
  const useScriptGoogleTagManager: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGoogleTagManager
  const useScriptGravatar: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptGravatar
  const useScriptHotjar: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptHotjar
  const useScriptIntercom: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptIntercom
  const useScriptLemonSqueezy: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptLemonSqueezy
  const useScriptLinkedInInsight: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptLinkedInInsight
  const useScriptMatomoAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptMatomoAnalytics
  const useScriptMetaPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptMetaPixel
  const useScriptMixpanelAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptMixpanelAnalytics
  const useScriptNpm: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptNpm
  const useScriptPayPal: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptPayPal
  const useScriptPlausibleAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptPlausibleAnalytics
  const useScriptPostHog: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptPostHog
  const useScriptRedditPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptRedditPixel
  const useScriptRybbitAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptRybbitAnalytics
  const useScriptSegment: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptSegment
  const useScriptSnapchatPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptSnapchatPixel
  const useScriptSpeedCurve: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptSpeedCurve
  const useScriptStripe: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptStripe
  const useScriptTikTokPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptTikTokPixel
  const useScriptTriggerConsent: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptTriggerConsent
  const useScriptTriggerElement: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptTriggerElement
  const useScriptUmamiAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptUmamiAnalytics
  const useScriptUsercentrics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptUsercentrics
  const useScriptVercelAnalytics: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptVercelAnalytics
  const useScriptVimeoPlayer: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptVimeoPlayer
  const useScriptXPixel: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptXPixel
  const useScriptYouTubePlayer: typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs').useScriptYouTubePlayer
  const useScrollAnim: typeof import('../../app/composables/useScrollAnim').useScrollAnim
  const useSeoMeta: typeof import('../../node_modules/nuxt/dist/app/composables/head').useSeoMeta
  const useServerHead: typeof import('../../node_modules/nuxt/dist/app/composables/head').useServerHead
  const useServerHeadSafe: typeof import('../../node_modules/nuxt/dist/app/composables/head').useServerHeadSafe
  const useServerSeoMeta: typeof import('../../node_modules/nuxt/dist/app/composables/head').useServerSeoMeta
  const useShadowRoot: typeof import('vue').useShadowRoot
  const useSimilarChannels: typeof import('../../app/composables/useSimilarChannels').useSimilarChannels
  const useSlots: typeof import('vue').useSlots
  const useSoins: typeof import('../../app/composables/useSoins').useSoins
  const useState: typeof import('../../node_modules/nuxt/dist/app/composables/state').useState
  const useStatsDataChrome: typeof import('../../app/composables/useStatsDataChrome').useStatsDataChrome
  const useStatsDataDetail: typeof import('../../app/composables/useStatsDataDetail').useStatsDataDetail
  const useStudioAgentStore: typeof import('../../app/stores/studio-agent').useStudioAgentStore
  const useStudioAutosave: typeof import('../../app/composables/useStudioAutosave').useStudioAutosave
  const useStudioDatasetsStore: typeof import('../../app/stores/studio-datasets').useStudioDatasetsStore
  const useStudioStore: typeof import('../../app/stores/studio').useStudioStore
  const useStudioVariables: typeof import('../../app/composables/useStudioVariables').useStudioVariables
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTransitionState: typeof import('vue').useTransitionState
  const useTvAudiences: typeof import('../../app/composables/useTvAudiences').useTvAudiences
  const useTvSchedule: typeof import('../../app/composables/useTvSchedule').useTvSchedule
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const withCtx: typeof import('vue').withCtx
  const withDirectives: typeof import('vue').withDirectives
  const withKeys: typeof import('vue').withKeys
  const withMemo: typeof import('vue').withMemo
  const withModifiers: typeof import('vue').withModifiers
  const withScopeId: typeof import('vue').withScopeId
  const wizardStepsFor: typeof import('../../app/composables/useCreateContentWizard').wizardStepsFor
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { PageMeta } from '../../node_modules/nuxt/dist/app/composables/pages'
  import('../../node_modules/nuxt/dist/app/composables/pages')
  // @ts-ignore
  export type { StudioEmbedContext } from '../../app/composables/studioEmbedContext'
  import('../../app/composables/studioEmbedContext')
  // @ts-ignore
  export type { SourceType, AuthType, HttpMethod, ApiFormPagination, ProvenanceSelection, ApiFormShape } from '../../app/composables/useAddSourceWizard'
  import('../../app/composables/useAddSourceWizard')
  // @ts-ignore
  export type { BlockDataOverrides } from '../../app/composables/useBlockData'
  import('../../app/composables/useBlockData')
  // @ts-ignore
  export type { ContentTypeFilter } from '../../app/composables/useChannelContents'
  import('../../app/composables/useChannelContents')
  // @ts-ignore
  export type { ChannelTab } from '../../app/composables/useChannelDetail'
  import('../../app/composables/useChannelDetail')
  // @ts-ignore
  export type { ChannelProfileTab } from '../../app/composables/useChannelProfile'
  import('../../app/composables/useChannelProfile')
  // @ts-ignore
  export type { HeaderMenuData } from '../../app/composables/useHeaderMegaMenuData'
  import('../../app/composables/useHeaderMegaMenuData')
  // @ts-ignore
  export type { OwnerFilter, DisplayContent } from '../../app/composables/useMyStudioContents'
  import('../../app/composables/useMyStudioContents')
  // @ts-ignore
  export type { NowNext } from '../../app/composables/useNowNext'
  import('../../app/composables/useNowNext')
  // @ts-ignore
  export type { PageSeoOgType, PageSeoOptions } from '../../app/composables/usePageSeo'
  import('../../app/composables/usePageSeo')
  // @ts-ignore
  export type { VariableItem, VariableGroup } from '../../app/composables/useStudioVariables'
  import('../../app/composables/useStudioVariables')
  // @ts-ignore
  export type { YearDataWithChannel } from '../../app/composables/useTvAudiences'
  import('../../app/composables/useTvAudiences')
  // @ts-ignore
  export type { StatsDataVisual } from '../../app/utils/statsDataVisuals'
  import('../../app/utils/statsDataVisuals')
  // @ts-ignore
  export type { ContextState } from '../../app/stores/context'
  import('../../app/stores/context')
  // @ts-ignore
  export type { AgentStatus, AgentChatMessage } from '../../app/stores/studio-agent'
  import('../../app/stores/studio-agent')
  // @ts-ignore
  export type { AgentRunStatus, AgentPatchOp, AgentRun, AgentMessage, AgentConversation, AgentConversationSummary } from '../../app/api/ai'
  import('../../app/api/ai')
  // @ts-ignore
  export type { ChannelKind, ChannelCategory, CreateChannelPayload, ChannelProfile, ChannelOrganization, Channel, ChannelCategoryItem, ChannelSort, ChannelsListParams, PaginatedChannels, ChannelStats, ChannelDataSourceUsage, ChannelDataSource, ToggleSubscriptionResponse, ChannelRole, ChannelPermission, ChannelPermissionCategory, ChannelMember, ChannelInvitation, ChannelSubscriber, UpdateChannelPayload, InviteChannelMembersPayload, InviteChannelMembersResult, InvitationDetails } from '../../app/api/channels'
  import('../../app/api/channels')
  // @ts-ignore
  export type { ContactReason, ContactMessagePayload } from '../../app/api/contact'
  import('../../app/api/contact')
  // @ts-ignore
  export type { RefreshFrequency, PaginationStyle, Materialization, QueryMappingFilter, QueryMapping, SemanticRole, DetectedSchemaColumn, ChartType, SourceCapabilities, DataSourcePagination, DataSourceApiConfig, DataSourceDetail, DetectStructureResult, SpreadsheetPreview, UpdateDataSourcePayload } from '../../app/api/data-sources'
  import('../../app/api/data-sources')
  // @ts-ignore
  export type { IdentityStatus, IdentityStartResult } from '../../app/api/identity'
  import('../../app/api/identity')
  // @ts-ignore
  export type { SourceProvenance } from '../../app/api/source-provenances'
  import('../../app/api/source-provenances')
  // @ts-ignore
  export type { ProfileReferenceData, UpdateProfilePayload } from '../../app/api/statsio-user'
  import('../../app/api/statsio-user')
  // @ts-ignore
  export type { FormAnswerValue, BlockResponseOption, DemographicBucket, ResponseDemographics, BlockResponseAggregate, BlockResponseState } from '../../app/api/studio-responses'
  import('../../app/api/studio-responses')
  // @ts-ignore
  export type { DatasetPreview, ScalarAggregateParams, ContentChannel, ContentDataset, StatsDataDocument, CreateStudioContentPayload, ContentMention, EmbeddedBlockDoc, EmbeddableBlockSummary, ResolvedEmbeddedBlock, SaveStatsDataDocumentPayload } from '../../app/api/studio'
  import('../../app/api/studio')
  // @ts-ignore
  export type { BroadcastCategory, BroadcastDetail, BroadcastScoreSummary, ToggleViewResponse, ProgrammeBroadcast, ProgrammeSchedule, BroadcastReview, ReviewsResponse, ReviewQuestion, ReviewSubmitPayload } from '../../app/api/tv-broadcast'
  import('../../app/api/tv-broadcast')
  // @ts-ignore
  export type { ChannelDetail, PopularProgramme, ToggleFollowResponse } from '../../app/api/tv-channel'
  import('../../app/api/tv-channel')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly $fetch: UnwrapRef<typeof import('../fetch.mjs')['$fetch']>
    readonly ADD_SOURCE_WIZARD_STEPS: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['ADD_SOURCE_WIZARD_STEPS']>
    readonly CHANNEL_BADGE_LABELS: UnwrapRef<typeof import('../../app/api/channels')['CHANNEL_BADGE_LABELS']>
    readonly CHANNEL_CHART_COLORS: UnwrapRef<typeof import('../../app/composables/useTvAudiences')['CHANNEL_CHART_COLORS']>
    readonly CONTENT_TYPE_FILTER_OPTIONS: UnwrapRef<typeof import('../../app/composables/useChannelContents')['CONTENT_TYPE_FILTER_OPTIONS']>
    readonly CONTENT_WIZARD_STEPS: UnwrapRef<typeof import('../../app/composables/useCreateContentWizard')['CONTENT_WIZARD_STEPS']>
    readonly DATAGOUV_TABULAR_API_BASE: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['DATAGOUV_TABULAR_API_BASE']>
    readonly EDIT_SOURCE_WIZARD_STEPS: UnwrapRef<typeof import('../../app/composables/useEditSourceWizard')['EDIT_SOURCE_WIZARD_STEPS']>
    readonly INVITABLE_ROLES: UnwrapRef<typeof import('../../app/api/channels')['INVITABLE_ROLES']>
    readonly OWNER_FILTER_OPTIONS: UnwrapRef<typeof import('../../app/composables/useMyStudioContents')['OWNER_FILTER_OPTIONS']>
    readonly PALETTE: UnwrapRef<typeof import('../../app/composables/useChart')['PALETTE']>
    readonly POPULAR_MEDICAMENTS: UnwrapRef<typeof import('../../app/composables/useMedicaments')['POPULAR_MEDICAMENTS']>
    readonly STATSIO_API: UnwrapRef<typeof import('../../app/api/statsio-endpoints')['STATSIO_API']>
    readonly STUDIO_EMBED_CONTEXT: UnwrapRef<typeof import('../../app/composables/studioEmbedContext')['STUDIO_EMBED_CONTEXT']>
    readonly abortNavigation: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['abortNavigation']>
    readonly acceptChannelInvitation: UnwrapRef<typeof import('../../app/api/channels')['acceptChannelInvitation']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['acceptHMRUpdate']>
    readonly addRouteMiddleware: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['addRouteMiddleware']>
    readonly anonymizeAccount: UnwrapRef<typeof import('../../app/api/statsio-user')['anonymizeAccount']>
    readonly apiFormAuthHeaders: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['apiFormAuthHeaders']>
    readonly callOnce: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/once')['callOnce']>
    readonly cancelIdleCallback: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback')['cancelIdleCallback']>
    readonly channelCategoryLabels: UnwrapRef<typeof import('../../app/api/channels')['channelCategoryLabels']>
    readonly channelRoleLabels: UnwrapRef<typeof import('../../app/api/channels')['channelRoleLabels']>
    readonly checkHandleAvailability: UnwrapRef<typeof import('../../app/api/channels-validation')['checkHandleAvailability']>
    readonly clearAggregateCache: UnwrapRef<typeof import('../../app/composables/useResolvedTokens')['clearAggregateCache']>
    readonly clearError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['clearError']>
    readonly clearHistory: UnwrapRef<typeof import('../../app/api/statsio-account')['clearHistory']>
    readonly clearNuxtData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['clearNuxtData']>
    readonly clearNuxtState: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/state')['clearNuxtState']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createAgentConversation: UnwrapRef<typeof import('../../app/api/ai')['createAgentConversation']>
    readonly createApiDataSource: UnwrapRef<typeof import('../../app/api/data-sources')['createApiDataSource']>
    readonly createChannel: UnwrapRef<typeof import('../../app/api/channels')['createChannel']>
    readonly createError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['createError']>
    readonly createOrganization: UnwrapRef<typeof import('../../app/api/channels')['createOrganization']>
    readonly createStudioContent: UnwrapRef<typeof import('../../app/api/studio')['createStudioContent']>
    readonly createUseAsyncData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['createUseAsyncData']>
    readonly createUseFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/fetch')['createUseFetch']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly datagouvTabularUrl: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['datagouvTabularUrl']>
    readonly defaultPagination: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['defaultPagination']>
    readonly defineAppConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineLazyHydrationComponent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/lazy-hydration')['defineLazyHydrationComponent']>
    readonly defineNuxtComponent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/component')['defineNuxtComponent']>
    readonly defineNuxtLink: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/components/nuxt-link')['defineNuxtLink']>
    readonly defineNuxtPlugin: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['defineNuxtPlugin']>
    readonly defineNuxtRouteMiddleware: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['defineNuxtRouteMiddleware']>
    readonly definePageMeta: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/pages')['definePageMeta']>
    readonly definePayloadPlugin: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['definePayloadPlugin']>
    readonly definePayloadReducer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['definePayloadReducer']>
    readonly definePayloadReviver: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['definePayloadReviver']>
    readonly defineStore: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['defineStore']>
    readonly deleteAgentConversation: UnwrapRef<typeof import('../../app/api/ai')['deleteAgentConversation']>
    readonly deleteAvatar: UnwrapRef<typeof import('../../app/api/statsio-account')['deleteAvatar']>
    readonly deleteChannel: UnwrapRef<typeof import('../../app/api/channels')['deleteChannel']>
    readonly deleteDataset: UnwrapRef<typeof import('../../app/api/studio')['deleteDataset']>
    readonly deleteStatsDataDocument: UnwrapRef<typeof import('../../app/api/studio')['deleteStatsDataDocument']>
    readonly detectApiStructure: UnwrapRef<typeof import('../../app/api/data-sources')['detectApiStructure']>
    readonly effect: UnwrapRef<typeof import('vue')['effect']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extractMedicamentBrandName: UnwrapRef<typeof import('../../app/utils/medicaments')['extractMedicamentBrandName']>
    readonly fetchAgentConversation: UnwrapRef<typeof import('../../app/api/ai')['fetchAgentConversation']>
    readonly fetchAgentRun: UnwrapRef<typeof import('../../app/api/ai')['fetchAgentRun']>
    readonly fetchBlockData: UnwrapRef<typeof import('../../app/api/studio')['fetchBlockData']>
    readonly fetchBlockResponse: UnwrapRef<typeof import('../../app/api/studio-responses')['fetchBlockResponse']>
    readonly fetchBroadcast: UnwrapRef<typeof import('../../app/api/tv-broadcast')['fetchBroadcast']>
    readonly fetchBroadcastReviews: UnwrapRef<typeof import('../../app/api/tv-broadcast')['fetchBroadcastReviews']>
    readonly fetchChannelCatalog: UnwrapRef<typeof import('../../app/api/channels')['fetchChannelCatalog']>
    readonly fetchChannelDetail: UnwrapRef<typeof import('../../app/api/tv-channel')['fetchChannelDetail']>
    readonly fetchChannelPopularProgrammes: UnwrapRef<typeof import('../../app/api/tv-channel')['fetchChannelPopularProgrammes']>
    readonly fetchChannelSchedules: UnwrapRef<typeof import('../../app/api/tv-schedule')['fetchChannelSchedules']>
    readonly fetchContentCategories: UnwrapRef<typeof import('../../app/api/content-categories')['fetchContentCategories']>
    readonly fetchContentDataSources: UnwrapRef<typeof import('../../app/api/studio')['fetchContentDataSources']>
    readonly fetchContentMentions: UnwrapRef<typeof import('../../app/api/studio')['fetchContentMentions']>
    readonly fetchDataSource: UnwrapRef<typeof import('../../app/api/data-sources')['fetchDataSource']>
    readonly fetchDatasetPreview: UnwrapRef<typeof import('../../app/api/studio')['fetchDatasetPreview']>
    readonly fetchDatasetSchema: UnwrapRef<typeof import('../../app/api/studio')['fetchDatasetSchema']>
    readonly fetchDatasets: UnwrapRef<typeof import('../../app/api/studio')['fetchDatasets']>
    readonly fetchDistinctValues: UnwrapRef<typeof import('../../app/api/studio')['fetchDistinctValues']>
    readonly fetchFavorites: UnwrapRef<typeof import('../../app/api/statsio-account')['fetchFavorites']>
    readonly fetchHistory: UnwrapRef<typeof import('../../app/api/statsio-account')['fetchHistory']>
    readonly fetchIdentityStatus: UnwrapRef<typeof import('../../app/api/identity')['fetchIdentityStatus']>
    readonly fetchInProgress: UnwrapRef<typeof import('../../app/api/statsio-account')['fetchInProgress']>
    readonly fetchMaladieDetail: UnwrapRef<typeof import('../../app/api/maladies')['fetchMaladieDetail']>
    readonly fetchMaladiesPopulaires: UnwrapRef<typeof import('../../app/api/maladies')['fetchMaladiesPopulaires']>
    readonly fetchMaladiesSearch: UnwrapRef<typeof import('../../app/api/maladies')['fetchMaladiesSearch']>
    readonly fetchMedicamentDetail: UnwrapRef<typeof import('../../app/api/medicaments')['fetchMedicamentDetail']>
    readonly fetchMedicamentGeneriques: UnwrapRef<typeof import('../../app/api/medicaments')['fetchMedicamentGeneriques']>
    readonly fetchMedicamentImage: UnwrapRef<typeof import('../../app/api/medicaments')['fetchMedicamentImage']>
    readonly fetchMedicamentVentes: UnwrapRef<typeof import('../../app/api/medicaments')['fetchMedicamentVentes']>
    readonly fetchMedicamentsSearch: UnwrapRef<typeof import('../../app/api/medicaments')['fetchMedicamentsSearch']>
    readonly fetchMedicamentsTopVentes: UnwrapRef<typeof import('../../app/api/medicaments')['fetchMedicamentsTopVentes']>
    readonly fetchPaysDetail: UnwrapRef<typeof import('../../app/api/pays')['fetchPaysDetail']>
    readonly fetchPaysList: UnwrapRef<typeof import('../../app/api/pays')['fetchPaysList']>
    readonly fetchProfileReferenceData: UnwrapRef<typeof import('../../app/api/statsio-user')['fetchProfileReferenceData']>
    readonly fetchProgrammeSchedule: UnwrapRef<typeof import('../../app/api/tv-broadcast')['fetchProgrammeSchedule']>
    readonly fetchPublicArticles: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicArticles']>
    readonly fetchPublicBlockData: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicBlockData']>
    readonly fetchPublicCatalog: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicCatalog']>
    readonly fetchPublicDistinctValues: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicDistinctValues']>
    readonly fetchPublicScalarAggregate: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicScalarAggregate']>
    readonly fetchPublicSearchRows: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicSearchRows']>
    readonly fetchPublicStatsDataBlock: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicStatsDataBlock']>
    readonly fetchPublicStatsDataCatalog: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicStatsDataCatalog']>
    readonly fetchPublicStatsDataDocument: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicStatsDataDocument']>
    readonly fetchPublicSurveys: UnwrapRef<typeof import('../../app/api/studio')['fetchPublicSurveys']>
    readonly fetchReviewQuestions: UnwrapRef<typeof import('../../app/api/tv-broadcast')['fetchReviewQuestions']>
    readonly fetchScalarAggregate: UnwrapRef<typeof import('../../app/api/studio')['fetchScalarAggregate']>
    readonly fetchSearchRows: UnwrapRef<typeof import('../../app/api/studio')['fetchSearchRows']>
    readonly fetchSoinsList: UnwrapRef<typeof import('../../app/api/soins')['fetchSoinsList']>
    readonly fetchSourceProvenances: UnwrapRef<typeof import('../../app/api/source-provenances')['fetchSourceProvenances']>
    readonly fetchStatsDataDocument: UnwrapRef<typeof import('../../app/api/studio')['fetchStatsDataDocument']>
    readonly fetchStatsDataEmbeddableBlocks: UnwrapRef<typeof import('../../app/api/studio')['fetchStatsDataEmbeddableBlocks']>
    readonly fetchStatsioAuthMe: UnwrapRef<typeof import('../../app/api/statsio-user')['fetchStatsioAuthMe']>
    readonly fetchStatsioMe: UnwrapRef<typeof import('../../app/api/statsio-user')['fetchStatsioMe']>
    readonly fetchSubscriptions: UnwrapRef<typeof import('../../app/api/statsio-account')['fetchSubscriptions']>
    readonly fetchTvAudiences: UnwrapRef<typeof import('../../app/api/tv-audiences')['fetchTvAudiences']>
    readonly fetchUserStudioContents: UnwrapRef<typeof import('../../app/api/studio')['fetchUserStudioContents']>
    readonly fmtRelative: UnwrapRef<typeof import('../../app/composables/useBroadcastDetail')['fmtRelative']>
    readonly fmtScheduleDate: UnwrapRef<typeof import('../../app/composables/useBroadcastDetail')['fmtScheduleDate']>
    readonly formatCompactNumber: UnwrapRef<typeof import('../../app/utils/number')['formatCompactNumber']>
    readonly formatDisplayValue: UnwrapRef<typeof import('../../app/utils/statsDataFormat')['formatDisplayValue']>
    readonly formatRowCount: UnwrapRef<typeof import('../../app/utils/statsDataFormat')['formatRowCount']>
    readonly formatStatsDataDate: UnwrapRef<typeof import('../../app/utils/statsDataFormat')['formatStatsDataDate']>
    readonly getAppManifest: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/manifest')['getAppManifest']>
    readonly getChannel: UnwrapRef<typeof import('../../app/api/channels')['getChannel']>
    readonly getChannelCategories: UnwrapRef<typeof import('../../app/api/channels')['getChannelCategories']>
    readonly getChannelDataSources: UnwrapRef<typeof import('../../app/api/channels')['getChannelDataSources']>
    readonly getChannelInvitations: UnwrapRef<typeof import('../../app/api/channels')['getChannelInvitations']>
    readonly getChannelMembers: UnwrapRef<typeof import('../../app/api/channels')['getChannelMembers']>
    readonly getChannelPermissionsCatalog: UnwrapRef<typeof import('../../app/api/channels')['getChannelPermissionsCatalog']>
    readonly getChannelStats: UnwrapRef<typeof import('../../app/api/channels')['getChannelStats']>
    readonly getChannelSubscribers: UnwrapRef<typeof import('../../app/api/channels')['getChannelSubscribers']>
    readonly getChannels: UnwrapRef<typeof import('../../app/api/channels')['getChannels']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getInvitationByToken: UnwrapRef<typeof import('../../app/api/channels')['getInvitationByToken']>
    readonly getJoinableOrganizations: UnwrapRef<typeof import('../../app/api/channels')['getJoinableOrganizations']>
    readonly getMedicamentFormEmoji: UnwrapRef<typeof import('../../app/utils/medicaments')['getMedicamentFormEmoji']>
    readonly getMyChannels: UnwrapRef<typeof import('../../app/api/channels')['getMyChannels']>
    readonly getPublicChannels: UnwrapRef<typeof import('../../app/api/channels')['getPublicChannels']>
    readonly getRouteRules: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/manifest')['getRouteRules']>
    readonly getStatsDataPalette: UnwrapRef<typeof import('../../app/utils/statsDataVisuals')['getStatsDataPalette']>
    readonly getStatsDataVisual: UnwrapRef<typeof import('../../app/utils/statsDataVisuals')['getStatsDataVisual']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hasInjectionContext: UnwrapRef<typeof import('vue')['hasInjectionContext']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectHead: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['injectHead']>
    readonly invalidateDbChannelCache: UnwrapRef<typeof import('../../app/api/tv-schedule')['invalidateDbChannelCache']>
    readonly inviteChannelMembers: UnwrapRef<typeof import('../../app/api/channels')['inviteChannelMembers']>
    readonly isNuxtError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['isNuxtError']>
    readonly isPrerendered: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['isPrerendered']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isVue2: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi')['isVue2']>
    readonly isVue3: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/vue-demi')['isVue3']>
    readonly isoToFlagEmoji: UnwrapRef<typeof import('../../app/utils/flag')['isoToFlagEmoji']>
    readonly joinOrganization: UnwrapRef<typeof import('../../app/api/channels')['joinOrganization']>
    readonly leaveOrganization: UnwrapRef<typeof import('../../app/api/channels')['leaveOrganization']>
    readonly listAgentConversations: UnwrapRef<typeof import('../../app/api/ai')['listAgentConversations']>
    readonly loadArticleMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadArticleMenu']>
    readonly loadAudiencesMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadAudiencesMenu']>
    readonly loadChannelsMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadChannelsMenu']>
    readonly loadMaladiesMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadMaladiesMenu']>
    readonly loadMedicamentsMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadMedicamentsMenu']>
    readonly loadPayload: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['loadPayload']>
    readonly loadProgrammeTvMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadProgrammeTvMenu']>
    readonly loadPromoTicker: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadPromoTicker']>
    readonly loadSoinsMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadSoinsMenu']>
    readonly loadStatsDataMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadStatsDataMenu']>
    readonly loadSurveyMenu: UnwrapRef<typeof import('../../app/composables/useHeaderMegaMenuData')['loadSurveyMenu']>
    readonly mapPaginationToApi: UnwrapRef<typeof import('../../app/api/data-sources')['mapPaginationToApi']>
    readonly mapQueryMappingToApi: UnwrapRef<typeof import('../../app/api/data-sources')['mapQueryMappingToApi']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly navigateTo: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['navigateTo']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('../../node_modules/vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('../../node_modules/vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onNuxtReady: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ready')['onNuxtReady']>
    readonly onPrehydrate: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['onPrehydrate']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseDatagouvResourceId: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['parseDatagouvResourceId']>
    readonly parseNumericValue: UnwrapRef<typeof import('../../app/utils/statsDataFormat')['parseNumericValue']>
    readonly prefetchComponents: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preload')['prefetchComponents']>
    readonly preloadComponents: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preload')['preloadComponents']>
    readonly preloadPayload: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/payload')['preloadPayload']>
    readonly preloadRouteComponents: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preload')['preloadRouteComponents']>
    readonly prerenderRoutes: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['prerenderRoutes']>
    readonly previewSpreadsheet: UnwrapRef<typeof import('../../app/api/data-sources')['previewSpreadsheet']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly proxyRefs: UnwrapRef<typeof import('vue')['proxyRefs']>
    readonly publishStatsDataDocument: UnwrapRef<typeof import('../../app/api/studio')['publishStatsDataDocument']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly recordContentView: UnwrapRef<typeof import('../../app/api/statsio-account')['recordContentView']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refreshCookie: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/cookie')['refreshCookie']>
    readonly refreshDataSource: UnwrapRef<typeof import('../../app/api/data-sources')['refreshDataSource']>
    readonly refreshNuxtData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['refreshNuxtData']>
    readonly relativeUpdate: UnwrapRef<typeof import('../../app/utils/statsDataFormat')['relativeUpdate']>
    readonly reloadNuxtApp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/chunk')['reloadNuxtApp']>
    readonly removeFavorite: UnwrapRef<typeof import('../../app/api/statsio-account')['removeFavorite']>
    readonly requestIdleCallback: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/idle-callback')['requestIdleCallback']>
    readonly resolveAggregationParams: UnwrapRef<typeof import('../../app/composables/useBlockData')['resolveAggregationParams']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly revokeChannelInvitation: UnwrapRef<typeof import('../../app/api/channels')['revokeChannelInvitation']>
    readonly saveStatsDataDocument: UnwrapRef<typeof import('../../app/api/studio')['saveStatsDataDocument']>
    readonly searchAccount: UnwrapRef<typeof import('../../app/api/statsio-account')['searchAccount']>
    readonly seededSparklinePoints: UnwrapRef<typeof import('../../app/utils/statsDataVisuals')['seededSparklinePoints']>
    readonly sendAgentMessage: UnwrapRef<typeof import('../../app/api/ai')['sendAgentMessage']>
    readonly setInterval: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/compat/interval')['setInterval']>
    readonly setPageLayout: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['setPageLayout']>
    readonly setResponseStatus: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['setResponseStatus']>
    readonly setStatsDataDocumentStatus: UnwrapRef<typeof import('../../app/api/studio')['setStatsDataDocumentStatus']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly showError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['showError']>
    readonly startIdentityVerification: UnwrapRef<typeof import('../../app/api/identity')['startIdentityVerification']>
    readonly storeToRefs: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['storeToRefs']>
    readonly submitBlockResponse: UnwrapRef<typeof import('../../app/api/studio-responses')['submitBlockResponse']>
    readonly submitBroadcastReview: UnwrapRef<typeof import('../../app/api/tv-broadcast')['submitBroadcastReview']>
    readonly submitContactMessage: UnwrapRef<typeof import('../../app/api/contact')['submitContactMessage']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toggleBroadcastView: UnwrapRef<typeof import('../../app/api/tv-broadcast')['toggleBroadcastView']>
    readonly toggleChannelFollow: UnwrapRef<typeof import('../../app/api/tv-channel')['toggleChannelFollow']>
    readonly toggleChannelSubscription: UnwrapRef<typeof import('../../app/api/channels')['toggleChannelSubscription']>
    readonly toggleFavorite: UnwrapRef<typeof import('../../app/api/statsio-account')['toggleFavorite']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly tryUseNuxtApp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['tryUseNuxtApp']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateAppConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/config')['updateAppConfig']>
    readonly updateChannel: UnwrapRef<typeof import('../../app/api/channels')['updateChannel']>
    readonly updateChannelMedia: UnwrapRef<typeof import('../../app/api/channels')['updateChannelMedia']>
    readonly updateChannelProfile: UnwrapRef<typeof import('../../app/api/channels')['updateChannelProfile']>
    readonly updateDataSource: UnwrapRef<typeof import('../../app/api/data-sources')['updateDataSource']>
    readonly updateDataset: UnwrapRef<typeof import('../../app/api/studio')['updateDataset']>
    readonly updateProfile: UnwrapRef<typeof import('../../app/api/statsio-user')['updateProfile']>
    readonly uploadAvatar: UnwrapRef<typeof import('../../app/api/statsio-account')['uploadAvatar']>
    readonly useAccountFavorites: UnwrapRef<typeof import('../../app/composables/useAccountFavorites')['useAccountFavorites']>
    readonly useAccountHistory: UnwrapRef<typeof import('../../app/composables/useAccountHistory')['useAccountHistory']>
    readonly useAccountOverview: UnwrapRef<typeof import('../../app/composables/useAccountOverview')['useAccountOverview']>
    readonly useAccountSearch: UnwrapRef<typeof import('../../app/composables/useAccountSearch')['useAccountSearch']>
    readonly useAccountSubscriptions: UnwrapRef<typeof import('../../app/composables/useAccountSubscriptions')['useAccountSubscriptions']>
    readonly useActiveEditor: UnwrapRef<typeof import('../../app/composables/useActiveEditor')['useActiveEditor']>
    readonly useAddSourceWizard: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['useAddSourceWizard']>
    readonly useAggregateValues: UnwrapRef<typeof import('../../app/composables/useResolvedTokens')['useAggregateValues']>
    readonly useAnnouncer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/announcer')['useAnnouncer']>
    readonly useApiStructureDetection: UnwrapRef<typeof import('../../app/composables/useAddSourceWizard')['useApiStructureDetection']>
    readonly useAppConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/config')['useAppConfig']>
    readonly useAppNotifications: UnwrapRef<typeof import('../../app/composables/useAppNotifications')['useAppNotifications']>
    readonly useAppNotificationsStore: UnwrapRef<typeof import('../../app/stores/app-notifications')['useAppNotificationsStore']>
    readonly useAsyncData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['useAsyncData']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('../../app/stores/auth')['useAuthStore']>
    readonly useBlockData: UnwrapRef<typeof import('../../app/composables/useBlockData')['useBlockData']>
    readonly useBroadcastDetail: UnwrapRef<typeof import('../../app/composables/useBroadcastDetail')['useBroadcastDetail']>
    readonly useChannelContents: UnwrapRef<typeof import('../../app/composables/useChannelContents')['useChannelContents']>
    readonly useChannelDashboard: UnwrapRef<typeof import('../../app/composables/useChannelDashboard')['useChannelDashboard']>
    readonly useChannelDataSources: UnwrapRef<typeof import('../../app/composables/useChannelDataSources')['useChannelDataSources']>
    readonly useChannelDetail: UnwrapRef<typeof import('../../app/composables/useChannelDetail')['useChannelDetail']>
    readonly useChannelProfile: UnwrapRef<typeof import('../../app/composables/useChannelProfile')['useChannelProfile']>
    readonly useChannelPublicContent: UnwrapRef<typeof import('../../app/composables/useChannelPublicContent')['useChannelPublicContent']>
    readonly useChannelStats: UnwrapRef<typeof import('../../app/composables/useChannelStats')['useChannelStats']>
    readonly useChannelsCatalog: UnwrapRef<typeof import('../../app/composables/useChannelsCatalog')['useChannelsCatalog']>
    readonly useChart: UnwrapRef<typeof import('../../app/composables/useChart')['useChart']>
    readonly useClickOutside: UnwrapRef<typeof import('../../app/composables/useClickOutside')['useClickOutside']>
    readonly useContentBasePath: UnwrapRef<typeof import('../../app/composables/useContentBasePath')['useContentBasePath']>
    readonly useContentDashboard: UnwrapRef<typeof import('../../app/composables/useContentDashboard')['useContentDashboard']>
    readonly useContentDataSources: UnwrapRef<typeof import('../../app/composables/useContentDataSources')['useContentDataSources']>
    readonly useContextStore: UnwrapRef<typeof import('../../app/stores/context')['useContextStore']>
    readonly useCookie: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/cookie')['useCookie']>
    readonly useCookieBanner: UnwrapRef<typeof import('../../app/composables/useCookieBanner')['useCookieBanner']>
    readonly useCreateContentWizard: UnwrapRef<typeof import('../../app/composables/useCreateContentWizard')['useCreateContentWizard']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useEditSourceWizard: UnwrapRef<typeof import('../../app/composables/useEditSourceWizard')['useEditSourceWizard']>
    readonly useError: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/error')['useError']>
    readonly useExpressionNumber: UnwrapRef<typeof import('../../app/composables/useResolvedTokens')['useExpressionNumber']>
    readonly useFavicon: UnwrapRef<typeof import('../../app/composables/useFavicon')['useFavicon']>
    readonly useFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/fetch')['useFetch']>
    readonly useFormBlockResponse: UnwrapRef<typeof import('../../app/composables/useFormBlockResponse')['useFormBlockResponse']>
    readonly useHead: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useHead']>
    readonly useHeadSafe: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useHeadSafe']>
    readonly useHomeCatalogSection: UnwrapRef<typeof import('../../app/composables/useHomeCatalogSection')['useHomeCatalogSection']>
    readonly useHydration: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/hydrate')['useHydration']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLayout: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/layout')['useLayout']>
    readonly useLazyAsyncData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['useLazyAsyncData']>
    readonly useLazyFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/fetch')['useLazyFetch']>
    readonly useLink: UnwrapRef<typeof import('../../node_modules/vue-router')['useLink']>
    readonly useLoadingIndicator: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/loading-indicator')['useLoadingIndicator']>
    readonly useMaladies: UnwrapRef<typeof import('../../app/composables/useMaladies')['useMaladies']>
    readonly useMedicamentImage: UnwrapRef<typeof import('../../app/composables/useMedicamentImage')['useMedicamentImage']>
    readonly useMedicaments: UnwrapRef<typeof import('../../app/composables/useMedicaments')['useMedicaments']>
    readonly useModalA11y: UnwrapRef<typeof import('../../app/composables/useModalA11y')['useModalA11y']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMyChannels: UnwrapRef<typeof import('../../app/composables/useMyChannels')['useMyChannels']>
    readonly useMyStudioContents: UnwrapRef<typeof import('../../app/composables/useMyStudioContents')['useMyStudioContents']>
    readonly useNowNext: UnwrapRef<typeof import('../../app/composables/useNowNext')['useNowNext']>
    readonly useNuxtApp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['useNuxtApp']>
    readonly useNuxtData: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/asyncData')['useNuxtData']>
    readonly useNuxtDevTools: UnwrapRef<typeof import('../../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools')['useNuxtDevTools']>
    readonly usePageSeo: UnwrapRef<typeof import('../../app/composables/usePageSeo')['usePageSeo']>
    readonly usePays: UnwrapRef<typeof import('../../app/composables/usePays')['usePays']>
    readonly usePinia: UnwrapRef<typeof import('../../node_modules/@pinia/nuxt/dist/runtime/composables')['usePinia']>
    readonly usePrefsStore: UnwrapRef<typeof import('../../app/stores/prefs')['usePrefsStore']>
    readonly usePreviewMode: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/preview')['usePreviewMode']>
    readonly usePublicCatalog: UnwrapRef<typeof import('../../app/composables/usePublicCatalog')['usePublicCatalog']>
    readonly useRequestEvent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestEvent']>
    readonly useRequestFetch: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestFetch']>
    readonly useRequestHeader: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestHeader']>
    readonly useRequestHeaders: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useRequestHeaders']>
    readonly useRequestURL: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/url')['useRequestURL']>
    readonly useResolvedTokenList: UnwrapRef<typeof import('../../app/composables/useResolvedTokens')['useResolvedTokenList']>
    readonly useResolvedTokens: UnwrapRef<typeof import('../../app/composables/useResolvedTokens')['useResolvedTokens']>
    readonly useRespondentToken: UnwrapRef<typeof import('../../app/composables/useRespondentToken')['useRespondentToken']>
    readonly useResponseHeader: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/ssr')['useResponseHeader']>
    readonly useRoute: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['useRoute']>
    readonly useRouteAnnouncer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/route-announcer')['useRouteAnnouncer']>
    readonly useRouter: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/router')['useRouter']>
    readonly useRuntimeConfig: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/nuxt')['useRuntimeConfig']>
    readonly useRuntimeHook: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/runtime-hook')['useRuntimeHook']>
    readonly useScript: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScript']>
    readonly useScriptAhrefsAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptAhrefsAnalytics']>
    readonly useScriptBingUet: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptBingUet']>
    readonly useScriptCalendly: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptCalendly']>
    readonly useScriptClarity: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptClarity']>
    readonly useScriptCloudflareWebAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptCloudflareWebAnalytics']>
    readonly useScriptCrisp: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptCrisp']>
    readonly useScriptDatabuddyAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptDatabuddyAnalytics']>
    readonly useScriptEventPage: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptEventPage']>
    readonly useScriptFathomAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptFathomAnalytics']>
    readonly useScriptGoogleAdsense: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleAdsense']>
    readonly useScriptGoogleAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleAnalytics']>
    readonly useScriptGoogleMaps: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleMaps']>
    readonly useScriptGoogleRecaptcha: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleRecaptcha']>
    readonly useScriptGoogleSignIn: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleSignIn']>
    readonly useScriptGoogleTagManager: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGoogleTagManager']>
    readonly useScriptGravatar: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptGravatar']>
    readonly useScriptHotjar: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptHotjar']>
    readonly useScriptIntercom: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptIntercom']>
    readonly useScriptLemonSqueezy: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptLemonSqueezy']>
    readonly useScriptLinkedInInsight: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptLinkedInInsight']>
    readonly useScriptMatomoAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptMatomoAnalytics']>
    readonly useScriptMetaPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptMetaPixel']>
    readonly useScriptMixpanelAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptMixpanelAnalytics']>
    readonly useScriptNpm: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptNpm']>
    readonly useScriptPayPal: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptPayPal']>
    readonly useScriptPlausibleAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptPlausibleAnalytics']>
    readonly useScriptPostHog: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptPostHog']>
    readonly useScriptRedditPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptRedditPixel']>
    readonly useScriptRybbitAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptRybbitAnalytics']>
    readonly useScriptSegment: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptSegment']>
    readonly useScriptSnapchatPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptSnapchatPixel']>
    readonly useScriptSpeedCurve: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptSpeedCurve']>
    readonly useScriptStripe: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptStripe']>
    readonly useScriptTikTokPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptTikTokPixel']>
    readonly useScriptTriggerConsent: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptTriggerConsent']>
    readonly useScriptTriggerElement: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptTriggerElement']>
    readonly useScriptUmamiAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptUmamiAnalytics']>
    readonly useScriptUsercentrics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptUsercentrics']>
    readonly useScriptVercelAnalytics: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptVercelAnalytics']>
    readonly useScriptVimeoPlayer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptVimeoPlayer']>
    readonly useScriptXPixel: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptXPixel']>
    readonly useScriptYouTubePlayer: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/script-stubs')['useScriptYouTubePlayer']>
    readonly useScrollAnim: UnwrapRef<typeof import('../../app/composables/useScrollAnim')['useScrollAnim']>
    readonly useSeoMeta: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useSeoMeta']>
    readonly useServerHead: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useServerHead']>
    readonly useServerHeadSafe: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useServerHeadSafe']>
    readonly useServerSeoMeta: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/head')['useServerSeoMeta']>
    readonly useShadowRoot: UnwrapRef<typeof import('vue')['useShadowRoot']>
    readonly useSimilarChannels: UnwrapRef<typeof import('../../app/composables/useSimilarChannels')['useSimilarChannels']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSoins: UnwrapRef<typeof import('../../app/composables/useSoins')['useSoins']>
    readonly useState: UnwrapRef<typeof import('../../node_modules/nuxt/dist/app/composables/state')['useState']>
    readonly useStatsDataChrome: UnwrapRef<typeof import('../../app/composables/useStatsDataChrome')['useStatsDataChrome']>
    readonly useStatsDataDetail: UnwrapRef<typeof import('../../app/composables/useStatsDataDetail')['useStatsDataDetail']>
    readonly useStudioAgentStore: UnwrapRef<typeof import('../../app/stores/studio-agent')['useStudioAgentStore']>
    readonly useStudioAutosave: UnwrapRef<typeof import('../../app/composables/useStudioAutosave')['useStudioAutosave']>
    readonly useStudioDatasetsStore: UnwrapRef<typeof import('../../app/stores/studio-datasets')['useStudioDatasetsStore']>
    readonly useStudioStore: UnwrapRef<typeof import('../../app/stores/studio')['useStudioStore']>
    readonly useStudioVariables: UnwrapRef<typeof import('../../app/composables/useStudioVariables')['useStudioVariables']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTransitionState: UnwrapRef<typeof import('vue')['useTransitionState']>
    readonly useTvAudiences: UnwrapRef<typeof import('../../app/composables/useTvAudiences')['useTvAudiences']>
    readonly useTvSchedule: UnwrapRef<typeof import('../../app/composables/useTvSchedule')['useTvSchedule']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly withCtx: UnwrapRef<typeof import('vue')['withCtx']>
    readonly withDirectives: UnwrapRef<typeof import('vue')['withDirectives']>
    readonly withKeys: UnwrapRef<typeof import('vue')['withKeys']>
    readonly withMemo: UnwrapRef<typeof import('vue')['withMemo']>
    readonly withModifiers: UnwrapRef<typeof import('vue')['withModifiers']>
    readonly withScopeId: UnwrapRef<typeof import('vue')['withScopeId']>
    readonly wizardStepsFor: UnwrapRef<typeof import('../../app/composables/useCreateContentWizard')['wizardStepsFor']>
  }
}