
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AdminSidebar: typeof import("../app/components/admin/AdminSidebar.vue")['default']
export const AuthGoogleButton: typeof import("../app/components/auth/AuthGoogleButton.vue")['default']
export const UserDashboardCreatorSection: typeof import("../app/components/dashboard/UserDashboardCreatorSection.vue")['default']
export const UserDashboardHistorySection: typeof import("../app/components/dashboard/UserDashboardHistorySection.vue")['default']
export const UserDashboardLayout: typeof import("../app/components/dashboard/UserDashboardLayout.vue")['default']
export const UserDashboardSidebarCompletion: typeof import("../app/components/dashboard/UserDashboardSidebarCompletion.vue")['default']
export const UserDashboardSidebarNav: typeof import("../app/components/dashboard/UserDashboardSidebarNav.vue")['default']
export const UserDashboardSidebarProfileCard: typeof import("../app/components/dashboard/UserDashboardSidebarProfileCard.vue")['default']
export const UserDashboardSubscriptionsSection: typeof import("../app/components/dashboard/UserDashboardSubscriptionsSection.vue")['default']
export const UserDashboardUsageCard: typeof import("../app/components/dashboard/UserDashboardUsageCard.vue")['default']
export const HomeArticles: typeof import("../app/components/home/HomeArticles.vue")['default']
export const HomeCTA: typeof import("../app/components/home/HomeCTA.vue")['default']
export const HomeHero: typeof import("../app/components/home/HomeHero.vue")['default']
export const HomeHighlights: typeof import("../app/components/home/HomeHighlights.vue")['default']
export const HomePageFrame: typeof import("../app/components/home/HomePageFrame.vue")['default']
export const HomePolls: typeof import("../app/components/home/HomePolls.vue")['default']
export const HomeStatsData: typeof import("../app/components/home/HomeStatsData.vue")['default']
export const HomeStatsStrip: typeof import("../app/components/home/HomeStatsStrip.vue")['default']
export const IconCommunity: typeof import("../app/components/icons/IconCommunity.vue")['default']
export const IconDocumentation: typeof import("../app/components/icons/IconDocumentation.vue")['default']
export const IconEcosystem: typeof import("../app/components/icons/IconEcosystem.vue")['default']
export const IconSupport: typeof import("../app/components/icons/IconSupport.vue")['default']
export const IconTooling: typeof import("../app/components/icons/IconTooling.vue")['default']
export const AppAccessibilityPanel: typeof import("../app/components/layout/AppAccessibilityPanel.vue")['default']
export const AppBootstrapError: typeof import("../app/components/layout/AppBootstrapError.vue")['default']
export const AppCreateFab: typeof import("../app/components/layout/AppCreateFab.vue")['default']
export const AppDropdownMenu: typeof import("../app/components/layout/AppDropdownMenu.vue")['default']
export const AppDropdownMenuItem: typeof import("../app/components/layout/AppDropdownMenuItem.vue")['default']
export const AppFooter: typeof import("../app/components/layout/AppFooter.vue")['default']
export const AppHeader: typeof import("../app/components/layout/AppHeader.vue")['default']
export const AppNavIcon: typeof import("../app/components/layout/AppNavIcon.vue")['default']
export const AppNotificationStack: typeof import("../app/components/layout/AppNotificationStack.vue")['default']
export const AppPromoBanner: typeof import("../app/components/layout/AppPromoBanner.vue")['default']
export const AuthLayout: typeof import("../app/components/login/AuthLayout.vue")['default']
export const ForgotPasswordFormCard: typeof import("../app/components/login/ForgotPasswordFormCard.vue")['default']
export const LoginFormCard: typeof import("../app/components/login/LoginFormCard.vue")['default']
export const LoginHeader: typeof import("../app/components/login/LoginHeader.vue")['default']
export const LoginIntroPanel: typeof import("../app/components/login/LoginIntroPanel.vue")['default']
export const RegisterFormCard: typeof import("../app/components/login/RegisterFormCard.vue")['default']
export const GlobalStatusBar: typeof import("../app/components/notifications/GlobalStatusBar.vue")['default']
export const PollCard: typeof import("../app/components/polls/PollCard.vue")['default']
export const PollQuestionBlock: typeof import("../app/components/polls/PollQuestionBlock.vue")['default']
export const StudioHeader: typeof import("../app/components/studio/StudioHeader.vue")['default']
export const StudioSidebarLeft: typeof import("../app/components/studio/StudioSidebarLeft.vue")['default']
export const StudioSidebarRight: typeof import("../app/components/studio/StudioSidebarRight.vue")['default']
export const BarChartBlock: typeof import("../app/components/studio/blocks/BarChartBlock.vue")['default']
export const BlockRenderer: typeof import("../app/components/studio/blocks/BlockRenderer.vue")['default']
export const KpiBlock: typeof import("../app/components/studio/blocks/KpiBlock.vue")['default']
export const LineChartBlock: typeof import("../app/components/studio/blocks/LineChartBlock.vue")['default']
export const SearchBlock: typeof import("../app/components/studio/blocks/SearchBlock.vue")['default']
export const TableBlock: typeof import("../app/components/studio/blocks/TableBlock.vue")['default']
export const TextBlock: typeof import("../app/components/studio/blocks/TextBlock.vue")['default']
export const BlockWrapper: typeof import("../app/components/studio/canvas/BlockWrapper.vue")['default']
export const CanvasGrid: typeof import("../app/components/studio/canvas/CanvasGrid.vue")['default']
export const CanvasPageTabs: typeof import("../app/components/studio/canvas/CanvasPageTabs.vue")['default']
export const CanvasSection: typeof import("../app/components/studio/canvas/CanvasSection.vue")['default']
export const CanvasZone: typeof import("../app/components/studio/canvas/CanvasZone.vue")['default']
export const AddSourceModal: typeof import("../app/components/studio/sidebar/AddSourceModal.vue")['default']
export const BlockConfigPanel: typeof import("../app/components/studio/sidebar/BlockConfigPanel.vue")['default']
export const DynamicParamsPanel: typeof import("../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']
export const SidebarBlocks: typeof import("../app/components/studio/sidebar/SidebarBlocks.vue")['default']
export const SidebarDataSources: typeof import("../app/components/studio/sidebar/SidebarDataSources.vue")['default']
export const SidebarLayouts: typeof import("../app/components/studio/sidebar/SidebarLayouts.vue")['default']
export const SidebarVariables: typeof import("../app/components/studio/sidebar/SidebarVariables.vue")['default']
export const TvAudiencesEvolutionChart: typeof import("../app/components/tv/TvAudiencesEvolutionChart.vue")['default']
export const TvAudiencesRankingTable: typeof import("../app/components/tv/TvAudiencesRankingTable.vue")['default']
export const TvAudiencesTop50Table: typeof import("../app/components/tv/TvAudiencesTop50Table.vue")['default']
export const TvProgrammeCardIcon: typeof import("../app/components/tv/TvProgrammeCardIcon.vue")['default']
export const TvReviewModal: typeof import("../app/components/tv/TvReviewModal.vue")['default']
export const TvScheduleChannelRow: typeof import("../app/components/tv/TvScheduleChannelRow.vue")['default']
export const TvScheduleGrid: typeof import("../app/components/tv/TvScheduleGrid.vue")['default']
export const TvScheduleNowNext: typeof import("../app/components/tv/TvScheduleNowNext.vue")['default']
export const TvScheduleProgrammeBlock: typeof import("../app/components/tv/TvScheduleProgrammeBlock.vue")['default']
export const TvScheduleTimeline: typeof import("../app/components/tv/TvScheduleTimeline.vue")['default']
export const AppAvatar: typeof import("../app/components/ui/AppAvatar.vue")['default']
export const AppButton: typeof import("../app/components/ui/AppButton.vue")['default']
export const AppCheckbox: typeof import("../app/components/ui/AppCheckbox.vue")['default']
export const AppColorPickerModal: typeof import("../app/components/ui/AppColorPickerModal.vue")['default']
export const AppModal: typeof import("../app/components/ui/AppModal.vue")['default']
export const AppSelect: typeof import("../app/components/ui/AppSelect.vue")['default']
export const AppStepModal: typeof import("../app/components/ui/AppStepModal.vue")['default']
export const AppWordmark: typeof import("../app/components/ui/AppWordmark.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAdminSidebar: LazyComponent<typeof import("../app/components/admin/AdminSidebar.vue")['default']>
export const LazyAuthGoogleButton: LazyComponent<typeof import("../app/components/auth/AuthGoogleButton.vue")['default']>
export const LazyUserDashboardCreatorSection: LazyComponent<typeof import("../app/components/dashboard/UserDashboardCreatorSection.vue")['default']>
export const LazyUserDashboardHistorySection: LazyComponent<typeof import("../app/components/dashboard/UserDashboardHistorySection.vue")['default']>
export const LazyUserDashboardLayout: LazyComponent<typeof import("../app/components/dashboard/UserDashboardLayout.vue")['default']>
export const LazyUserDashboardSidebarCompletion: LazyComponent<typeof import("../app/components/dashboard/UserDashboardSidebarCompletion.vue")['default']>
export const LazyUserDashboardSidebarNav: LazyComponent<typeof import("../app/components/dashboard/UserDashboardSidebarNav.vue")['default']>
export const LazyUserDashboardSidebarProfileCard: LazyComponent<typeof import("../app/components/dashboard/UserDashboardSidebarProfileCard.vue")['default']>
export const LazyUserDashboardSubscriptionsSection: LazyComponent<typeof import("../app/components/dashboard/UserDashboardSubscriptionsSection.vue")['default']>
export const LazyUserDashboardUsageCard: LazyComponent<typeof import("../app/components/dashboard/UserDashboardUsageCard.vue")['default']>
export const LazyHomeArticles: LazyComponent<typeof import("../app/components/home/HomeArticles.vue")['default']>
export const LazyHomeCTA: LazyComponent<typeof import("../app/components/home/HomeCTA.vue")['default']>
export const LazyHomeHero: LazyComponent<typeof import("../app/components/home/HomeHero.vue")['default']>
export const LazyHomeHighlights: LazyComponent<typeof import("../app/components/home/HomeHighlights.vue")['default']>
export const LazyHomePageFrame: LazyComponent<typeof import("../app/components/home/HomePageFrame.vue")['default']>
export const LazyHomePolls: LazyComponent<typeof import("../app/components/home/HomePolls.vue")['default']>
export const LazyHomeStatsData: LazyComponent<typeof import("../app/components/home/HomeStatsData.vue")['default']>
export const LazyHomeStatsStrip: LazyComponent<typeof import("../app/components/home/HomeStatsStrip.vue")['default']>
export const LazyIconCommunity: LazyComponent<typeof import("../app/components/icons/IconCommunity.vue")['default']>
export const LazyIconDocumentation: LazyComponent<typeof import("../app/components/icons/IconDocumentation.vue")['default']>
export const LazyIconEcosystem: LazyComponent<typeof import("../app/components/icons/IconEcosystem.vue")['default']>
export const LazyIconSupport: LazyComponent<typeof import("../app/components/icons/IconSupport.vue")['default']>
export const LazyIconTooling: LazyComponent<typeof import("../app/components/icons/IconTooling.vue")['default']>
export const LazyAppAccessibilityPanel: LazyComponent<typeof import("../app/components/layout/AppAccessibilityPanel.vue")['default']>
export const LazyAppBootstrapError: LazyComponent<typeof import("../app/components/layout/AppBootstrapError.vue")['default']>
export const LazyAppCreateFab: LazyComponent<typeof import("../app/components/layout/AppCreateFab.vue")['default']>
export const LazyAppDropdownMenu: LazyComponent<typeof import("../app/components/layout/AppDropdownMenu.vue")['default']>
export const LazyAppDropdownMenuItem: LazyComponent<typeof import("../app/components/layout/AppDropdownMenuItem.vue")['default']>
export const LazyAppFooter: LazyComponent<typeof import("../app/components/layout/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/layout/AppHeader.vue")['default']>
export const LazyAppNavIcon: LazyComponent<typeof import("../app/components/layout/AppNavIcon.vue")['default']>
export const LazyAppNotificationStack: LazyComponent<typeof import("../app/components/layout/AppNotificationStack.vue")['default']>
export const LazyAppPromoBanner: LazyComponent<typeof import("../app/components/layout/AppPromoBanner.vue")['default']>
export const LazyAuthLayout: LazyComponent<typeof import("../app/components/login/AuthLayout.vue")['default']>
export const LazyForgotPasswordFormCard: LazyComponent<typeof import("../app/components/login/ForgotPasswordFormCard.vue")['default']>
export const LazyLoginFormCard: LazyComponent<typeof import("../app/components/login/LoginFormCard.vue")['default']>
export const LazyLoginHeader: LazyComponent<typeof import("../app/components/login/LoginHeader.vue")['default']>
export const LazyLoginIntroPanel: LazyComponent<typeof import("../app/components/login/LoginIntroPanel.vue")['default']>
export const LazyRegisterFormCard: LazyComponent<typeof import("../app/components/login/RegisterFormCard.vue")['default']>
export const LazyGlobalStatusBar: LazyComponent<typeof import("../app/components/notifications/GlobalStatusBar.vue")['default']>
export const LazyPollCard: LazyComponent<typeof import("../app/components/polls/PollCard.vue")['default']>
export const LazyPollQuestionBlock: LazyComponent<typeof import("../app/components/polls/PollQuestionBlock.vue")['default']>
export const LazyStudioHeader: LazyComponent<typeof import("../app/components/studio/StudioHeader.vue")['default']>
export const LazyStudioSidebarLeft: LazyComponent<typeof import("../app/components/studio/StudioSidebarLeft.vue")['default']>
export const LazyStudioSidebarRight: LazyComponent<typeof import("../app/components/studio/StudioSidebarRight.vue")['default']>
export const LazyBarChartBlock: LazyComponent<typeof import("../app/components/studio/blocks/BarChartBlock.vue")['default']>
export const LazyBlockRenderer: LazyComponent<typeof import("../app/components/studio/blocks/BlockRenderer.vue")['default']>
export const LazyKpiBlock: LazyComponent<typeof import("../app/components/studio/blocks/KpiBlock.vue")['default']>
export const LazyLineChartBlock: LazyComponent<typeof import("../app/components/studio/blocks/LineChartBlock.vue")['default']>
export const LazySearchBlock: LazyComponent<typeof import("../app/components/studio/blocks/SearchBlock.vue")['default']>
export const LazyTableBlock: LazyComponent<typeof import("../app/components/studio/blocks/TableBlock.vue")['default']>
export const LazyTextBlock: LazyComponent<typeof import("../app/components/studio/blocks/TextBlock.vue")['default']>
export const LazyBlockWrapper: LazyComponent<typeof import("../app/components/studio/canvas/BlockWrapper.vue")['default']>
export const LazyCanvasGrid: LazyComponent<typeof import("../app/components/studio/canvas/CanvasGrid.vue")['default']>
export const LazyCanvasPageTabs: LazyComponent<typeof import("../app/components/studio/canvas/CanvasPageTabs.vue")['default']>
export const LazyCanvasSection: LazyComponent<typeof import("../app/components/studio/canvas/CanvasSection.vue")['default']>
export const LazyCanvasZone: LazyComponent<typeof import("../app/components/studio/canvas/CanvasZone.vue")['default']>
export const LazyAddSourceModal: LazyComponent<typeof import("../app/components/studio/sidebar/AddSourceModal.vue")['default']>
export const LazyBlockConfigPanel: LazyComponent<typeof import("../app/components/studio/sidebar/BlockConfigPanel.vue")['default']>
export const LazyDynamicParamsPanel: LazyComponent<typeof import("../app/components/studio/sidebar/DynamicParamsPanel.vue")['default']>
export const LazySidebarBlocks: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarBlocks.vue")['default']>
export const LazySidebarDataSources: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarDataSources.vue")['default']>
export const LazySidebarLayouts: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarLayouts.vue")['default']>
export const LazySidebarVariables: LazyComponent<typeof import("../app/components/studio/sidebar/SidebarVariables.vue")['default']>
export const LazyTvAudiencesEvolutionChart: LazyComponent<typeof import("../app/components/tv/TvAudiencesEvolutionChart.vue")['default']>
export const LazyTvAudiencesRankingTable: LazyComponent<typeof import("../app/components/tv/TvAudiencesRankingTable.vue")['default']>
export const LazyTvAudiencesTop50Table: LazyComponent<typeof import("../app/components/tv/TvAudiencesTop50Table.vue")['default']>
export const LazyTvProgrammeCardIcon: LazyComponent<typeof import("../app/components/tv/TvProgrammeCardIcon.vue")['default']>
export const LazyTvReviewModal: LazyComponent<typeof import("../app/components/tv/TvReviewModal.vue")['default']>
export const LazyTvScheduleChannelRow: LazyComponent<typeof import("../app/components/tv/TvScheduleChannelRow.vue")['default']>
export const LazyTvScheduleGrid: LazyComponent<typeof import("../app/components/tv/TvScheduleGrid.vue")['default']>
export const LazyTvScheduleNowNext: LazyComponent<typeof import("../app/components/tv/TvScheduleNowNext.vue")['default']>
export const LazyTvScheduleProgrammeBlock: LazyComponent<typeof import("../app/components/tv/TvScheduleProgrammeBlock.vue")['default']>
export const LazyTvScheduleTimeline: LazyComponent<typeof import("../app/components/tv/TvScheduleTimeline.vue")['default']>
export const LazyAppAvatar: LazyComponent<typeof import("../app/components/ui/AppAvatar.vue")['default']>
export const LazyAppButton: LazyComponent<typeof import("../app/components/ui/AppButton.vue")['default']>
export const LazyAppCheckbox: LazyComponent<typeof import("../app/components/ui/AppCheckbox.vue")['default']>
export const LazyAppColorPickerModal: LazyComponent<typeof import("../app/components/ui/AppColorPickerModal.vue")['default']>
export const LazyAppModal: LazyComponent<typeof import("../app/components/ui/AppModal.vue")['default']>
export const LazyAppSelect: LazyComponent<typeof import("../app/components/ui/AppSelect.vue")['default']>
export const LazyAppStepModal: LazyComponent<typeof import("../app/components/ui/AppStepModal.vue")['default']>
export const LazyAppWordmark: LazyComponent<typeof import("../app/components/ui/AppWordmark.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
