export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptCalendly, useScriptLinkedInInsight, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAccessibilityPreferences } from '../app/composables/useAccessibilityPreferences';
export { useActiveEditor } from '../app/composables/useActiveEditor';
export { useAppNotifications } from '../app/composables/useAppNotifications';
export { useAppTheme } from '../app/composables/useAppTheme';
export { useBlockData } from '../app/composables/useBlockData';
export { useChart } from '../app/composables/useChart';
export { useFavicon } from '../app/composables/useFavicon';
export { globalStatus, showGlobalStatus, hideGlobalStatus, GlobalStatusVariant } from '../app/composables/useGlobalStatusBar';
export { useStudioAutosave } from '../app/composables/useStudioAutosave';
export { CHANNEL_CHART_COLORS, useTvAudiences, YearDataWithChannel } from '../app/composables/useTvAudiences';
export { useTvSchedule } from '../app/composables/useTvSchedule';
export { useAppNotificationsStore } from '../app/stores/app-notifications';
export { useAuthStore } from '../app/stores/auth';
export { useContextStore, ContextState } from '../app/stores/context';
export { useCounterStore } from '../app/stores/counter';
export { useStudioDatasetsStore } from '../app/stores/studio-datasets';
export { useStudioStore } from '../app/stores/studio';
export { adminListUsers, adminUpdateUser, adminDeleteUser, adminRestoreUser, adminListChannels, adminGetChannel, adminCreateChannel, adminUpdateChannel, adminUploadChannelLogo, adminDeleteChannel, adminListReviewQuestions, adminCreateReviewQuestion, adminUpdateReviewQuestion, adminDeleteReviewQuestion, adminListCategories, adminCreateCategory, adminUpdateCategory, adminDeleteCategory, adminListPrograms, adminGetProgram, adminUpdateProgram, adminDeleteProgram, BROADCAST_TYPES, adminListBroadcasts, adminGetBroadcast, adminUpdateBroadcast, adminUpdateBroadcastAudience, adminDeleteBroadcast, AdminUser, PaginatedUsers, AdminChannel, PaginatedChannels, AdminReviewQuestion, AdminCategory, AdminProgram, AdminProgramDetail, PaginatedPrograms, BroadcastType, AdminBroadcast, PaginatedBroadcasts } from '../app/api/admin';
export { checkHandleAvailability } from '../app/api/channels-validation';
export { createChannel, getChannelCategories, getMyChannels, getChannels, getChannel, updateChannel, updateChannelProfile, updateChannelMedia, getChannelMembers, getChannelSubscribers, deleteChannel, channelCategoryLabels, ChannelCategory, CreateChannelPayload, ChannelProfile, Channel, ChannelCategoryItem, ChannelMember, ChannelSubscriber, UpdateChannelPayload } from '../app/api/channels';
export { STATSIO_API } from '../app/api/statsio-endpoints';
export { fetchStatsioAuthMe, fetchStatsioMe, updateProfile } from '../app/api/statsio-user';
export { fetchDatasets, fetchDatasetSchema, fetchDatasetPreview, updateDataset, deleteDataset, fetchBlockData, fetchSearchRows, fetchDistinctValues, fetchUserStatsDataDocuments, createStatsDataDocument, fetchPublicStatsDataCatalog, fetchStatsDataDocument, fetchPublicStatsDataDocument, saveStatsDataDocument, deleteStatsDataDocument, publishStatsDataDocument, DatasetPreview, StatsDataDocument } from '../app/api/studio';
export { fetchTvAudiences } from '../app/api/tv-audiences';
export { fetchBroadcast, toggleBroadcastView, fetchProgrammeSchedule, fetchBroadcastReviews, fetchReviewQuestions, submitBroadcastReview, BroadcastCategory, BroadcastDetail, BroadcastScoreSummary, ToggleViewResponse, ProgrammeBroadcast, ProgrammeSchedule, BroadcastReview, ReviewsResponse, ReviewQuestion, ReviewSubmitPayload } from '../app/api/tv-broadcast';
export { fetchChannelSchedules, invalidateDbChannelCache } from '../app/api/tv-schedule';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../node_modules/@pinia/nuxt/dist/runtime/composables';
export { useNuxtDevTools } from '../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';